### ISSUE TITLE
datadir not working consistently

### ISSUE THREAD

**Issue by ethers** [sigp/lighthouse#1006]
## Description

From https://lighthouse-book.sigmaprime.io/become-a-validator-source.html
Run all the lighthouse commands but specify a `-d someDataDir`

There appears to be some implied paths because when you get to
`lighthouse -d someDataDir validator`
You get:
`error: Unable to get voting keypair: Keypair file does not exist`

## Version

Lighthouse 0.1.1
testnet5 branch

## Present Behaviour

As above

## Expected Behaviour

`lighthouse validator -d someDataDir` shoud just work.

From user perspective, the different lighthouse commands should NOT require different datadir parameters.

Running 
`lighthouse -d someDataDir beacon ...`
`lighthouse -d someDataDir account ...`
`lighthouse -d someDataDir validator ...`

Also, the placement of `-d someDataDir` in the command line should not matter.  Does it matter?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by paulhauner** [comment]
I agree that the datadir is quite confusing as it is.

So there's two approaches to this:

1. `--datadir` is always `~/.lighthouse` (@ethers suggested this)
1. `--datadir` is application dependent (e.g., `~/.lighthouse/validator`, `~/lighthouse/beacon`)

(2) is completely un-opinionated, each component has its own directory. (1) is somewhat opinionated since it optimizes for the case where there's either 1 or 0 beacon nodes (BN) for each validator client (VC).

Let's assume the case where a system has 1x BN and 2x VC (violating the condition that (1) is optimized for). Their directory structure and commands might look like this:

#### Scenario (1)

Filesystem:
```
~/.lighthouse
  - validators
  - beacon
~/.lighthouse-2
  - validators
```

Shell:
```bash
lighthouse bn
lighthouse vc
lighthouse vc --datadir ~/.lighthouse-2
```

#### Scenario (2)

Filesystem:
```
~/.lighthouse
  - validators_1
  - validators_2
  - beacon
```

Shell:
```bash
lighthouse bn
lighthouse vc --datadir ~/.lighthouse/validators_1
lighthouse vc --datadir ~/.lighthouse/validators_2
```

In this scenario I think (2) looks better since there's no weird scenario where only one VC shares its datadir with the BN.

I just ran out of time, so I'll come back to this. I'll leave this here for now though.

**Comment by ethers** [comment]
app dependent datadir looks better for multiple validator scenario.  Main issue is documenting datadir well as scenario2 does.  It wasn't obvious bn and vc datadir should share a common parent dir but actually have different subdirs. Thanks

**Comment by AgeManning** [comment]
We have updated the datadir handling. Closing this issue for now.
