### ISSUE TITLE
Beacon node does not recover when eth1 node goes bad

### ISSUE THREAD

**Issue by ethers** [sigp/lighthouse#1023]
## Description

Beacon node is not robust enough, starts losing peers, and loses sync with the beacon chain, when the eth1 node goes bad.

## Version

testnet5 branch commit 93da74e7d630602efc6ccbf731128b90e28ae3a1

## Present Behaviour

Assume 3 nodes are all running fine: eth1, beacon, validator.
At some point the eth1 goerli node goes bad, possibly it crashes.
Eventually the beacon node also goes bad, and this leads to validator error: beacon node not synced.  (By the time I discover the issue, I don't have the logs to pinpoint more when the beacon node started going bad.)

## Expected Behaviour

I understand an ongoing eth1 is not crucial and should not degrade the beacon node.  Expect that the beacon node still remain in sync with the beacon chain, and that validator is all good. 

## Steps to resolve

Restart the eth1 and beacon nodes.
Throughout all this, the validator never needs to be restarted. Nice job on the robustness of the validator.

**Comment by paulhauner** [comment]
I don't see the connection between the eth1 node going down and the beacon node going down, apart from the fact that they happened consecutively.

The `testnet5` branch  is now basically end-of-life since it's from an older spec version. We've been working on spec `v0.11.1` over on the local `v0.2.0` branch and a new testnet is being launched in the coming days.

Unless there's some more info you can supply, I'll close this for now since:

- We don't have enough info to diagnose why the beacon node stopped following the head
- The `testnet5` branch is end-of-life so it's perhaps not worth going digging for it.

I appreciate you opening the issue though, sorry that you had issues with the BN.
