### ISSUE TITLE
Failed to start lighthouse (invalid testnet directory)

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1061]
Tried to run Lighthouse for the first time in many months. Followed the instructions (updated Rust, pulled latest, recompiled) and I'm getting the following error. I'm assuming I need to clear a directory somehow but the error message does not suggest any next steps.

```
Justins-MBP:lighthouse justin$ lighthouse -V
Lighthouse 0.2.0
Justins-MBP:lighthouse justin$ lighthouse beacon_node
Failed to start Lighthouse: The hard-coded testnet directory was invalid. This happens when Lighthouse is migrating between spec versions. Error : Unable to parse genesis state: OffsetOutOfBounds(3841354912)
Justins-MBP:lighthouse justin$ lighthouse
Failed to start Lighthouse: The hard-coded testnet directory was invalid. This happens when Lighthouse is migrating between spec versions. Error : Unable to parse genesis state: OffsetOutOfBounds(3841354912)
```

**Comment by JustinDrake** [comment]
I just did `rm -rf ~/.lighthouse` put didn't help.

**Comment by paulhauner** [comment]
Hi @JustinDrake :)

Are you running on the `testnet5` branch? This is what the [docs instruct](https://lighthouse-book.sigmaprime.io/become-a-validator-source.html#1-download-and-install-lighthouse), since it's the last branch that still points to our current testnet.

If you're on `master` then this is expected behavior until we have a testnet running.

I hoped the "This happens when..." message would be informative enough, but perhaps I need to change the message some more.

**Comment by JustinDrake** [comment]
> Are you running on the `testnet5` branch? This is what the docs instruct, since it's the last branch that still points to our current testnet.

Aha, I see what's going on :) The top "Documentation" link in `README.md` points to http://lighthouse-book.sigmaprime.io/. The top "Installation Guide" on that page points to https://lighthouse-book.sigmaprime.io/installation.html which does not mention the `testnet5` branch at all.

**Comment by paulhauner** [comment]
Good point, will fix this. Thanks.
