### ISSUE TITLE
Tidy `process_deposit`

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1076]
**Context**: I started yesterday to familiarise myself with the Lighthouse codebase. (I'm enjoyed it BTW—very readable and accessible.) I'll report issues and ask questions as I go along if that's OK :) Apologies in advance if I ask stupid questions :joy:

---

What is the purpose of the following snippet in `process_deposit`?

```rust
    let pubkey: PublicKey = match (&deposit.data.pubkey).try_into() {
        Err(_) => return Ok(()), //bad public key => return early
        Ok(k) => k,
    };
```

1) From what I can tell the `pubkey` variable is only used way down (`pubkey.into()` under "Create a new validator.").
2) If the public key is "bad" (what exactly does bad mean here?) then shouldn't `verify_deposit_signature(&deposit.data, spec).is_err()` cause `process_deposit` to return early anyway?
3) As a nitpick the comment `//bad public key => return early` is a bit sloppy. (Missing space after `//`, missing capitalisation of `bad`, missing `.` at the end, use of `=>`.)

**Comment by paulhauner** [comment]
> From what I can tell the pubkey variable is only used way down (pubkey.into() under "Create a new validator.").

Ordering here is indeed a bit odd. I suspect it's because `get_existing_validator_index` used to take a `PublicKey` not a `PublicKeyBytes`, but not sure.

I'd be tempted to move the `try_into` higher up in the function so we can fail earlier if we get junk BLS. @michaelsproul, thoughts?

> If the public key is "bad" (what exactly does bad mean here?) then shouldn't verify_deposit_signature(&deposit.data, spec).is_err() cause process_deposit to return early anyway?

We have two ways to represent a public key:

  - `PublicKeyBytes`: some bytes that are supposed to be a compressed pubkey.
  - `PublicKey`: an actual decompressed pubkey.

What you're seeing is a conversion from `PublicKeyBytes` to `PublicKey` that will fail if `PublicKeyBytes` doesn't represent a point on the curve.

The problem with only having a `PublicKeyBytes` struct and decompressing each time we do signature verification is that it does repeated decompression (not cheap). It is primarily for this reason we maintain these two structs throughout the codebase.

On a side-note, we also maintain a [ValidatorPubkeyCache](https://github.com/sigp/lighthouse/blob/master/beacon_node/beacon_chain/src/validator_pubkey_cache.rs) on the `BeaconChain` that we use to keep all known pubkeys in decompressed form in RAM, making the assumption that `ETH1_FOLLOW_DISTANCE` means finality for eth1. This struct will probably need re-thinking when we start re-using validator indices, but I think that'll be a matter of representing them as `(epoch, index)` tuples; a bridge we can cross when we come to it.

> As a nitpick the comment //bad public key => return early is a bit sloppy. (Missing space after //, missing capitalisation of bad, missing . at the end, use of =>.)

Yep, good point, it's not consistent with the rest of our code. Git blame says that an external contributor did this and I didn't pick it up in a PR review.

In order to close this issue I think we should:

- Decide if we're going to move that `try_into` (cc @michaelsproul)
- Tidy that comment

**Comment by JustinDrake** [comment]
> We have two ways to represent a public key

That makes sense. Since decompression is expensive do you maintain a cache mapping compressed to uncompressed keys?

**Comment by paulhauner** [comment]
> Since decompression is expensive do you maintain a cache mapping compressed to uncompressed keys?

We don't maintain an arbitrary cache of compressed bytes -> uncompressed bytes, if that's your question. We keep that `ValidatorPubkeyCache` instead, which does validator index -> uncompressed struct representation.
