### ISSUE TITLE
Isolate consensus from the rest of the codebase

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1089]
In Bitcoin-land they have isolated the consensus part in a library called [Libbitcoin Consensus](https://github.com/libbitcoin/libbitcoin-consensus). Isolating the consensus logic into a separate library (I guess in Rust that means a separate crate?) comes with  bunch of security advantages:

* easier to reason about and audit
* minimises complexities arising from unforeseen interactions with the environment (database, networking, etc.)
* allows for security-conscious processes to be enforced (e.g. require at least 3 reviewers to merge a PR, whereas the non-consensus critical part of the codebase can have just 1 reviewer in addition to the author)
* allows for reusability without too much baggage (e.g. for fuzzing efforts that only want to fuzz consensus)

In my mind Ligthouse's mission is to build the most secure Eth2 client and as such isolating consensus from the rest of the codebase feels natural. The earlier such a refactor is done the less painful it will be. (Bitcoin did this relatively late in the game and it was painful—it took years if I recall correctly.)

**Comment by paulhauner** [comment]
I also agree that isolating consensus code is desired. We already do separate it into crates, where `/eth2/state_processing` and `eth2/proto_array_fork_choice` are the top-level consensus crates. Below them we only have:

- `eth2/utils/bls`
- `eth2/utils/ssz_types`
- `eth2/utils/merkle_proof`
- `eth2/utils/safe_arith`
- `eth2/types`
- `eth2/utils/eth2_hashing`
- `eth2_utils/int_to_bytes`

Each of these crates are a series of pure functions completed abstracted from databases, networking etc. They're tested and fuzzed independently and can be audited stand-alone.

@JustinDrake in another chat you suggested moving it into another repo, I'm not particularly enthused about this. At one stage we did split apart our repos and we found that having a single "monorepo" was much easier to manage for:

- Project management: a single place to raise issues, manage milestones, etc.
- Everyday development: debugging or developing across two separate repos means you need to make modifications to the `Cargo.toml` into order to pull your deps locally instead of via Github. This gets annoying for core devs (e.g., I just spent an hour debugging only to realise I was using the wrong dep) and it's also another barrier-to-entry for contributors that needs to be documented.

Perhaps there's a middle ground, though. As expressed in #467, I'm not particularly fond of our current, emergent directory structure (e.g., why is something in `eth2` but not `eth2/utils`?). So, here's an updated proposal that includes separation of consensus code: https://github.com/sigp/lighthouse/issues/467#issuecomment-622248701.

I believe this proposed directory structure would address @JustinDrake's points first, second and fourth points quite simply. The second point is more of a challenge though:

> allows for security-conscious processes to be enforced (e.g. require at least 3 reviewers to merge a PR, whereas the non-consensus critical part of the codebase can have just 1 reviewer in addition to the author)

As far as I can tell, with vanilla Github we can't say "this dir requires one review and this dir requires three", however I'm pretty sure we can use the [Mergable](https://probot.github.io/apps/mergeable/) bot with the [Change Set](https://github.com/mergeability/mergeable#change-set) config. We would have to throughly review the permissions of the bot before letting it anywhere near the repo, of course.

**Comment by JustinDrake** [comment]
> Below them we only have:

Enumerating all the consensus dependencies like that is helpful for me in the short term to familiarise myself with the codebase :)

> Each of these crates are a series of pure functions completed abstracted from databases, networking etc. They're tested and fuzzed independently and can be audited stand-alone.

👍👍👍

> here's an updated proposal that includes separation of consensus code

Directory separation of consensus code is definitely helpful 👍

> I'm pretty sure we can use the Mergable bot with the Change Set config

Makes sense :)

**Comment by paulhauner** [comment]
I might close this one for now and it can live on via #467 :)
