### ISSUE TITLE
Rules for using `SafeArith`

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1098]
What are the rules for using `SafeArith`? For example, why is `safe_add` not used in

```rust
epoch + T::EpochsPerSlashingsVector::to_u64().safe_div(2)?
```

or

```rust
state.get_all_slashings().iter().sum::<u64>();
```

**Comment by paulhauner** [comment]
`SafeArith` was added a week or two ago so it's still pretty fresh, but we're using [clippy](https://github.com/rust-lang/rust-clippy) during CI to lint for unsafe arith in any crates where we [explicitly ask for it](https://github.com/sigp/lighthouse/blob/36f213c092eb4802e603cff5901269168637c3f6/eth2/state_processing/src/lib.rs#L1).

So, the rules _should_ be pretty simple: No unsafe arith in crates that have the linter enabled.

With the `epoch + ...` one, we've defined addition and subtraction on `Slot` and `Epoch` to be saturating. With the spec recently becoming clear about overflows, this might not be so good anymore and I'm now tracking it at #1100. But, to address your question: this is safe arith because it saturates.

WRT `.iter.sum()`, it seems that the safe arith linter isn't bullet-proof yet and @michaelsproul has patched some [holes](https://github.com/rust-lang/rust-clippy/pulls?q=is%3Apr+author%3Amichaelsproul) in it already. This seems like the sort of operation that could fly under it's radar. Would be keen to hear @michaelsproul thoughts on this.

Going to mark this as a bug since it seems like a scenario where the fuzzer will be able to trigger a panic.

**Comment by michaelsproul** [comment]
Ooh the `sum()` function is interesting. The lint doesn't inspect the code of called functions at all (and it would be unwise to make it do that IMO), but we could add a check for calls to `Iterator::{sum,product}` and any other functions that do meaningful arithmetic from `std`.
