### ISSUE TITLE
Update hash function

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#111]
## Description

The older spec used `blake2` as the hash function. The latest spec uses `keccak256`.

## Present Behaviour

Uses the old hash.

## Expected Behaviour

Should use the new hash.

## Steps to resolve

Use the correct hash function.

I started this work on a branch and seem to be triggering a panic due to this line:

https://github.com/sigp/signature-schemes/blob/master/src/amcl_utils.rs#L36

And think we should just update that crate to use keccak256 as well.

Figured I would open this up for discussion before making more changes.

**Comment by ralexstokes** [comment]
ideally that function is just generic over our hashing function... i just checked though and the tiny_keccak hash does not implement `std::hash::Hasher`

**Comment by paulhauner** [comment]
Oh yep, I didn't notice the change to keccack!

I also noticed that the hashing libs I saw didn't use `std::hash::Hasher`. I don't know/can't remember why that is.

I agree that it would be ideal that `signature-schemes` is generic over different hashers, but I wouldn't spend much time upgrading it because we're hopefully going to move to something by zcash in the medium-term.

Why exactly is there a panic due to lighthouse moving to keccack, I would have thought `signature-schemes` would be unaffected by how we hash?

**Comment by ralexstokes** [comment]
I believe it has to do w/ this:

https://github.com/sigp/lighthouse/blob/master/beacon_chain/utils/hashing/src/lib.rs#L13

and pretty sure it traces to this:

https://github.com/sigp/signature-schemes/blob/master/src/amcl_utils.rs#L36

Seems like `GroupG1::map_it` expects a buffer of a certain size (which is the panic I'm seeing)...

Is there a reason the buffer is this size?
