### ISSUE TITLE
Get rid of MemoryStore

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#1139]
## Description

This is aimed at code simplification that will ease introduction of atomic operations (https://github.com/sigp/lighthouse/issues/692).  [MemoryStore](https://github.com/sigp/lighthouse/blob/2955e6b941d719c46a326908bed7bd152eb53004/beacon_node/store/src/memory_store.rs#L13-L16) is meant as a faster version of LevelDB-based store for use in tests.  The problem is, with `fsync` disabled, LevelDB should perform on par with the current implementation of `MemoryStore`, i.e. `RwLock<DBHashMap>` so that `MemoryStore` becomes an unnecessary complication.  In addition to that, the `Store` trait along with `StoreItem` and `SimpleStoreItem` complicate database access (think using it atomically and safely) too and getting rid of `MemoryStore` can be seen as a first step towards getting rid of them too.  Therefore, this ticket proposes ditching `MemoryStore` in favor of plain `LevelDB` with `fsync=false`.

**Comment by paulhauner** [comment]
Seems reasonable to me. I can't think of a case where we _need_ `MemoryStore`.

Perhaps @michaelsproul can think of something?

**Comment by michaelsproul** [comment]
Yep I'm in favour of this.

For the `fsync=false` DB to be different from the regular DB also implies we need to turn `WriteOptions::sync` on, which we don't do at the moment. Once we do that we could even run the 

---

Longer-term, I'm also open to the idea of removing the `Store` trait, as it complicates the implementation of an LMDB backend (because you can't write `type Transaction<'a> = lmdb::RwTransaction<'a>`). BUT, we've settled on LevelDB for now because it's better for write-intensive workloads, and we could probably workaround the associated type issue by making a concrete transaction type shared by both DBs, like:

```rust
enum Transaction<'a> {
    LevelDBTransaction(leveldb::WriteBatch),
    LMDBTransaction(lmdb::RwTransaction<'a>),
}
```

Anyway, that's kind of off-topic, delete the memory store!!

**Comment by michaelsproul** [comment]
Ooh I just saw @adaszko's `do_atomically` API, which removes the need for the `Transaction` stuff I was talking about!

**Comment by adaszko** [comment]
Re `Transaction`: Are we talking about non-existent code?

**Comment by adaszko** [comment]
> Anyway, that's kind of off-topic, delete the memory store!!

👍

**Comment by michaelsproul** [comment]
> Re Transaction: Are we talking about non-existent code? It's not clear to me why it's even necessary.

You're right, it's not!

**Comment by adaszko** [comment]
Turns out using real LevelDB in place of MemoryStore is much much slower:
 * [MemoryStore](https://github.com/adaszko/lighthouse/runs/677696218) 36m 17s
 * [LevelDB](https://github.com/adaszko/lighthouse/runs/689756506) 1h 0m 19s

The diff: https://github.com/sigp/lighthouse/compare/master...adaszko:ditch-memory-store 
I'm gonna leave MemoryStore in place.

LevelDB [doesn't support 'in memory only' mode](https://github.com/dain/leveldb/issues/79) to which I attribute the slowdown (i.e. it still hits the disk).  Contrary to [RocksDB](https://github.com/facebook/rocksdb/wiki/RocksDB-In-Memory-Workload-Performance-Benchmarks) or [LMDB](https://stackoverflow.com/questions/36170778/in-memory-databases-with-lmdb).
