### ISSUE TITLE
VC issues when BN reports it is not syncing when first booted

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1234]
## Description

NA

## Version

`master`

## Present Behaviour

When the BN first starts some distance behind the head, it reports that it is not syncing until it finds some peers:

```json
{"is_syncing":false,"sync_status":{"starting_slot":0,"current_slot":25919,"highest_slot":25919}}
```

This causes the validator client to immediately start requesting and performing duties. Since the BN is so far behind, this causes very long skip-slots and excess resource consumption.

## Steps to resolve

It seems like we need to be able to detect the case where the BN:

- Has just started.
- Has not yet surveyed the status of other peers.

A simple-fix might be to get the VC to not produce blocks if the BN doesn't have any peers and BN has an old head (compared to slot clock). However this feels to me like it'll introduce new edge-cases with undesired behaviour.

Perhaps @AgeManning has some thoughts?

**Comment by AgeManning** [comment]
A few thoughts:

1. I built a /lighthouse/syncing endoint, which in this case will return "Stalled". We could use this endpoint and not do anything when the sync state is stalled. This probably isn't ideal as we are diverging from the official API's and our validator client would then be lighthouse specific. Also this endpoint isn't correct JSON atm, and if we are going to use it, should clean it up a bit. Was mainly for my use atm.

2. Change the `is_syncing` to true in this case. Not a huge fan of this as it will be inconsistent with the actual sync states we use in lighthouse, where `Stalled` is more accurate and used internally.  This probably a better solution to 1. however if we are choosing 2. over 1. because of conformance with other clients, then we would need other clients to also have this logic. 

3. Add a new endpoint and make it official that is like /validator/status that returns Ready or something when the BN is ready to accept validator input. 

4. /node/ heuristics. As you suggest we could add a check for number of peers and distance and deal with the edge cases as they come.

I'm down with any of these. My preferences would be 3, 1, 4, 2 each has obvious cons associated with them.

**Comment by ethDreamer** [comment]
I think this looks interesting but I have a few questions:
>This probably isn't ideal as we are diverging from the official API's

I wasn't aware there were official API's for the communication between the beacon node and validator node. I don't see that in the spec and it looks like Prysm uses their own API... 

> conformance with other clients

I remember a while back I asked Paul about this and he said the API wasn't standardized so you couldn't mix beacon and validators from different projects :/...

>Add a new endpoint and make it official
Make it official? I'm missing something fundamental here :/

**Comment by AgeManning** [comment]
Yeah, there is a drive towards standardising a beacon node's http API. 

The main repo holding the standards and where the final product once we all converge on an API will be here: https://github.com/ethereum/eth2.0-APIs

See the issues and PR's within. Also there is a discussion on the eth2 discord in the API's channel. 

Fundamentally, the idea is to standardise this API so users and developers will have a unified eth2 http api across all clients

**Comment by paulhauner** [comment]
All this logic has been refactored so this issue is stale.
