### ISSUE TITLE
Use monotonic clocks to compute slots

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#1343]
### The issue

Currently, we use system clock absolute time readings, by repeatedly calling `SystemTime::now().duration_since(UNIX_EPOCH).ok()?`:

https://github.com/sigp/lighthouse/blob/51fbaefe415abd35305b798fc3772afeccceddf4/common/slot_clock/src/system_time_slot_clock.rs#L13-L60

Every time that call is made, we risk reading a skewed time value, which can result for instance, in producing the same slot value twice if the clock has been set back by the NTP client daemon or even by the machine admin.

### How to fix it

It should be possible to base time slots computation on Rust's `Instant`s which are monotonic and never decrease.  The system time would be read exactly once, at Lighthouse's startup and all the computations would be computer relative to that one reading, avoiding thereby all the problems with system clock adjustments.

**Comment by paulhauner** [comment]
I assume that `SystemTime` and `Instant` would both handle leap seconds identically, but it would be worth confirming.

**Comment by michaelsproul** [comment]
A counter-point: sometimes the user might _want_ to affect the slot clock while the node is running, for example if their clock was out of sync when the system time was read at start-up and they've since run NTP (although arguably they could just restart).

Another issue could be the fact that `Instant`s aren't designed to be used as clocks, and are subject to dilation as described in their docs:

> Note, however, that instants are not guaranteed to be steady. In other words, each tick of the underlying clock may not be the same length (e.g. some seconds may be longer than others). An instant may jump forwards or experience time dilation (slow down or speed up), but it will never go backwards.

As far as I understand, `Instant`s are good for measuring durations of time over a short period (nanoseconds to minutes), but not over a long period (hours to weeks).

System time also seems more intuitive from a user's perspective. I would be quite baffled if my Lighthouse node started computing the wrong slots, yet my system clock showed that I was in sync with NTP servers and other nodes.

We could test it out though.

**Comment by adaszko** [comment]
`Instant`s are messier than I realized.  There doesn't seem to be a clearly better way than the current one, so I'm gonna close this issue.  Thank you for the feedback!
