### ISSUE TITLE
Fix double Lighthouse in --version

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1465]
## Description

Running `lighthouse --version` prints "Lighthouse" twice, which looks weird (see below). Similarly for `lighthouse -h`:

```
$ lighthouse -h
Lighthouse Lighthouse/v0.2.0/f26adc0a
Sigma Prime <contact@sigmaprime.io>
...
$ lighthouse --version
Lighthouse Lighthouse/v0.2.0/f26adc0a
BLS Library: blst
```

## Version

See above

## Present Behaviour

Lighthouse printed twice.

## Expected Behaviour

Lighthouse printed once.

## Steps to resolve

The `--version` option would be easy to fix, just change the format string. The `--help` might required digging around in clap configuration.

Alternatively, change the `VERSION` constant so that it's just the `v0.2.0/f26adc0a` part and add the Lighthouse prefix when constructing the default graffiti

**Comment by paulhauner** [comment]
So our official version string is: `Lighthouse/v0.2.0/f26adc0a`, but `clap` decides to prefix it with the name of the `clap::App`, which gives us `Lighthouse Lighthouse/v0.2.0/f26adc0a`.

We want to avoid going into the `common/lighthouse_version` crate and just stripping the `Lighthouse` there, because then it will be missing for the API and P2P network. Ideally we can just tell `clap` not to prefix the version string.

**Comment by torfbolt** [comment]
Looked into this briefly, looks like there's no option to skip printing the app name:
https://github.com/clap-rs/clap/blob/master/src/output/help.rs#L873

**Comment by minaminao** [comment]
Hi, I sent the PR directly because it was a simple issue.
