### ISSUE TITLE
Key files loading is slow and key management is difficult

### ISSUE THREAD

**Issue by somuchid** [sigp/lighthouse#1575]
Problem: 
1. loading takes 4 minutes for 500 validator, when validator process start up
2. hard to manage a few thousand files for 500 validators

Probable Cause: 
1. key store is file base
2. each key file is on its own folder
3. each key file has a lock file, a secret file, and other files

Possible Solution:
-> check prysm's current solution
instant loading
just one file - all key stores and passwords are merged into one small text file
simple, clean, easy to manage

**Comment by danielschonfeld** [comment]
👍 to everything OP said, however, one advantage I believe lighthouse has that should and must be preserved is the notion of which accounts out of a given list, has had it's deposit go through.  Making running the 'deposit' functionality safe to run multiple times over the same given list of validator public keys.  

Example where that is useful, is if using geth, and the account locks on you cause you didn't know you had to specify and endless unlock timeout using '0' as the parameter.

**Comment by AgeManning** [comment]
The reason the loading is slow, is because there is a large `scrypt` parameter used in each of the keystores which adds to the keyfile's security. This could be reduced which would reduce loading times to next to nothing, but at the cost of the security of the keystore. 

As I understand, prysm decrypt all the keys and the resulting decrypted keys they combine into a single key file. The thing to be weary of is moving validator keys. If a key is then moved, it must also be removed from the grouped file as if you forget to remove from both, you could run two validators and get slashed. 

@paulhauner has been dealing with a lot of key management and may want to weigh in here as to the approach we should take going forward. 

We are particularly concerned with preventing any possible slashing scenarios with validators that use lighthouse, however there is a tradeoff for very large staking users UX and might we want to help accommodate this.

**Comment by somuchid** [comment]
prysm provides a delete function to remove keys from the single combined key file.
It also does de-dup when adding new keys or importing keys from launchpad / lighthouse.

All 3clients i tested, prysm, lighthouse and teku, have the mechanism in place to avoid duplicate keys.

To avoid key duplication across multiple clients, I created a shell script to detect duplicate between clients. The script is not complicated.

**Comment by somuchid** [comment]
cached keys works great. 1st time loading takes time, subsequent loading is instant.
better than prysm now. prysm has to keep wallet and its password online, not safe. lighthouse does not.
