### ISSUE TITLE
Discrepancies regarding the use of `decrease_balance`

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1677]
The function `decrease_balance` (which is defined in `common/mod.rs`) is only used once in `slash_validator`. In `process_slashings` you explicit avoid using `decrease_balance`:

```rust
            // Equivalent to `decrease_balance(state, index, penalty)`, but avoids borrowing `state`.
            state.balances[index] = state.balances[index].saturating_sub(penalty);
```

Similarly, `decrease_balance` is avoided in `process_rewards_and_penalties`. A couple questions:

1) What does "avoid borrowing `state`" mean, and what is the advantage versus called `decrease_balance`?
2) Why is `decrease_balance` not avoided in `slash_validator`? Why not be consistent with `process_slashings`?

**Comment by paulhauner** [comment]
I haven't looked into this deeply, but for a quick triage:

1. "Borrowing state" is to do with Rust's ownership system. It's generally *the* learning curve with Rust, so I won't go into it in detail but a borrow is akin to taking a reference but with lots of additional constraints from the compiler. These constraints exist generally to allow Rust to be GC-free and also to prevent variable-access race-conditions between threads. The constraints are generally great, but sometimes you need to work a little harder to satisfy the compiler that you're being safe. I think that's the case here.
1. I think it's because we're not already iterating through the state, but I'm not sure.

We'll look into this in the short-term and get back with a proper answer :)

**Comment by michaelsproul** [comment]
@paulhauner's analysis is spot on, in that this is a constraint imposed by Rust's type system due to the fact that `state.validators` is being iterated here:

https://github.com/sigp/lighthouse/blob/a1a6b01acb44d9c9a336524cc9a3997b8aaad0fe/consensus/state_processing/src/per_epoch_processing/process_slashings.rs#L19-L35

We can't obtain a mutable reference to `state` inside that loop, because part of it (`state.validators`) is already borrowed mutably.

If we wanted to use a function called `decrease_balance` in both places, we would have to change the definition of `decrease_balance` to only borrow the `state.balances` field that it's _really_ interested in, like:

```rust
/// Decrease the balance of a validator, saturating upon overflow, as per the spec.
///
/// Spec v0.12.1
pub fn decrease_balance(balances: &mut [u64], index: usize, delta: u64) {
    balances[index] = balances[index].saturating_sub(delta);
}
```

And then we would call it like this in that loop (and in `slash_validator`):

```rust
decrease_balance(&mut state.balances, index, penalty);
```

I think both options are similar in terms of elegance/similarity to the spec. Having `decrease_balance` take `&mut state.balances` is itself kind of mysterious, in which case the explicit comment about this being a Rust-specific thing isn't so bad IMO.

**Comment by JustinDrake** [comment]
Thank you for the explanations :) I'll let you address and close this issue as you see fit.

**Comment by michaelsproul** [comment]
I'm going to close for now, but I'll keep it in mind, particularly if anyone else gets tripped up by it
