### ISSUE TITLE
Beacon node randomly closed with "SyncedKilled" message.

### ISSUE THREAD

**Issue by DaveFlowberries** [sigp/lighthouse#1679]
## Description

Noticed my node was offline. Looked at the history and it shows "SyncedKilled" : (last line not shown as it just shows lighthouse dir after the beacon node closed)
![Screenshot from 2020-09-28 21-38-09](https://user-images.githubusercontent.com/25303159/94440125-d9e01280-01d3-11eb-8d89-5090b11ba922.png)

## Version
Lighthouse/v0.2.11-a97ec318
I build from source. 

## Present Behavior

It is working. (Previously running for many weeks without issue. First time seeing this.)

## Expected Behavior

Not randomly shut down.

## Steps to resolve

Start the beacon node again.

## System Specs

x64, Ubuntu Desktop 20.04, 16 GB Ram, Rx-427bb × 4 CPU

##  Apps running

Prysm, LIghthouse, Geth, Firefox, Astrill VPN

**Comment by paulhauner** [comment]
This would be a `Synced` message that just happened to be half-way printing when a `Killed` message was fired.

This generally means you've run out of RAM and the OS has killed Lighthouse because it requires more memory than is available. That `Killed` message doesn't come from LH, it comes from the OS.

With that list of running apps it seems fairly likely that RAM was exhausted.

I'll close this for now, but feel free to reopen if you disagree with my conclusion :) Thanks for reporting.
