### ISSUE TITLE
Parasitic voluntary exits

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1709]
This is a small DoS vector. Validators can craft voluntary exits with a super large `exit.epoch`. For all practical purposes these voluntary exit messages will never be valid. Nonetheless, such exists persist `prune_voluntary_exits`.

Every signed voluntary exit is something like 96 + 8 + 8 + overhead, say 130 bytes. So with 1M validators a 1/3 attacker could consume ~43MB of RAM. Possibly meaningful for constrained devices.

The easy fix is to require voluntary exists to become valid quickly enough to warrant being saved in RAM.

**Comment by paulhauner** [comment]
Thanks @JustinDrake. I've only labelled this `A1` since the `A0` deadline is so close that we won't be able to implement in time.

**Comment by michaelsproul** [comment]
43 MB of RAM at 1M validators is quite inconsequential IMO, there are many more things that a 1/3 attacker could do at that scale that would cause us to use vastly more CPU and memory. For example, they could create lots and lots of maximum-length forks in the chain (a new fork for every block proposal), which would cause us to run heaps of state processing computations and store heaps of states in memory and on disk. This attack would be on the order of 100s of GB of data (due to our somewhat naive approach to state storage), and would be very similar to what caused us to crash during the Great Medalla Outage. The difference on Medalla was that the forks weren't being crafted maliciously, so we could mitigate the issue with the `--max-skip-slots` fix (https://github.com/sigp/lighthouse/issues/800)

**Comment by michaelsproul** [comment]
Closing as invalid
