### ISSUE TITLE
Racy seen caches

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1719]
## Description

The [`lift_locks`](https://github.com/sigp/lighthouse/tree/lift-locks) branch contains some work to remove some `RwLock`-based race conditions from the `BeaconChain` "seen caches".

The following diff is my solution to this issue:

https://github.com/sigp/lighthouse/compare/4b128ee8494b1775dd285c8d0f56b1a5025f1d20..dc76a3340c6b012ea0083343104889ae9831b8ce

## Steps to resolve

Take the `lift_locks` branch, rebase it on master (or whatever git strategy you want) and get it ready to merge into master. Also, check that my changes are sane.

**Comment by michaelsproul** [comment]
I think we're seeing this manifest in errors like:

```
Nov 03 06:30:51.979 WARN BlockProcessingFailure                  outcome: ObservedAttestationsError(IncorrectSlot { expected: Slot(511412), attestation: Slot(511411) }), msg: unexpected condition in processing block.
```

Because at the moment methods like `ObservedAttestations::observe_attestation` lock the datastructure to compute an index to mutate at, release the lock (allow concurrent mutation and shifting of the relevant index), and then mutate anyway at the precomputed index:

https://github.com/sigp/lighthouse/blob/0cde4e285ccd021f2564e0474b6dc981e5b5faa9/beacon_node/beacon_chain/src/observed_attestations.rs#L138-L151

**Comment by michaelsproul** [comment]
I'm working on this
