### ISSUE TITLE
Update last seen peer store variable

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1732]
## Description

Improve the resolution of the peer state in the peer store. 

- Update the last-seen instant in our peer store when we receive a ping/pong. These values are mainly for up to date information in our peer store. Nothing relies on this variable.
- Update the state of peers to dialing when they are being dialed (ensure that this is consistent throughout the code base). 
- Update the state of peers when attempting to disconnect

**Comment by blacktemplar** [comment]
I had a look at this issue and I am not sure if anything needs to be done here or if the issue is just outdated:

- Connected peers have no last-seen instant stored. We only store `since` variables for `Disconnected`/`Banned`/`Dialing`. For `Disconnected` and `Banned` we do not get any ping/pongs, for `Dialing` I am not sure. But also for `Dialing` the name since suggests that this is the time we started dialing (and not the time of the last ping/pong).
- As far as I can tell there is only one point in the code where we start dialing a peer: https://github.com/sigp/lighthouse/blob/9ee71d6fec643cb00e3ffcd39f4e7dd5d2a453f0/beacon_node/eth2_libp2p/src/peer_manager/mod.rs#L124-L127
 And in `connect_peer` we call `dialing_peer` that sets the status to `Dialing`.
- There are five situations in the code base where we create a `PeerManagerEvent::DisconnectPeer` event to disconnect a peer. As far as I can tell in all five situations we already update the status correctly (even though through different methods). There are two situations when we receive a disconnect from the other peer and in both situations the code contains a comment explicitly stating that we don't inform the peer manager about it. If this issue is about that and we should change this behaviour I can look into that, but I am not sure if that is what is wanted here.

**Comment by AgeManning** [comment]
Previously we were storing time last seen in the connected state. This was planned to be used to positive scores. This issue was originally designed to update these. 

So it sounds this is out-dated.
