### ISSUE TITLE
/eth/v1/debug/beacon/states/genesis issues

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#1776]
Running against a relatively recent master:

```
$ git rev-parse HEAD
e9d5bade367e4720a0ceea9d15fe994256f5ead6
```

Node is synced to Medalla.

Test run of `/eth/v1/debug/beacon/states/genesis` against the new API showed up a couple of issues.

Firstly, it returned the current state rather than the genesis state:

```
      "slot": "505608",
```

Second, the previous justified checkpoint information appears incorrect (a duplicate of the current justified checkpoint):

```
      "previous_justified_checkpoint": {
        "epoch": "15705",
        "root": "0x66ba71dfb29bada27c3f99e9823dac4272ff1a057814d0672353358571cb0142"
      },
      "current_justified_checkpoint": {
        "epoch": "15705",
        "root": "0x66ba71dfb29bada27c3f99e9823dac4272ff1a057814d0672353358571cb0142"
      },
```

**Comment by realbigsean** [comment]
@mcdee Thanks for bringing these up! 

I've raised a pull request to resolve the genesis state issue.  I believe the issue with the `previous_justified_checkpoint` equaling the `current_justified_checkpoint` is due to the finality issues on Medalla. In [this](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#justification-and-finalization) portion of the eth2 spec, the `previous_justified_checkpoint` is updated to the `current_justified_checkpoint` before checking for participation.

**Comment by mcdee** [comment]
Two more items (I'll add them here because they are part of the same call): the `balances` and `slashings` arrays are returned as numbers but should be strings.
