### ISSUE TITLE
Metrics: Startup time

### ISSUE THREAD

**Issue by stefa2k** [sigp/lighthouse#1788]
## Description

There is currently no way to tell the startup time of lighthouse components, except using OS features. Accessing this information on OS level rises security concerns.

## Present Behaviour

No metrics of startup time/up time present.

## Expected Behaviour

Publishing information about startup time on `process_start_time_seconds` like teku and prysm do.

**Comment by paulhauner** [comment]
I'm not exactly sure what we'd publish in `process_start_time_seconds`. It's not immediately clear to me what we're trying to measure here; startup is fairly complex and involves several components.

**Comment by stefa2k** [comment]
To my understanding Teku and Prysm return the unix timestamp of the start of the main process.

**Comment by Yoldark34** [comment]
@stefa2k 
Workaround for beacon node with validator monitor.

`validator_monitor_unaggregated_attestation_total*384`
Gives you the qty of seconds since restarted

Reduce to the last value if you got multiple validator. It will provide you with a good enough estimation of when your beacon node restarted.

Still looking for a reliable not resource intensive way to know when the validator process restarded

**Comment by Yoldark34** [comment]
@stefa2k 
For the validator process : 

`vc_signed_attestations_total*384 reduced / with validator_monitor_validators_total`
I dont undestand why i can't do in a single query
`vc_signed_attestations_total/validator_monitor_validators_total*384`

Best regards

**Comment by paulhauner** [comment]
> To my understanding Teku and Prysm return the unix timestamp of the start of the main process.

Oh I understand. Sorry, I was reading this as "the duration LH took to start up" instead of "the timestamp at which LH was started".

This seems quite easy to achieve.

**Comment by Yoldark34** [comment]
Thanks <3
