### ISSUE TITLE
Endpoint /eth/v1/validator/beacon_committee_subscriptions does not accept valid input

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#1820]
## Description

The API endpoint `/eth/v1/validator/beacon_committee_subscriptions` does not accept a valid input.

## Version

Recent master:

```
git rev-parse HEAD
a741553028e6e1d461e16e12b23f6402b3f7994d
```

## Present Behaviour

Sent the following to the `/eth/v1/validator/beacon_committee_subscriptions` endpoint:

```
[
  {
    "slot": "576391",
    "committee_index": "8",
    "committees_at_slot": "17",
    "is_aggregator": false
  }
]
```

(Note that the actual data was sent unformatted; this has been added for convenience of viewing.)

Received the response:

```
{
  "code": 400,
  "message": "BAD_REQUEST: body deserialize error: Request body deserialize error: missing field `validator_index` at line 1 column 88",
  "stacktraces": []
}
```

(Again, formatted for convenience.)

## Expected Behaviour

Would expect this to be accepted as it conforms to the format shown in https://ethereum.github.io/eth2.0-APIs/#/ValidatorRequiredApi/prepareBeaconCommitteeSubnet

**Comment by paulhauner** [comment]
We'll check it out, it's not always easy conforming to the ever-changing API spec lol

**Comment by paulhauner** [comment]
Oh yeah, we need the `validator_index` field so that we can do the random subnet subscription.

I had raised this somewhere on the APIs repo before, but I can't find it anymore. We've always had this in our API, I'm not sure why it never made it into the standard.

**Comment by AgeManning** [comment]
Yep I think we've had this discussion in the spec repository. 

We require in addition to the current fields a `validator_index` field. We use this so that we know how many validators are subscribed during any epoch. We require this knowledge so that we can subscribe to a fixed number of long-lived subscriptions for each connected validator. 

Fundamentally the beacon node needs to know how many unique validators are connected so that it can subscribe to a multiple of long-lived subnets. If there is another API endpoint that does this for us, perhaps we need to use that, this will involve changing the VC logic to use that endpoint.

**Comment by mcdee** [comment]
There was a discussion at https://github.com/ethereum/eth2.0-APIs/issues/98 regarding this.  The number of validators can be estimated from the number of short-lived beacon committee subscriptions, to within a reasonable margin of error.

**Comment by paulhauner** [comment]
Closing since the `validator_index` field has been added to the spec: https://github.com/ethereum/eth2.0-APIs/pull/110
