### ISSUE TITLE
Close frame for closed substream

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#1832]
## Description

On latest versions (around ~0.3.0) we started getting this error
```bash
Oct 26 22:24:57.797 DEBG RPC Error
err: IO Error: Protocol error: Received `Close` frame for closed substream.
protocol: metadata
service: libp2p
```

This debug msg is printed, as far as I can tell, exclusively on metadata messages, but there is also this log:
```bash
Oct 26 22:32:45.009 DEBG Connection closed
connections: 0
cause: Some(IO(Custom { kind: Other, error: "Protocol error: Received `Close` frame for closed substream." }))
service: libp2p
```

This means this error is killing connections with peers, most likely quite rapidly. I expect this to affect head syncing the most

We should investigate what's the source of these errors and check if they really should be killing connections with a peer

## Version
 master on 92c8eba8ca337b93c15e65e958b011ac4aeef9a7

## Present Behaviour

Connections are killed by this errors

## Expected Behaviour

Probably ignore the error

## Steps to resolve

detective tasks

**Comment by romanb** [comment]
Does this error occur

  a) between communicating nodes that all use the same `rust-libp2p` version?
  b) between communicating nodes that use different `rust-libp2p` versions?
  c) between nodes using `rust-libp2p` and nodes using other libp2p implementations?

If `a)`, it may indicate a bug in `rust-libp2p`. If `b)` it may indicate that older versions of `rust-libp2p` potentially send duplicate `Close` frames and the newer version thus needs to be more lenient to maintain backwards-compatibility. If `c)` it may indicate that `rust-libp2p` needs to be more lenient in accepting duplicate `Close` frames because other implementations may send them.

cc @mxinden

**Comment by divagant-martian** [comment]
Thanks @romanb after checking some more this only happens with a golang client, so I guess `c` it is

**Comment by romanb** [comment]
Thanks for the feedback. `libp2p-mplex-0.23.1` has been published which should resolve this problem by ignoring duplicating `Close` frames, as was the case in earlier versions.

**Comment by divagant-martian** [comment]
Hey  @romanb, thanks a lot. I'll close after we can upgrade and test
