### ISSUE TITLE
Fix disabled Eth1Block test

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1835]
## Description

As per https://github.com/sigp/lighthouse/pull/1765#discussion_r513205310, we need to resolve this:

https://github.com/sigp/lighthouse/blob/2eced35a631a032615c182a0411c4e3d1b166f4c/testing/ef_tests/tests/tests.rs#L193-L194

## Notes

- Only valid once #1765 is merged.
- Will conflict with #1691, probably best to wait until its merged.

**Comment by michaelsproul** [comment]
I'm removing this FIXME in https://github.com/sigp/lighthouse/pull/2279 because I don't think that test is relevant to us. The `Eth1Block` from the spec is a loosely defined object, and our `Eth1Block` has two more fields than it:

https://github.com/sigp/lighthouse/blob/b34a79dc0b02e04441ba01fd0f304d1e203d877d/common/eth2/src/lighthouse.rs#L173-L181

**Comment by michaelsproul** [comment]
Same reasoning applies to new merge type `PowBlock`.
