### ISSUE TITLE
Latest lighthouse does not respect target-peers

### ISSUE THREAD

**Issue by torfbolt** [sigp/lighthouse#1843]
## Description

Most or all of the recent lighthouse builds do not seem to respect the peer number target. Looking at https://eth2stats.io/medalla-testnet, there are lots of clients in the 400-500 peer range. At least in my case this results in severely degraded performance of my internet connection.

## Version

Regression, at least since 0.3.1

## Present Behaviour

The beacon node seems to connect to as many peers as it can find.

## Expected Behaviour

Limit connections to roughly the target value (default 50).

## Steps to resolve

Run lighthouse on the medalla testnet. Setting an explicit value of `--target-peers 30` does not help.

**Comment by michaelsproul** [comment]
The problem is actually in the eth2 stats client rather than Lighthouse itself. Eth2 stats reports all the peers the node has ever seen, rather than just the ones that it is connected to (more info: https://github.com/Alethio/eth2stats-client/issues/66)

If you check your BN logs, you'll see that the peer count reported is still ~50

**Comment by AgeManning** [comment]
This is an eth2-stats issue. 

Lighthouse has implemented the eth2-api's for this endpoint as the spec describes, eth2-stats is consuming it incorrectly.
