### ISSUE TITLE
v0.3.3 beacon_node db uses large amount of disk space from fresh sync even after Medalla finalized

### ISSUE THREAD

**Issue by jerryji** [sigp/lighthouse#1866]
## Description

v0.3.3 beacon_node db uses large amount of disk space from fresh sync after Medalla finalized

## Version

Lighthouse v0.3.3 compiled from master

## Present Behaviour

After Medalla (re)finalized on 04-Nov-2020, the beacon_node db still grows to more than 90G from a _fresh sync_

## Expected Behaviour

Ideally the db size should be around 8G

## Steps to resolve

No known workaround

**Comment by ChuckNorrison** [comment]
My chain_db is 94GB on Mainnet after sync. Any recommendations on amount of disk space to keep free over next 3 years? In a thread it was meant to grow once to max amount and then it will try to force sync which should reduce the db again. But as i understand we need to get the full amount of the beacon chain available for now

**Comment by michaelsproul** [comment]
This might be because the node witnessed the Medalla chaos via sync (i.e. it downloaded all the stray blocks), even if it synced after it all occurred. Nonetheless, the fix is the same:

There's a known issue where LevelDB is really slow at reclaiming space after the database grows. We're seeing that a lot on nodes that were running throughout the period of non-finality. I just tested a rough fix on my node (invoking LevelDB's compaction), and it shrank the DB from 90GB+ to 8.9GB, with a runtime of ~1 minute. I'll polish the code and put a PR up early next week, we'll ship a new release, and everyone's databases can go back to being <20GB :tada: 

For mainnet, I think it makes sense to leave a bit of headroom and not rely on the DB being any smaller than 128GB. I suspect many people will be running on 1TB SSDs, particularly if they're running a Geth instance.

**Comment by jerryji** [comment]
@michaelsproul Thank you so much for the PR and explanation.

> For mainnet, I think it makes sense to leave a bit of headroom and not rely on the DB being any smaller than 128GB.

Just to confirm: does it mean even with your PR the mainnet db could still grow upto 128GB despite the lesser probability / shorter duration of non-finality?

**Comment by paulhauner** [comment]
I believe @michaelsproul is working on a fix to this :)

**Comment by michaelsproul** [comment]
> I believe @michaelsproul is working on a fix to this :)

Yep! PR is up now https://github.com/sigp/lighthouse/pull/1871

> Just to confirm: does it mean even with your PR the mainnet db could still grow upto 128GB despite the lesser probability / shorter duration of non-finality?

@jerryji Kind of. If the non-finality duration isn't as long, then the database won't grow as large, but I think we should be prepared for the worst.

I also realised that the disk usage during sync could be due just to the canonical chain. Without finalization, we store a (heavy) `BeaconState` in the hot DB every epoch, and for 4000 epochs of non-finality, that's a lot of space. To sync Medalla will now require ~90GB disk space (assuming the worst), even if we were to adopt other disk usage reductions (like #1872). Fixing this would require substantial changes to sync and the database which I don't think are viable before mainnet.
