### ISSUE TITLE
Improvement suggestion : change endpoints' fallback behavior

### ISSUE THREAD

**Issue by romanoLT** [sigp/lighthouse#2050]
When using eth-endpoints, there can be situation when you need to restart your full node and it's running a bit late to catch-up with the highest block in eth1.
The thing is even though you can specify several end points, lighthouse seems to care only if node N is unreachable. If lighthouse can speak with the eth1 node, even being late of the synchronisation it doesn't use the fallback.
It would be great to force lighthouse to use endpoint N+1 until endpoint N is synced again?

**Comment by blacktemplar** [comment]
Lighthouse should use the fallback as soon as the eth1 endpoint is unsynced AND "far behind". By "far behind" we mean that `remote_head_block.timestamp + ETH1_FOLLOW_DISTANCE / 2 * SECONDS_PER_ETH1_BLOCK < now`. Since we are only interested in the eth1 blocks before the `ETH1_FOLLOW_DISTANCE` this should be enough to ensure that we always get all blocks we need.

If you have witnessed another behavior please post some logs, because that would be a bug.

**Comment by realbigsean** [comment]
I believe the fallback implementation is in line with the requested behavior in this issue
