### ISSUE TITLE
--beacon-node flag broken in v1.0.5

### ISSUE THREAD

**Issue by hukkinj1** [sigp/lighthouse#2118]
## Description

The `--beacon-node` flag should be deprecated in v1.0.5, but seems completely broken. I'm running with `lighthouse-docker` and keep getting the following logs on startup
```
WARN Offline beacon node
WARN Unable to connect to a beacon node
```

## Version

Docker tag `v1.0.5`

## Present Behaviour

Validator not connecting to beacon node with `--beacon-node`

## Expected Behaviour

Validator connects to beacon node with `--beacon-node`

## Steps to resolve

Run `lighthouse-docker`

**Comment by paulhauner** [comment]
Thanks for raising this @hukkinj1.

It seems the issue is here:

https://github.com/sigp/lighthouse/blob/9ed65a64f8fc518c98b381e628556df9bf906acb/validator_client/src/config.rs#L109-L111

We assume that if `beacon-nodes` is `Some`, then it has been provided on the CLI. However, this is not true since it has a default value and will always be `Some`:

https://github.com/sigp/lighthouse/blob/9ed65a64f8fc518c98b381e628556df9bf906acb/validator_client/src/cli.rs#L26

I think we need to use [`is_present`](https://docs.rs/clap/3.0.0-beta.2/clap/struct.ArgMatches.html#method.is_present) instead. I'm not certain, but *I think* it allows us to differentiate between the default value and no provided value. Unit testing would be required to prove this.

This is indeed a bug, and an annoying one at that. I reviewed the PR that contained this bug and I failed to catch it. My sincere apologies.

**Comment by paulhauner** [comment]
Users with this issue should switch to the `--beacon-nodes` flag until we can get a fix out. This might not be possible until next year, considering that although this bug is annoying it's not necessarily critical.
