### ISSUE TITLE
libc dependency change GLIBC_2.25

### ISSUE THREAD

**Issue by syspulse** [sigp/lighthouse#2120]
## Description

libc dependency was upgraded in 1.0.5 build
Default Ubuntu 16.04 LTS is broken:
`/lighthouse: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.25' not found (required by ./lighthouse)`

This is a bit "painful" since nobody wants validator downtime and it is not 5 minutes fix to make it work on existing setup

## Version

**lighthouse 1.0.5**
**Ubuntu 16.04.7 LTS**

## Present Behaviour

Previous versions are working against libc-2.23

## Expected Behaviour

Ideally minor version upgrades should not break core system libraries dependency where laborous upgrade/updage is required (manual recompile, OS install). 

## Steps to resolve

1. Build from source. It is about 1h to start from scratch and build lighhouse (rust, make upgrade, etc.).
2. Non-dynamic linking build option ?

**Comment by paulhauner** [comment]
I'm not exactly sure why the `GLIBC_2.25` tends to break, but I suspect it's related to BLST and @michaelsproul might have more info. In my experience a `cargo clean` resolves it. You're getting that issue at *compile time* right, not runtime?

If you check out the [cross-compiling](https://lighthouse-book.sigmaprime.io/cross-compiling.html) section of the docs you can see how to build portable binaries. For our nodes, I build the binary on my desktop and then push it out to the servers. I can run the binary built with `make build-x86_64` on a brand new Ubuntu install, no dependencies needed at runtime; we purposefully use static linking wherever possibe. I would suggest you do the same thing, it means there's no downtime if you have issues compiling.

I would also suggest upgrading to a newer Ubuntu, since 16 is now 4+ years old and you can get 18 and 20 in LTS now.

**Comment by michaelsproul** [comment]
I don't think this is related to BLST

It could be related to the fact the new automated release flow stopped building the x86_64 binaries inside the Cross Docker containers:

https://github.com/sigp/lighthouse/blob/9ed65a64f8fc518c98b381e628556df9bf906acb/.github/workflows/release.yml#L78-L84

Running `objdump -T lighthouse-v1.0.5 | grep GLIBC` on the portable binary reveals a dependency on `getentropy` that wasn't present in the v1.0.4 binary:

```
0000000000000000  w   DF *UND*  0000000000000000  GLIBC_2.25  getentropy
```

The build might try to use `getentropy` if it's available, which would explain why this occurred when we stopped building inside the Cross image.

I'm on leave until next week but can look into fixing it then (for v1.0.7). If you could continue building from source until then @syspulse it would be much appreciated :pray:

**Comment by syspulse** [comment]
@paulhauner It's not so much about upgrading and using latest LTS, but amount of effort it might require if your infra setup is "settled" and validators are working fine. 
I do suspect that a lot of validators are well beyond old LTS distros. For me the source build is very simple and that's what I immediately did. I hope for others who encounter this issue it will be painless as well.
@michaelsproul thanks for looking into it!

**Comment by paulhauner** [comment]
Yep, understood @syspulse. This was an unintentional break, so apologies for that.

> It could be related to the fact the new automated release flow stopped building the x86_64 binaries inside the Cross Docker containers:

@realbigsean, I forget why we couldn't use cross in the release CI..

**Comment by realbigsean** [comment]
> @realbigsean, I forget why we couldn't use cross in the release CI..

We can't use `cross` for macOS but we can use it for linux still.. I opted not to use it for either to keep the workflow simpler, so my bad here. I can update the workflow to use `cross` for linux in the next couple of days
