### ISSUE TITLE
Unable to get fork choice head: ... InvalidBestNode

### ISSUE THREAD

**Issue by clifton** [sigp/lighthouse#2128]
## Description

My beacon client was running for about 1 week uninterrupted and suddenly began to fail.

`Dec 28 17:01:05.696 CRIT Failed to start beacon node reason: Failed to build beacon chain: Unable to get fork choice head: ProtoArrayError("find_head failed: InvalidBestNode { start_root: 0xa498fe73df9ac05d997b9ca092b294eae91eb8e239946133e177ba3f684be028, justified_epoch: Epoch(6050), finalized_epoch: Epoch(6048), head_root: 0xa498fe73df9ac05d997b9ca092b294eae91eb8e239946133e177ba3f684be028, head_justified_epoch: Epoch(6048), head_finalized_epoch: Epoch(6047) }")`

## Version

Docker `sigp/lighthouse:v1.0.4`

## Present Behaviour

Fixed by deleting beacon folder and restarting client. I didn't have the foresight to retain the logs or data from the beacon folder, but I still have metrics for this time period if those would be helpful.

**Comment by paulhauner** [comment]
I'm going to close this one since I haven't seen it again and it seems unlikely that we're going to make progress on it at this point. Thanks for raising it @clifton.

I can't help but think it's some form of obscure database corruption.

I am *very* interested in hearing if this has happened again.
