### ISSUE TITLE
a lot of warning messages or error messages

### ISSUE THREAD

**Issue by GerardBri** [sigp/lighthouse#2332]
## Description

I monitor all logs from beacon and validators binaries, then if a log doesnt respect a pattern like "INFO", i raise an alert.  

And time to time, i 've got some alert on warning messages like :   

```
WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
```
or
```
WARN Listener error                          error: Custom { kind: Other, error: Other(A(A(Underlying(Os { code: 103, kind: ConnectionAborted, message: "Software caused connection abort" })))) }, service: libp2p
```

some of 
```
ERRO Fork choice failed                      location: block gossip, error: CanonicalHeadLockTimeout
```

and 
```
WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0x032cd19c1ff1ca9714f6d52b6acd9f57d7d1f13dd8c5f536e6c9a5c29ba085b0)), service: state_advance
```

Is there any fix possible or my beacon node had issues ?

## Version

Lighthouse v1.3.0-3a24ca5

## Present Behaviour

a lot of WARNING message, i've already set a list of  "normal warning" (which shouldn't exist from my point of view)
- `WARN Block arrived early`
- `WARN Banning peer that is currently disconnecting, peer_id:`
- `WARN Beacon chain re-org`
- `WARN Proposer duties re-org                  msg: this may happen from time to time, dependent_root: 0x..., prior_dependent_root: 0x..., service: duties`

## Expected Behaviour

Less of warning, error message or fix them ?

## Steps to resolve

run beacon node + validator for a long time.

**Comment by AgeManning** [comment]
These occur if your computer's CPU is overloaded. I.e it cannot process the required amount data in the time frame needed. 

What is the CPU usage on your machine and what are its specs?

**Comment by GerardBri** [comment]
I don't think the computer's CPU is overloaded, it's moreover underload

- I've got an max of **120%** CPU usage with `openethereum` running   (avg 40-80%)
- and `lighthouse` use about **~20%**,   
so **140%** usage with a 6x core CPU, we 're far from a full 600% usage.  

In addition :  
`load average: 0.72, 1.14, 1.43` which seems to be normal and underused with a 6x core CPU and 16GB of RAM

**Comment by michaelsproul** [comment]
Some of the logs you've posted are warnings to do with node performance and are legitimate cause for investigation, but you're right that some of the others are not. The ones that indicate real problems are:

- Timing out to a node's request. This shouldn't happen if your node is performing well. This often involves reading blocks from disk to serve to a peer, so it could be your I/O letting you down (or too many peers).
- Fork choice failing due to a lock timeout. This is indicative of something taking too long with the head lock, again could be I/O related (or maybe just bad luck and the lock getting starved).

The others about network status (re-orgs, proposer duty changes, early blocks) are to be expected from time to time and are usually nothing to worry about.

The reason we have these as warnings is that in some way it makes sense to have an alert level between `INFO` (everything is fine) and `ERRO`/`CRIT` (things are definitely screwed). Until we re-assess how we log in all of Lighthouse, I would disable alerts for warnings and instead treat them as meaning "something slightly interesting or strange happened". These warnings about network events also *could* be indicative of issues if they happened frequently (e.g. repeated re-orgs), and we currently shift that judgement onto the user rather than trying to codify rules about which kinds of re-orgs are allowable.

As another example, a user on Reddit recently found some invalid blocks on mainnet due to a warning:

https://www.reddit.com/r/ethstaker/comments/n31tkq/lighthouse_did_not_advance_head_state_reason/

**Comment by paulhauner** [comment]
I'm going to close this once since I can't see anything actionable here. Thank you for reaching out though :)

`WARN` logs don't always indicate an error. They're letting the user know that something sub-optimal is happening, which is not a cause for alarm itself. On our nodes, `CRIT` gets me out of bed and `ERRO` gets investigated next time I'm online. `WARN` gets added to todo list.

Here are all your `WARN`s detailed:

- `WARN Timed out to a peer's request.`: I don't see this one much, we'll keep an eye on it.
- `WARN Listener error `: I've never seen this before, but it's unsurprising that the OS occasionally does things we don't expect (but are able to handle gracefully).
- `WARN Did not advance head state`: this can happen occasionally with re-orgs. I wouldn't expect to see this much at all.
- `WARN Block arrived early`: a block arrived early, it might be because your clock is wrong or it might be someone else. Time is squishy and relative, if you see a lot of these, check your clock (as per error message).
- `WARN Banning peer that is currently disconnecting, peer_id:` this should be fixed in the next release, was sub-optimal behaviour on our end.
- `WARN Beacon chain re-org`: indicates that there's some disagreement among nodes on the network. Occasionally this will happen, but if you see a lot of these (e.g., multiple per minute) start to be concerned about the network.
- `WARN Proposer duties re-org`: as above.

I wish we could straight-up declare "this is ok" and "this is bad", but on a decentralized network that relies on a lot of different people it can be hard to make that call. This is why it's nice to have `WARN`, we can indicate that something isn't great but it might just be due to network irregularities. 

I hope this helps! :)
