### ISSUE TITLE
Validator monitor shows best effort inclusion as sub-optimal

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#2552]
## Description

For the per epoch report in the validator monitor logs, we show a `Sub-optimal inclusion delay` log for min inclusion distances > 1.
This is misleading to users in cases where the attestation was actually included optimally in the next non missed/ non orphaned slot.

## Version

unstable

## Expected Behaviour

Should show inclusion delay == optimal delay in cases where attestation was included in first block after the attestation was made. At the very least, the log should indicate that the inclusion delay may be incorrect because of missed/orphaned blocks.

## Steps to resolve

Not sure yet. Will investigate next week.

**Comment by michaelsproul** [comment]
We currently read the inclusion distance straight from the epoch processing summary, but this approach doesn't work for Altair and doesn't lend itself well to computing the best-effort inclusion delay.

Instead, I wonder if we could compute the minimum attestation inclusion distance per validator when we record attestations from blocks, here:

https://github.com/sigp/lighthouse/blob/b0ac3464ca5fb1e9d75060b56c83bfaf990a3d25/beacon_node/beacon_chain/src/validator_monitor.rs#L799-L808

I think the only extra bit of information we'd have to pass to that function is the slot of the block's parent (which is available), in which case the best-effort inclusion distance (0-optimal) is:

```
max(parent_slot - attestation.slot, 0)
```

or

```
parent_slot.saturating_sub(attestation.slot)
```

Which is fun because it doesn't even depend on `block.slot()`!

--

The downside to this is that it requires the validator monitor to have processed the blocks rather than just received the summary, which wouldn't be an issue most of the time, only after a restart.

**Comment by paulhauner** [comment]
>  I wonder if we could compute the minimum attestation inclusion distance per validator when we record attestations from blocks

It's not necessarily a deal breaker, but we'd have issues determining the correct inclusion distance when a block is orphaned.
