### ISSUE TITLE
Add test runner for new BLS tests

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2629]
## Description

There is a new suite of tests for BLS here: https://github.com/ethereum/bls12-381-tests/

Looking at the test format, it's very similar to the existing tests, so we should be able to re-use much of the code in `testing/ef_tests/src/cases/bls_*`.

**Comment by zsluedem** [comment]
@michaelsproul Hello. I am looking around and trying to take this one. But I am not sure if this issue is obsolete or not.

Currently, the BLS_tests are using the test cases provided in https://github.com/ethereum/consensus-spec-tests. But the latest version [1.2.0-rc.1](https://github.com/ethereum/consensus-spec-tests/tree/v1.2.0-rc.1/tests/general/altair/bls) of consensus-spec-tests already excluded these bls test cases generated by https://github.com/ethereum/bls12-381-tests/ and only keeps the eth related ones.

So the question is  -> how would you like this new suite of tests for BLS to be downloaded? Should I add a new download process from https://github.com/ethereum/bls12-381-tests/releases/tag/v0.1.1 ?

**Comment by michaelsproul** [comment]
Resolved by #3235!
