### ISSUE TITLE
Purge incompatible DB automatically when `--checkpoint-sync-url` is used

### ISSUE THREAD

**Issue by dong77** [sigp/lighthouse#2666]
If `--checkpoint-sync-url` is used, BN shall first try to get data from that URL for checkpoint sync. If no valid data is fetched, BN shall exit with an error message without modifying the database if it exists; if valid date is returned from the specified sync URL, BN shall delete the existing database if it is incompatible with checkpoint sync mode without the `--purge-db` flag used. This will enable a smooth transition from normal sync mode to the checkout sync mode.

**Comment by michaelsproul** [comment]
> This will enable a smooth transition from normal sync mode to the checkout sync mode.

We want to avoid deleting a good database unnecessarily. Most of the time when a beacon node restarts it will be pretty much fully synced, in which case it doesn't make sense to delete the entire database and start again. Checkpoint sync _does not_ help sync to head faster due to any algorithmic difference, but due to starting closer to the head, so there's nothing that a healthy, almost-synced BN can gain from using it.

We could attempt to detect the case where checkpoint sync _would_ be faster, but I fear this would be too uncertain to enable by default. It's not as simple as checking whether the database's current head is older than the checkpoint, because checkpoint sync also imposes the cost of backfilling all the blocks (extra work) which may not even be available (extra risk).

I think the current system where checkpoint sync can be triggered by stopping the node and adding `--purge-db`, or manually deleting the database – offers the right compromise between ease of use and protection from unnecessary re-syncing.

**Comment by michaelsproul** [comment]
> BN shall delete the existing database if it is incompatible with checkpoint sync mode

Just to clarify here, there's no such thing as a "database that is incompatible with checkpoint sync". Lighthouse can only tell the difference between:

1) A database with all historic states available, which could be the result of genesis sync OR checkpoint sync with `--restore-historic-states`: these databases end up exactly the same. OR
2) A database with some historic states missing, which must have been checkpoint synced. It may or may not (yet) have all blocks available. If historic state reconstruction isn't used then it will be forever identifiable as checkpoint synced.

i.e. if Lighthouse detects case (1) it shouldn't try to checkpoint sync, because it is potentially in a better (more complete) state already

**Comment by xrchz** [comment]
> so there's nothing that a healthy, almost-synced BN can gain from using it.

I think one possible gain from switching to checkpoint sync from a fully or almost synced BN is a reduction in disk space usage. For this use case do you still prefer a manual `--purge-db`? It would be nice if lighthouse could detect whether the space reduction will be achieved before purging though.

**Comment by michaelsproul** [comment]
> I think one possible gain from switching to checkpoint sync from a fully or almost synced BN is a reduction in disk space usage.

This is a bit of a hack though – the reason checkpoint sync can save space is that it doesn't store restore points (states) from before the checkpoint. We could achieve even better space savings by implementing a config option to prevent storage of _all_ restore points, and this could be turned on regardless of whether checkpoint sync was used and without requiring a resync of all the blocks.

I'm still hesitant to add any sort of automatic database purge because having to resync all the blocks is a non-trivial amount of work, and could cause a data availability issue if every node deleted its database and had to resync at the same time.

**Comment by paulhauner** [comment]
I'm also keen to keep things simple and explicit regarding database purges. An unexpected purge could be very frustrating, especially when using a node for archival purposes.

I'm going to close this for now. Feel free to reopen, but keep in mind that any automation with database purging needs to be very predictable and clear.
