### ISSUE TITLE
Upgrading Lighthouse for new hardfork

### ISSUE THREAD

**Issue by ethcurious** [sigp/lighthouse#2706]
What's the recommended workflow to upgrade Lighthouse if a hardfork is imminent? For example, do stable clients released near-ish to hardforks have the post-hardfork protocol updates already written in, but dormant until the client detects (based on blocknumber/epoch) the fork has been reached, at which point the client starts using the updated protocols and follows the right fork automatically? If that's how the client works, as long as I'm careful to update it before each fork, I should be ok. If that's NOT how it works, I'm not sure what I should do.

**Comment by michaelsproul** [comment]
You're correct, that's how it works! For example, our [v2.0.0 release](https://github.com/sigp/lighthouse/releases/tag/v2.0.0) contains all the code for the Altair hard fork, and the activation epoch for mainnet. When that epoch (74240) is reached the node will start using the Altair consensus and networking changes. The other clients work similarly.

Lighthouse also includes a rollback feature so that it can switch to the correct chain _even if_ you forget to upgrade before the fork. However it's obviously better if you don't miss the fork in the first place, and the rollback has some caveats, but we hope it helps in emergency situations. More info in the impl PR: https://github.com/sigp/lighthouse/pull/2529
