### ISSUE TITLE
Bootnode warning about invalid ENR

### ISSUE THREAD

**Issue by k1rill-fedoseev** [sigp/lighthouse#2744]
## Description

I am trying to run a boot node for some private testnet.
I see a lot of warnings in the logs like:
```
WARN Session has invalid ENR. Enr socket: Some(<IP>:12000), Node: 0x5df1..d0fd, addr: <IP>:1024
```

## Version

Lighthouse v2.0.1
Beacon node is run in docker container
Bootnode is run natively (it didn't work in docker at all)

## Present Behaviour

Warnings in the logs.

## Expected Behaviour

Node should be able to connect to boot node without issues.

**Comment by AgeManning** [comment]
These warnings are telling you that the node that is trying to connect to you is supplying you with the wrong ENR. 

The node connecting node is saying, hey i'm at IP:12000 but really they are connecting to you on IP:1024. This can happen due to NAT'ing for example. Node's that falsely advertise their ENR's we reject, because if we added their ENR to our routing table, they would not be contactable, and we'd be passing around non-contactable ENR's to those who ask for peers (which is a waste of our resources and also DHT space). 

There are two solutions: 

1. The connecting node should not set their IP/port if they don't know their external contactable port (or if they don't have port forwards). ENR's do not require this field to be set. If this node is behind a NAT and non-contactable, then your bootnode will still respond to their requests, but will not add them to the DHT (because they are non-contactable). 

If the node is actually contactable, and it can connect to 10 (this is a default parameter) other nodes, then it will automatically update its ENR to the correct value based on what the other nodes see. 

2. Set the correct IP:Port that matches the external port forward for the node.

**Comment by AgeManning** [comment]
We do have scripts that help you set up private testnets also. They are here for reference: https://github.com/sigp/lighthouse/tree/stable/scripts/local_testnet

**Comment by AgeManning** [comment]
I'm closing this issue as I think its addressed and is becoming stale.
