### ISSUE TITLE
temporary validator exit

### ISSUE THREAD

**Issue by junaltea** [sigp/lighthouse#2871]
## Description
Is it possible for a temporary exit as validator, just because perhaps of hardware issues?

**Comment by michaelsproul** [comment]
Sorry but a temporary exit is not possible due to how the protocol is defined: exits are permanent.

If you're having hardware issues there are several things you can do:

- Absorb the losses. This sounds bad, but when the chain is finalizing you won't lose too much each day that you're offline. Being offline for `N` days will lose rewards equivalent to being online for `N` days. If you're off for a week, then you'll be back to the same position after coming back online for a week.
- Run a validator client on some old hardware. The validator client is quite lightweight and will run on any old laptop/desktop that you may have lying around. You can point it at an Infura beacon node by using `--beacon-nodes INFURA_URL`, where `INFURA_URL` is the URL that you get from the Infura Eth2 dashboard. There's some more about the `--beacon-nodes` flag [here](https://lighthouse-book.sigmaprime.io/redundancy.html#redundant-beacon-nodes). When setting up the new validator client you should import the slashing protection data from your old validator client if you still have it available. Instructions for doing that are here: https://lighthouse-book.sigmaprime.io/slashing-protection.html#import-and-export

Let us know if you need any more assistance, or come chat to us on [Discord](https://discord.gg/cyAszAh)
