### ISSUE TITLE
Improve redundancy behavior

### ISSUE THREAD

**Issue by poupas** [sigp/lighthouse#2888]
## Description

Hello. I have been testing the "multi-beacon node" feature for redundancy purposes. It works well, provided the failover beacon node is listening on all subnets, as noted in the documentation.

## Version

Lighthouse/v2.0.1-fff01b2

## Present Behaviour

I think the "fail-back" behavior could be slightly improved. Right now, when the primary beacon node comes back online and changes its state to "synced", the validator is very eager to use the primary node again. In my experience, this seems to have resulted in missed attestations. Even tough the node reports its state as synced, the peer count is still quite low, and this could explain the observed behavior.

## Expected Behaviour

Suggestion: as long as the failover beacon node is working correctly, there is no urgent need to change back to the primary beacon node.

The validator could wait until the primary beacon node peer count has stabilized, or some time has passed. Additionally, it could request the primary beacon node to subscribe to the subnets the validator is interested in, before switching back to the primary. This way, the primary node wouldn't need to subscribe to all subnets by default.

I believe this could improve the chances of attestations being seen by the network during fail-back.

**Comment by enforest** [comment]
Agreed. The validator should track peer count of the beacon nodes. Beacon nodes with peer count lower than a threshold should be marked as unusable to decrease the risk of failure in publishing attestations.

**Comment by paulhauner** [comment]
This is great feedback, thank you! I think we could definitely improve here. I'll add a few comments regarding my thoughts:

> Suggestion: as long as the failover beacon node is working correctly, there is no urgent need to change back to the primary beacon node.

This might not be ideal for users who have a paid service (Infura) as their back-up. I imagine they'd want to switch back to their primary node when ready.

> Additionally, it could request the primary beacon node to subscribe to the subnets the validator is interested in, before switching back to the primary. 

This would be helpful indeed. I have considered a setup where subscription requests go to *all* nodes, rather than just active one. It does have a cost of making the backup nodes work harder, though.

> The validator could wait until the primary beacon node peer count has stabilized, or some time has passed.

The simplest solution here I think is "some time has passed". I.e., wait some period after a BN comes online before we switch back to it. Just waiting isn't ideal, but it does save us some complexity regarding judging what's a "good" peer count, especially when the BN might not be Lighthouse. It might be that some nodes have a purposefully low peer count or the network is unstable so there aren't many peers.

Perhaps this logic would be suitable: *"when using an endpoint, if a higher-priority endpoint comes online, wait 2 epochs before connecting to it"*.

**Comment by poupas** [comment]
> This would be helpful indeed. I have considered a setup where subscription requests go to _all_ nodes, rather than just active one. It does have a cost of making the backup nodes work harder, though.
> 
I like this idea a lot. Right now, my backup node has to subscribe to all subnets to be useful during a failover. I only have 1 validator, but my backup beacon node is working "furiously", listening and forwarding attestations on all subnets so that one day, it may be called upon. If the validator could ask the backup BC to only subscribe to the subnets it's interested on, I think that might help the environment :)

**Comment by paulhauner** [comment]
I've opened #3001 and #3002 to track the two enhancements we discussed.

I'm going to close this and we can track each change individually. Thanks for the discussion, feel free to reopen if you like :)
