### ISSUE TITLE
Beacon node excessive cpu usage

### ISSUE THREAD

**Issue by pnowosie** [sigp/lighthouse#2904]
## Description

I'm observing an excessive usage of the CPU (all cores, 100% constantly). It is permanent besides the node is fully synced.

## Version

I'm using [2.0.1 version](https://github.com/sigp/lighthouse/releases/tag/v2.0.1) with binaries available in GH release (lighthouse-v2.0.1-aarch64-unknown-linux-gnu.tar.gz) on custom 64-bit linux distro (build via [yocto](https://www.yoctoproject.org/))
but same behavioiur was observed on 64-bit ubuntu 20.04.
Hardware is RaspberryPi 4

I'm syncing mainnet beacon chain. Here is a command
```bash
lighthouse bn --http \
  --datadir "/DATA/lighthouse" \
  --http-address "0.0.0.0" \
  --http-port 5052
```

## Present Behaviour

CPU usage constantly on 100% on all (4) available cores which starves other processes.
I've tested with setting `CPU Affinity` and limitting the process to just one core - it's able to sync - but it's still a bit too much and unexpected behaviour as the node is synced.

## Expected Behaviour

CPU usage increment is expected when the node is syncing new data. Then it should decrease.

## Steps to resolve

-

**Comment by paulhauner** [comment]
Thanks for the report @pnowosie. Would you mind sharing the details of your CPU please? For example, using `less /proc/cpuinfo` I can see that my CPU is a `Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz`.

**Comment by pnowosie** [comment]
```bash
less /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : d03114
Serial          : 10000000de8e140b
Model           : Raspberry Pi 4 Model B Rev 1.4
```

**Comment by pnowosie** [comment]
Hey guys I'll appreciate any suggestions what I can do?
I tried to set also `CPU Quota=50%`. It resulted to significant lagging (~hundreds of slots behind infura).
Thanks in advance to any help!

**Comment by michaelsproul** [comment]
@pnowosie Running on a Raspi is "hard mode" for staking. The Rocket Pool docs contain some good tips: https://docs.rocketpool.net/guides/node/local/prepare-pi.html

The TL;DR is:

* Use an 8GB Raspi
* Don't try to run Geth on the same Pi that you run Lighthouse
* Make sure you have a fast SSD connected via USB 3
* Overclock if you're comfortable doing so

**Comment by jmcruz1983** [comment]
Hi guys,
I am also suffering from cpu spikes when running beacon nodes in k8s
where beacon usually is using 2-3 cpus and spiking to 6 cpus is causing  `SIGTERM`.
```
Feb 05 22:21:39.948 INFO Shutting down.. reason: Success("Received SIGTERM")
```
Beacon node gets killed as it is depleting cpu available in the k8s node.

Also worth mentioning this happening after upgrading to `v2.1.1`.

I would appreciate any suggestion to mitigate this issue.
Thanks

**Comment by michaelsproul** [comment]
> Also worth mentioning this happening after upgrading to v2.1.1.

Is this only happening after upgrading to v2.1.x?

> I am also suffering from cpu spikes when running beacon nodes in k8s
where beacon usually is using 2-3 cpus and spiking to 6 cpus is causing SIGTERM.

Lighthouse needs to spike CPU usage in order to keep latency low. For the beacon chain latency is everything: we want to be able to process blocks quickly and attest on time.

I've never used Kubernetes before, but based on [this article](https://sysdig.com/blog/troubleshoot-kubernetes-oom/) it seems like K8s won't kill a task for using too much CPU:

> _A container using more memory than the limit will most likely die, but using CPU can never be the reason of Kubernetes killing a container. CPU management is delegated to the system scheduler, and it uses two different mechanisms for the requests and the limits enforcement._

It might be worth checking your K8s memory limits to see if Lighthouse is exceeding them. If the OOM killer is in play then `dmesg` should show the kill in its log.

> I would appreciate any suggestion to mitigate this issue.

In addition to checking the memory limit (and raising it if necessary) I think you could also try:

* Setting the number of virtual CPUs available to Lighthouse (I _think_ K8s [`-cpus N`](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#specify-a-cpu-request-and-a-cpu-limit) flag might do this).
* Setting the `RAYON_NUM_THREADS` environment variable.
* If memory usage is an issue, setting the `MALLOC_ARENA_MAX` environment variable to 1 or 2 (prevents heap fragmentation at the cost of CPU usage).

All of these changes come with trade-offs however, and Lighthouse is unlikely to perform as well when its CPU and memory are tightly constrained.

I've also opened https://github.com/sigp/lighthouse/issues/3000 to track some changes we could make in Lighthouse to make configuring the number of threads used more straightforward.

**Comment by jmcruz1983** [comment]
Thanks @michaelsproul for reply

> Is this only happening after upgrading to v2.1.x?

Yes I tested with `v2.1.1`, `v2.1.2` & `v2.1.2-modern` and all of them were spiking and getting killed.

> I've never used Kubernetes before, but based on [this article](https://sysdig.com/blog/troubleshoot-kubernetes-oom/) it seems like K8s won't kill a task for using too much CPU:

Yes I am aware that k8s doesn't kill you when running above cpu request limit. And I don't have a hard limit configured, so basically would use all the cpu available.
But the case here is that beacons are getting killed because they are using all the cpu available in the node and node kills them to avoid cpu depletion. 

> In addition to checking the memory limit (and raising it if necessary) I think you could also try:

Currently each beacon is running with 3 cpus allocated as soft limit (request limit) and no hard limit so it can use all the cpu available in the node (each node has 4 cpus). 
Just worth to mention that 3 cpus were more than enough for `v2.0.1` and they never got killed.

Thanks

**Comment by michaelsproul** [comment]
> node kills them to avoid memory depletion.

How much memory is each beacon node using when it gets killed? The SigP mainnet nodes use 1.2 GB - 2.3 GB each.

> Just worth to mention that 3 cpus were more than enough for v2.0.1 and they never got killed.

The main change since v2.0.1 that could cause increased memory usage is https://github.com/sigp/lighthouse/pull/2832, which opts to keep more beacon states available in memory so that block processing can be faster. If memory usage is just a bit higher it could be that change, but if it's a lot higher it could be fragmentation. We have a [Malloc Info](https://gist.github.com/michaelsproul/abe1ece32c42d611e6a862915c7a33a7) Grafana dashboard that will show the breakdown of memory usage: look for high free block memory (indicates fragmentation) or high mmap usage correlated with the snapshot cache size (indicates #2832).

Could you also please try the `MALLOC_ARENA_MAX=1` env var and let me know if that helps?

**Comment by jmcruz1983** [comment]
My bad @michaelsproul 
I corrected my comment above.

My issue is entirely related to cpu consumption.
Beacons when spiking are using max cpu available in the node and get killed.
Each node where beacons run have 4 cpus and we allocate already 3 cpus to each beacon.

I don't have any problem with memory as we grant plenty of memory to each beacon. 

Here I am attaching an screenshot from the resource dashboard,
we after upgrading to `v2.1.x` cpu was spiking:
<img width="1589" alt="cpu" src="https://user-images.githubusercontent.com/15966694/152782787-27b09607-b621-4d02-a133-b3957b92ce44.png">
After downgrading to v2.0.1 cpu was back to range.

Thanks

**Comment by michaelsproul** [comment]
Closing because this is stale, and the scope is overly broad. If we find a specific bug that induces increased CPU usage we can open a new issue
