### ISSUE TITLE
High inclusion lag and missed attestations when using fallback beacon node

### ISSUE THREAD

**Issue by poupas** [sigp/lighthouse#2926]
## Description

Hi all. I think I've ran into a potential issue with the beacon node redundancy feature. Even if the primary node is unavailable, the validator client still tries to contact it **on every attestation**. This will result in attestation delays and missed attestations.

## Version

Lighthouse/v2.0.1-fff01b2

## Present Behaviour

I'm using the following setup for my tests:

  * primary beacon node (`192.168.0.1`)
  * secondary beacon node (`192.168.0.2`)
  * lighthouse validator client is configured with `--beacon-nodes http://192.168.0.1:5052,http://192.168.0.2:5052`

If the primary beacon node becomes unresponsive, and is correctly detected as being offline, the validator still tries to contact it every time during its attestation duties. This is causing significant delay (around 8 seconds, as it can be seen in the following logs), resulting in high inclusion lag and missed attestations.

This behavior is simple to reproduce, just make sure that the primary node does not reply to any traffic, since we need to trigger a timeout.

**OK scenario (primary beacon node is up):**
```
Jan DD HH:MM:03.001 TRCE Spawned attestation tasks               service: attestation
Jan DD HH:MM:03.055 TRCE Blocking task completed                 task: local_keystore_signer
Jan DD HH:MM:03.106 INFO Successfully published attestations     type: unaggregated, slot: [removed], committee_index: [removed], head_block: [removed], count: 1, service: attestation
```

**Failing scenario (primary beacon node is down, secondary is up):**
```
Jan DD HH:MM:15.001 TRCE Spawned attestation tasks               service: attestation

--- ~ 8 second gap ---

Jan DD HH:MM:23.005 WARN Offline beacon node                     endpoint: http://192.168.0.1:5052/, error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(192.168.0.1)), port: Some(5052),
 path: "/eth/v1/node/version", query: None, fragment: None }, source: TimedOut })
Jan DD HH:MM:23.005 INFO Connected to beacon node(s)             synced: 1, available: 1, total: 2, service: notifier
Jan DD HH:MM:23.026 TRCE Blocking task completed                 task: local_keystore_signer
Jan DD HH:MM:23.044 INFO Successfully published attestations     type: unaggregated, slot: [removed], committee_index: [removed], head_block: [removed], count: 1, service: attestation
```

## Expected Behaviour

The validator client should use the "healthy" beacon nodes first.

**Comment by realbigsean** [comment]
Thanks a lot for looking into this and bringing it up!  

> The validator client should use the "healthy" beacon nodes first.

The fallback functionality is intended to give users the ability to set an order of precedence for which nodes should be used. A very common setup is to have a local beacon node node running and using Infura as a backup. And the hope for this type of setup is to only use Infura when necessary, and recover to the beacon node as soon as it's available.

We could instead try to address this by reducing this timeout to something that would allow a fallback requests to still be made.
It's possible this could induce some missed attestations when requests that would have completed just after the timeout are cancelled and the backup doesn't have time to complete the request. So maybe we can reduce this timeout only when a node was last seen as unhealthy.

**Comment by paulhauner** [comment]
Reducing the timeout can be tricky for hard-working endpoints like `GET validator/blocks`. Block production can take a while and we don't want to abandon it with a short timeout.

Another solution might be to add a new `Timedout` variant to [`CandidateError`](https://github.com/sigp/lighthouse/blob/0177b9286edfdeb2782f74fc7fb1392b6459bfaa/validator_client/src/beacon_node_fallback.rs#L117) so we will always skip nodes that recently timed-out during the [first pass in the `first_success` function](https://github.com/sigp/lighthouse/blob/0177b9286edfdeb2782f74fc7fb1392b6459bfaa/validator_client/src/beacon_node_fallback.rs#L432-L449). Nodes that timeout will then need to be recovered via the [`update_unready_candidates`](https://github.com/sigp/lighthouse/blob/0177b9286edfdeb2782f74fc7fb1392b6459bfaa/validator_client/src/beacon_node_fallback.rs#L357-L385) routine.

**Comment by holiman** [comment]
How about: 
- If node `x` is found to be "down" (wrongly configured, actually down, responding with error, whatever), then remove it from the list of nodes to query. 
- Start a `poller` which checks health every 5 seconds. 
- Once the `poller` finds that it's "up" again (according to some criteria), it get put back in the list according to the desired priority. 

Maybe that's the same as what you mean, but in other words, @paulhauner (?)

**Comment by paulhauner** [comment]
> Maybe that's the same as what you mean, but in other words, @paulhauner (?)

Indeed, that's a clearer way to express what I was alluding to.

I looked into this a bit further and we do already implement the desired behaviour *(excluding a bug I'll describe shortly)*. When a node returns *any* error we call [`CandidateBeaconNode::set_offline`](https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/validator_client/src/beacon_node_fallback.rs#L424) which sets it's `status` to `CandidateError::Offline`. That node will then be ignored until the routine [`fallback_updater_service`](https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/validator_client/src/beacon_node_fallback.rs#L44) manages to reconnect to it.

However, I believe there was an issue in the [`CanidateBeaconNode::refesh_status`](https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/validator_client/src/beacon_node_fallback.rs#L157-L178) method, which is used by the updater service to see if the node has come good again. It was holding a [write lock on the `status` field](https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/validator_client/src/beacon_node_fallback.rs#L165) whilst it polled the node status. This means a long timeout would hog the write lock and starve other processes.

When a VC is trying to access a beacon node for whatever purpose (getting duties, posting blocks, etc), it performs [three passes](https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/validator_client/src/beacon_node_fallback.rs#L432-L482) through the lists of nodes, trying to run some generic `function` (closure/lambda) on each node:

- 1st pass: only try running `function` on all nodes which are both synced and online.
- 2nd pass: try running `function` on all nodes that are online, but not necessarily synced.
- 3rd pass: for each offline node, try refreshing its status and then running `function` on it.

So, it turns out that if the `CanidateBeaconNode::refesh_status` function from the routine update service is hogging the write-lock, the 1st pass gets blocked whilst trying to read the status of the first node. So, nodes that should be left until the 3rd pass are blocking the process of the 1st and 2nd passes, hence the behaviour described by @poupas.
