### ISSUE TITLE
Implement protolambda's `simple_back_prop` lmd ghost

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#296]
## Description

This is a more involved first issue. Some learning may be required. 

@protolambda has created a number of optimised versions of LMD ghost in go. This issue is for porting one of these implementations into rust and lighthouse. 

The repository containing the optimised go algorithms is [here](https://github.com/protolambda/lmd-ghost). 

It would be useful to add the `simple_back_prop` ([here](https://github.com/protolambda/lmd-ghost/blob/master/eth2/fork_choice/choices/simple_back_prop/simple_back_prop.go)) to the current list of fork choices we have implemented. 

For more information about LMD Ghost see references within #247.

Have a look at the current implementation of how fork choices are implemented: https://github.com/sigp/lighthouse/blob/master/eth2/fork_choice/src/lib.rs (and modules within). 

The `BitwiseLMDGhost` struct implement's Vitalik's optimised version which is also in @protolambda's repository, so you can compare implementations. 

The new implementation should implement  the `ForkChoice` trait, which specifies what to do when an attestation or block is added. See the other implementations for examples. 

For further details and more explanations don't hesitate to ask @AgeManning on the gitter channel. :)

**Comment by 192-sean** [comment]
I'll give it a go

**Comment by b-m-f** [comment]
Hi @AgeManning,
Is this up for grabs again? Would like to start helping abit whenever I have some time.

**Comment by protolambda** [comment]
Do take a look at one of the later additions, an array based one: https://github.com/protolambda/lmd-ghost#array-based-stateful-dag-proto_array It turned out to be the fastest in my latest simulation, which I posted a few weeks ago in the sharding gitter, here: https://gist.github.com/protolambda/23cc276b8562c811b3e36b21676a8ef6 (disclaimer: note that different algos are favored by different simulation params, and it's hard to do simulation well).

**Comment by AgeManning** [comment]
Thanks @protolambda!
@b-m-f - Hey. Yep this is on the back-burner at the moment and we would love some help building it whenever you have the time. 
I'm available whenever you need to help explain anything / where to start, which code to look at etc. 
Ping me either here or on gitter if/when you need help :).

**Comment by b-m-f** [comment]
@AgeManning alright , thanks :) I am quite busy right now so I cant yet start. If anyone reads this and has time and motivation, feel free to grab it!

**Comment by paulhauner** [comment]
Our wide selection of fork choice algos was removed in #398 and replaced with the "reduced tree" fork choice.

We did this because maintaining several fork choice implementations was burdensome.

Perhaps in the future we can start a new effort to benchmark fork choice algorithms, but I'll close this issue until we decide to do that.
