### ISSUE TITLE
Add HTTP Endpoint to Capture `BeaconState` and `BeaconBlock` for Head and Historical Slots

### ISSUE THREAD

**Issue by abdulrabbani00** [sigp/lighthouse#3143]
- [Overview](#overview)
  * [Use Case](#use-case)
  * [Running the Nodes](#running-the-nodes)
- [Endpoints](#endpoints)
  * [`/proposed-latest-block`](#--proposed-latest-block-)
    + [Result We Want](#result-we-want)
    + [Potential Implementation](#potential-implementation)
  * [`/proposed-latest-state`](#--proposed-latest-state-)
    + [Result We Want](#result-we-want-1)
    + [Potential Implementation](#potential-implementation-1)
  * [`/finalized-beacon-slot/range`](#--finalized-beacon-slot-range-)
    + [Result We Want](#result-we-want-2)
    + [Potential Implementation](#potential-implementation-2)
  * [`/finalized-beacon-slot/range`](#--finalized-beacon-slot-range--1)
    + [Result We Want](#result-we-want-3)
    + [Potential Implementation](#potential-implementation-3)
  * [`/forked-beacon-block`](#--forked-beacon-block-)
    + [Result We Want](#result-we-want-4)
    + [Potential Implementation](#potential-implementation-4)
  * [`/missed-beacon-slot` - Nice to have](#--missed-beacon-slot----nice-to-have)
    + [Result We Want](#result-we-want-5)
    + [Potential Implementation](#potential-implementation-5)
  * [`/finalized-beacon-slot/latest` - Nice to have](#--finalized-beacon-slot-latest----nice-to-have)
    + [Result We Want](#result-we-want-6)
- [Questions](#questions)

<small><i><a href='http://ecotrust-canada.github.io/markdown-toc/'>Table of contents generated with markdown-toc</a></i></small>

# Overview

I would like to add a few HTTP endpoints for my team's use case. I am more than happy and willing to write all the code needed to implement these feature. I only ask for guidance and help.

## Use Case

My teams use case is as follows:
1. We want to capture every `BeaconBlock` and `BeaconState` for every slot from `genesis` to `head` in a Postgres DB.
2. We want to capture `missed` slots (slots that were skipped).
3. We would like to capture all processed `BeaconBlocks`, even the ones that are `forked` when watching the head of chain.
  a. We would like to label the blocks that are `forked` as `forked` in the Postgres DB. 

## Running the Nodes

At the first go, we plan on having two `lighthouse` nodes running.
1. Sole purpose is to keep up with the head of the chain. This node will update the database with the latest information from the head.
2. An archival node that has every block since genesis available. This node will be used to fill the database for historical events, as well as missed events.

# Endpoints

The following capture all the endpoints that we are hoping to expose on the beacon node, as well as potential implementations for them. The actual names and "endpoints" themselves can be easily changed and modified. This example is simply using dummy placeholders.

### Result We Want
Expose an HTTP event stream endpoint that will stream the proposed head `BeaconBlock(s)` for the latest slot. Keeping in mind that we can have multiple proposed head `BeaconBlocks` for a given slot.

If someone is listening to this endpoint they might see:
```
{
  "Slot": 10,
  "BeaconBlock": dict_a
}
...
{
  "Slot": 10,
  "BeaconBlock": dict_b
}
...
{
  "Slot": 11,
  "BeaconBlock": dict_c
}
```

### Potential Implementation

Hypothetically speaking, whenever a new block is written to the Hot DB, we should be able to construct an object utilizing the `BeaconBlock` and send it through the endpoint.

### Result We Want
Very similar to the `/proposed-latest-block` endpoint. 

Expose an HTTP event stream endpoint that will stream the proposed head `BeaconStates` for the latest slot. Keeping in mind that we can have multiple proposed head `BeaconStates` for a given slot.

If someone is listening to this endpoint they might see:
```
{
  "Slot": 10,
  "BeaconState": dict_a
}
...
{
  "Slot": 10,
  "BeaconState": dict_b
}
...
{
  "Slot": 11,
  "BeaconState": dict_c
}
```

### Potential Implementation

From my understanding, the lighthouse juggles all potential `BeaconStates` at its head. We should be able to simply send them through the HTTP endpoint.

### Result We Want
Expose an HTTP endpoint to return a list of `BeaconBlock` objects for each slot for a specified block range.

If someone queries this endpoint with the following parameters, they might see:

```
Parameters: {start:10, end: 12}

[
  {
     "Slot: 10,
     "BeaconBody": dict_a
  },
  {
     "Slot: 11,
     "BeaconBody": None --> Because this was a skipped slot.
  },
  {
     "Slot: 12,
     "BeaconBody": dict_c
  }
]

```
### Potential Implementation
Hypothetically speaking, this object "should" be within the Hot DB (as long as the node has constructed it).  We should be able to query the DB to return the specified object.

### Result We Want

Similar to  `/finalized-beacon-slot/range`, but the implementation will vary drastically I believe.

Expose an HTTP endpoint to return a list of `BeaconStates` objects for each slot for a specified block range. If someone queries this endpoint with the following parameters, they might see:

```
Parameters: {start:10, end: 12}

[
  {
     "Slot: 10,
     "BeaconStates": dict_a
  },
  {
     "Slot: 11,
     "BeaconStates": dict_a --> Because this slot has no BeaconBlock.
  },
  {
     "Slot: 12,
     "BeaconStates": dict_c
  }
]

```

### Potential Implementation

The implementation for this is a bit of a head-scratcher to me. I would imagine that the cold DB might have some of the states available, but from my understanding, not all of the states (the frequency of states available in the cold DB can be configured through the parameter called `--slots-per-restore-point` correct?)

Perhaps this implementation would be two folds:
1. Check to see if any of the slots specified are in the cold DB, if so add them to the return array.
4. If not, then construct each `BeaconState` that is missing and add it to the return array.
5. Return the final return array.

### Result We Want
Expose an HTTP event stream endpoint that will stream any `forked` block. Consider the following case.

1. Latest slot is `10`.
2. Latest proposed block is `a`, this gets streamed via the `/proposed-latest-block` endpoint.
3. Latest proposed block is `b`, this gets streamed via the `/proposed-latest-block` endpoint.
6. Following the fork rule, the chain decides that block `a` is going to be chosen for slot `10`. This means that block `b` is the `forked` block.

In this scenario, anyone listening to `/forked-beacon-block`, should see the following:
```
{
  "Slot": 10,
  "status": "forked",
  "BeaconBody": b
}
```

### Potential Implementation

I am not entirely sure of the inner workings of Hot DB. But if hot DB keeps track of `forked` blocks, then we might be able to piggyback off of that functionality. When hot DB recognizes a block as `forked`, a function streams that block to the `/forked-beacon-block` endpoint.

### Result We Want
Expose an HTTP event stream endpoint that will stream any `missed` slots (skipped slots).

In this scenario, anyone listening to `/missed-beacon-slot`, should see the following:
```
{
  "Slot": 11,
  "status": "missed",
}
```

### Potential Implementation

I understand that `missed` slots are not referenced at all in the hot or cold DB. Therefore I am not sure how this might be implemented, but it would be great if `lighthouse` could see that it jumped from slot `x` to `x+2`, and skipped `x+1`. In this scenario it would then send slot `x+1` to the `/missed-beacon-slot` endpoint.

## `/finalized-beacon-slot/latest` - Nice to have

This implementation is not needed if we have `/forked-beacon-block`.

### Result We Want

 Expose an HTTP event stream endpoint that will stream the single, finalized head `BeaconBlock` for the latest finalized slot. This way, if we have 2 proposed blocks for a single slot, we can determine which block the chain chose for the specified slot.

In this scenario, anyone listening to `/finalized-beacon-slot/latest`, should see the following:
```
{
  "Slot": 10,
  "BlockNumber": a,
  "status": "finalized",
}
....
{
  "Slot": 11,
  "BlockNumber": b,
  "status": "finalized",
}
```

### Potential Implementation
I am not sure if the Hot DB marks blocks as `finalized`. But if it does, then we can stream the `finalized` block to this endpoint after it is finalized in Hot DB.

# Questions

There are a few questions that we have:
1. What is the "best" way to run the "archival" node. I am considering the best configuration flags to provide to this node, to contain all blocks from genesis to head, and be able to construct the `BeaconState` for each slot. I understand that this is a heavy lift. I would love to understand if you guys have some insights here regarding the flags to use as well as hardware specs for achieving this.
2. What type of Merkle tree is the `BeaconState` a part of?

**Comment by realbigsean** [comment]
An important thing to note is  we *do* prune non-canonical blocks from a finalized portion of the chain. I wasn't sure about this in answering your questions yesterday but I verified. So I don't know that some of these will be possible with lighthouse (any endpoint that expects to produce multiple blocks or states at a single slot in a portion of the chain that has finalized). If you require these, then another client might be an better option if they don't prune these (not sure which client that might be), or maybe you could get this data from a service like beaconcha.in. 

Otherwise, it sounds like lot of the other information here can be derived from existing standard API endpoints (which all clients implement), the main one being the existing events stream:  https://ethereum.github.io/beacon-APIs/#/Events/eventstream

- `proposed-latest-block` + `proposed-latest-state` -> these could map to the `head` topic (any block set as head, but also includes the state root associated with it) or the `block` topic (any valid block seen).  
  -  If you are looking for any states resulting from any block seen that are *not* set as head, we don't expose that but we do store them in our `snapshot_cache` so it would be possible to expose them 
  - The `head` topic only includes block roots and state roots, but you can use both of these to query the standard API endpoints to get the [full state](https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2) and [block](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockV2).  
  - If this route isn't feasible, I think it'd be reasonable for us to add a non-standard events endpoint. Something like `lighthouse_events` that is structured like the `events` endpoint where we stream full blocks and beacon states.

- `finalized-beacon-slot` -> `finalized_checkpoint` events topic
- `forked-beacon-block` -> `chaing_reorg` events topic
- `range` endpoints -> Because we prune orphaned blocks, these wouldn't be able to return multiple objects per slot, so I'm not sure there's a reason for new endpoints for these when you could query the standard [full state](https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2) and [block](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockV2) endpoints one slot at a time.
- An additional endpoint that you might find interesting: https://ethereum.github.io/beacon-APIs/#/Debug/getDebugChainHeads

### Answers to Questions

1. By default any node synced from genesis (not checkpoint synced) will be an `archival` node in the sense that it will have all blocks and all states. But, again, we *do* prune non-canonical blocks from a finalized portion of the chain. 
2. All consensus types are SSZ types who's merklization is spec'd out here: https://github.com/ethereum/consensus-specs/blob/dev/ssz/merkle-proofs.md

**Comment by abdulrabbani00** [comment]
@realbigsean - This was super helpful. A few notes:

* We are only interested in the `forked` blocks for new blocks (as we are syncing from the head). We don't need this information for historical blocks.
* You're absolutely correct, we don't need the `range` endpoints if we can just query each `block` and `state` from genesis by the slot number.
* Using the standard API to get the full state and block might be feasible hypothetically. But from a performance perspective, it might be too slow. If possible, I think implementing the `lighthouse_events` with full blocks would be a great help.
* What are your thoughts on the `missed-beacon-slot` endpoint? This would be useful in telling is which slots were skipped in real-time. 

I'm going to have to take a closer look at some of the events but ultimately, this has been incredibly insightful. I think we might be able to trim down a lot of the expected work.

**Comment by michaelsproul** [comment]
I'll add one thing about the range endpoints: fetching a range of states could be a lot faster than fetching states individually, because we reconstruct states by replaying blocks. For example if the DB has a full state at slot 2048, and the user wants states 2048-4096 then the DB will replay blocks `[2049], [2049, 2050], [2049, 2050, 2051], [2049, 2050, 2051, 2052], etc`. By replaying blocks one at a time and streaming the states we can avoid replaying some blocks multiple times, i.e. `O(n)` replays rather than `O(n^2)`.

We have quite succinct code for doing this in the [`BlockReplayer`](https://github.com/sigp/lighthouse/blob/stable/consensus/state_processing/src/block_replayer.rs), which is used to back the existing `/lighthouse/analysis/block_rewards` endpoint: https://lighthouse-book.sigmaprime.io/api-lighthouse.html#lighthouseanalysisblock_rewards

**Comment by abdulrabbani00** [comment]
# GitHub Issue: Lighthouse

# Overview

I would like to add a few HTTP endpoints for my team's use case. I am more than happy and willing to write all the code needed to implement these features. I only ask for guidance and help.

_This is the second iteration of the proposal._

## Use Case

My teams use case is as follows:

1.  We want to capture every `BeaconBlock` and `BeaconState` for every slot from `genesis` to `head` in a Postgres DB.
2.  We want to capture `missed` slots (slots that were skipped).
3.  We would like to capture all processed `BeaconBlocks`, even the ones that are `forked` when watching the head of the chain.
    1.  We would like to label the blocks that are `forked` as `forked` in the Postgres DB.

## Running the Nodes

On the first go, we plan on having two `lighthouse` nodes running.

1.  The sole purpose is to keep up with the head of the chain. This node will update the database with the latest information from the head.
2.  An archival node that has every block since genesis available. This node will be used to fill the database for historical events, as well as missed events.

# Endpoints

The following capture all the endpoints that we are hoping to expose on the beacon node, as well as potential implementations for them. The actual names and "endpoints" themselves can be easily changed and modified. This example is simply using dummy placeholders.

## [`/lighthouse-events?topic=head`](https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml#L41) - Update

### Result We Want

Update the endpoint to accept a parameter, that will return the entire `block` and `state` object in either JSON or SSZ encoded format.

Keep in mind that we can have multiple proposed head `BeaconBlocks` for a given slot.

If someone is listening to this endpoint they might see:

```
{"slot":"10", "block": "SSZ_OBJECT_A", "state":"SSZ_OBJECT_X", "epoch_transition":false, "previous_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e91", "current_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e91", "execution_optimistic": false}
...
{"slot":"10", "block": "SSZ_OBJECT_B", "state":"SSZ_OBJECT_Y", "epoch_transition":false, "previous_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e92", "current_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e92", "execution_optimistic": false}
...
{"slot":"11", "block": "SSZ_OBJECT_C", "state":"SSZ_OBJECT_Z", "epoch_transition":false, "previous_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e93", "current_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e93", "execution_optimistic": false}


```

### Potential Implementation

Update the features and functionalities to the current head endpoint to capture the entire SSZ encoded objects and return them if the necessary parameter is specified.

## `/eth/v1/events?topics=intermediary_slots&start_slot=x&end_slot=y`

### Result We Want

Expose an HTTP event stream endpoint that will stream the historical `BeaconState` from the start to the end slots provided.

```
Parameters: {start:10, end: 12}

[
  {
     "Slot: 10,
     "BeaconStates": dict_a
  },
  {
     "Slot: 11,
     "BeaconStates": dict_a --> Because this slot has no BeaconBlock.
  },
  {
     "Slot: 12,
     "BeaconStates": dict_c
  }
]


```

### Potential Implementaion

Utilize the code for doing this in the [`BlockReplayer`](https://github.com/sigp/lighthouse/blob/stable/consensus/state_processing/src/block_replayer.rs), which is used to back the existing [`/lighthouse/analysis/block_rewards`](https://lighthouse-book.sigmaprime.io/api-lighthouse.html#lighthouseanalysisblock_rewards) endpoint.

**Comment by abdulrabbani00** [comment]
@michaelsproul and @realbigsean - Thank you both for your wonderful insight. I have compiled a second iteration of the proposal. I think this is far shorter and simpler to implement. Let me know your thoughts and if there's anything else to change (if the changes are minor I will simply update the proposal above instead of creating a new proposal).

**Comment by realbigsean** [comment]
@abdulrabbani00 Nice! I think the simplified spec with the additional event topics holding debug information, and the state range endpoint all seem like reasonable additions to lighthouse. 

> I'll add one thing about the range endpoints...

@michaelsproul  This is sweet! I also noticed we have a `block_rewards` events topic gated behind a `lighthouse` feature -- that might be a good way to add full beacon block and beacon state events too. Then there'd be no need for a separate `lighthouse_events` endpoint.

> What are your thoughts on the missed-beacon-slot endpoint? This would be useful in telling is which slots were skipped in real-time.

It's tough to tell in real time whether the current slot is missed because you can't know if you just haven't seen the block yet. If you'd like this type of information, the timing in Eth2 is universal so slot times can be calculated outside of lighthouse pretty easily, so you can just mark a slot as likely missed if it's its been 8 seconds (or whatever threshold you choose) since the start of the slot and you haven't received a head event.

> When block a is replaced by block b as the head for slot 10. Is it safe to assume that block a can be labeled as forked?

- Yes
> When block a is replaced by block b as the head for slot 10. Will there be an event on the chain_reorg topic indicating the reorg?

- Yes
> `lighthouse bn --http --metrics --private --network prater --reconstruct-historic-states --slots-per-restore-point 32`

- `--reconstruct-historic-states` is only necessary if you are checkpoint syncing 
> `--slots-per-restore-point`  questions
- I think @michaelsproul will have a better idea about this than me

**Comment by abdulrabbani00** [comment]
@realbigsean - Thanks for the insight. I think there might be a way to simplify the spec even more and remove 2/3 endpoints.

Scenario:
1. I query `events?topic=head`, and I get the `block` and `state` in ssz encoded format.
2. I query a new endpoint: `/lighthouse-events?topic=proposed-latest-block`. This endpoint returns a json object of the `BeaconBlock`.
3. I query a new endpoint: `/lighthouse-events?topic=proposed-latest-state`. This endpoint returns a json object of the `BeaconState`.

The question I have is this:
1. If I query `events?topic=head` and get `block` and `state` ssz encoded. Can I simply decode these objects and get a JSON representation of them?
2. Is it faster to get the smaller return object from `head` and decode `block-->BeaconBlock` and `state-->BeaconState`? Or is it faster to query the significantly larger `BeaconState` and `BeaconBody`?

The thought is, if I can listen to `head` and decode the `block` and `state` to get the `BeaconState` and `BeaconBlock` in a relatively performant manner, then it makes sense to simply do that, instead of receiving a large JSON object. Thoughts?

**Comment by abdulrabbani00** [comment]
> I'll add one thing about the range endpoints: fetching a range of states could be a lot faster than fetching states individually, because we reconstruct states by replaying blocks. For example if the DB has a full state at slot 2048, and the user wants states 2048-4096 then the DB will replay blocks `[2049], [2049, 2050], [2049, 2050, 2051], [2049, 2050, 2051, 2052], etc`. By replaying blocks one at a time and streaming the states we can avoid replaying some blocks multiple times, i.e. `O(n)` replays rather than `O(n^2)`.
> 
> We have quite succinct code for doing this in the [`BlockReplayer`](https://github.com/sigp/lighthouse/blob/stable/consensus/state_processing/src/block_replayer.rs), which is used to back the existing `/lighthouse/analysis/block_rewards` endpoint: https://lighthouse-book.sigmaprime.io/api-lighthouse.html#lighthouseanalysisblock_rewards

Another thought is, what if, instead of implementing a new endpoint that takes a `start` and `end` slot, we implement a cache? 

Scenario:
* I query: `​/eth​/v2​/debug​/beacon​/states​/10`
  * Lighthouse runs block `1-10` on top of the state at block `1`.
  * Lighthouse stores the state at slot `10` in a `debug_state_cache`.
  * I get a JSON object.
* I query: `​/eth​/v2​/debug​/beacon​/states​/11`
  * Lighthouse checks a local cache, to see if there is a `state` at `debug_state_cache`. If there is, build on top of it, otherwise, run block `1-11` on top of state at slot `1`.

Hopefully, that makes sense. In this scenario, we would not need to add any new endpoints, we only need to implement a cache to make the historical state querying performant.

**Comment by michaelsproul** [comment]
I prefer the range approach to a cache for now, because cache logic similar to what you mention has already been implemented, but it's lurking in my `tree-states` branch (https://github.com/michaelsproul/lighthouse/tree/tree-states)  and won't be part of Lighthouse `unstable` for a while. The `tree-states` branch changes the in-memory representation of states from flat bytes to copy-on-write trees, which is what makes the state cache viable (otherwise states are like 50MB each in memory and you can't cache very many). I'm not opposed to adding an API-specific cache in the meantime though if that's the route you'd prefer to take.

> If I query events?topic=head and get block and state ssz encoded. Can I simply decode these objects and get a JSON representation of them?

_If_ we add a head topic that emits the full `BeaconState` and `SignedBeaconBlock`, then yeah you can convert from SSZ to JSON. It's a matter of doing an SSZ decode, and then serializing with `serde_json`.

> For our use case, will --slots-per-restore-point 32 make a difference, or if we implement /lighthouse/v2/debug/beacon?states?start_slot=2048?end_slot=4096, do you think it would be just as performant to utilize --slots-per-restore-point 2048.

Yeah I think you'll be OK with a high SPRP if your design only requires the LH database to be accessed occasionally. If you're storing all the beacon states outside the LH DB though, then that's going to use more space than LH's DB and you may want to consider using SPRP=32 and accessing states from LH more frequently.

I heard from Sean you were also considering state diffs, and we actually have something along those lines already implemented too, but on the `tree-states` branch: https://github.com/michaelsproul/lighthouse/blob/9ab7c24e5a6172a0d134ed9f4df5112c39865343/consensus/types/src/beacon_state/diff.rs#L29-L89. Again, it'll be a while before that lands. The diffs end up being 6-9MB per state (relative to the state at the previous epoch).

**Comment by abdulrabbani00** [comment]
@michaelsproul 

> _If_ we add a head topic that emits the full `BeaconState` and `SignedBeaconBlock`, then yeah you can convert from SSZ to JSON. It's a matter of doing an SSZ decode, and then serializing with `serde_json`.

* Does the current `head` topic not emit the full `BeaconState` and `SignedBeaconBlock` in an SSZ encoded format? 
* Also, from a performance perspective, do you think it would be better to get the SSZ encoded object and decode it or transmit the entire JSON object over the wire? If decoding SSZ --> JSON is fairly performant, it might be better to take this approach, especially if we think the `BeaconState` and `BeaconBlock` might increase in size.


> I heard from Sean you were also considering state diffs, and we actually have something along those lines already implemented too, but on the `tree-states` branch: https://github.com/michaelsproul/lighthouse/blob/9ab7c24e5a6172a0d134ed9f4df5112c39865343/consensus/types/src/beacon_state/diff.rs#L29-L89. Again, it'll be a while before that lands. The diffs end up being 6-9MB per state (relative to the state at the previous epoch).

This is very very interesting work. I will have to take a closer look at this. If we can send these statediff objects over the wire then it might be worth it to consider them in our application design and architecture.

**Comment by abdulrabbani00** [comment]
> # GitHub Issue: Lighthouse
> # Overview
> I would like to add a few HTTP endpoints for my team's use case. I am more than happy and willing to write all the code needed to implement these features. I only ask for guidance and help.
> 
> _This is the second iteration of the proposal._
> 
> ## Use Case
> My teams use case is as follows:
> 
> 1. We want to capture every `BeaconBlock` and `BeaconState` for every slot from `genesis` to `head` in a Postgres DB.
> 2. We want to capture `missed` slots (slots that were skipped).
> 3. We would like to capture all processed `BeaconBlocks`, even the ones that are `forked` when watching the head of the chain.
>    
>    1. We would like to label the blocks that are `forked` as `forked` in the Postgres DB.
> 
> ## Running the Nodes
> On the first go, we plan on having two `lighthouse` nodes running.
> 
> 1. The sole purpose is to keep up with the head of the chain. This node will update the database with the latest information from the head.
> 2. An archival node that has every block since genesis available. This node will be used to fill the database for historical events, as well as missed events.
> 
> # Endpoints
> The following capture all the endpoints that we are hoping to expose on the beacon node, as well as potential implementations for them. The actual names and "endpoints" themselves can be easily changed and modified. This example is simply using dummy placeholders.
> 
> ## [`/lighthouse-events?topic=head`](https://github.com/ethereum/beacon-APIs/blob/master/apis/eventstream/index.yaml#L41) - Update
> ### Result We Want
> Update the endpoint to accept a parameter, that will return the entire `block` and `state` object in either JSON or SSZ encoded format.
> 
> Keep in mind that we can have multiple proposed head `BeaconBlocks` for a given slot.
> 
> If someone is listening to this endpoint they might see:
> 
> ```
> {"slot":"10", "block": "SSZ_OBJECT_A", "state":"SSZ_OBJECT_X", "epoch_transition":false, "previous_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e91", "current_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e91", "execution_optimistic": false}
> ...
> {"slot":"10", "block": "SSZ_OBJECT_B", "state":"SSZ_OBJECT_Y", "epoch_transition":false, "previous_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e92", "current_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e92", "execution_optimistic": false}
> ...
> {"slot":"11", "block": "SSZ_OBJECT_C", "state":"SSZ_OBJECT_Z", "epoch_transition":false, "previous_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e93", "current_duty_dependent_root":"0x5e0043f107cb57913498fbf2f99ff55e730bf1e151f02f221e977c91a90a0e93", "execution_optimistic": false}
> ```
> 
> ### Potential Implementation
> Update the features and functionalities to the current head endpoint to capture the entire SSZ encoded objects and return them if the necessary parameter is specified.
> 
> ## `/lighthouse/v2/debug/beacon?states?start_slot=x?end_slot=y`
> ### Result We Want
> Expose an HTTP event stream endpoint that will stream the historical `BeaconState` from the start to the end slots provided.
> 
> ```
> Parameters: {start:10, end: 12}
> 
> [
>   {
>      "Slot: 10,
>      "BeaconStates": dict_a
>   },
>   {
>      "Slot: 11,
>      "BeaconStates": dict_a --> Because this slot has no BeaconBlock.
>   },
>   {
>      "Slot: 12,
>      "BeaconStates": dict_c
>   }
> ]
> ```
> 
> ### Potential Implementaion
> Utilize the code for doing this in the [`BlockReplayer`](https://github.com/sigp/lighthouse/blob/stable/consensus/state_processing/src/block_replayer.rs), which is used to back the existing [`/lighthouse/analysis/block_rewards`](https://lighthouse-book.sigmaprime.io/api-lighthouse.html#lighthouseanalysisblock_rewards) endpoint.

@michaelsproul and @realbigsean - I believe this should be the last proposal here.

I update the `head?topics` endpoint to accept a new parameter which would provide the entire SSZ encoded object or JSON  for the `state` and the `block`. Let me know if this is feasible, or if we will have to move this functionality to a non-standard endpoint. If I can get your teams sign off and blessing, I can start working on the implementation.

Also: 
> * Also, from a performance perspective, do you think it would be better to get the SSZ encoded object and decode it or transmit the entire JSON object over the wire? If decoding SSZ --> JSON is fairly performant, it might be better to take this approach, especially if we think the `BeaconState` and `BeaconBlock` might increase in size.

**Comment by abdulrabbani00** [comment]
Hello Guys,

We have decided we are going to stick with the currently existing features within the lighthouse for our use case. The current performance we are seeing is perfectly fine for what we are trying to achieve. I appreciate all your help, and if we need anything else I will be sure to raise another issue.

Please let me know if there is anything I can ever do for your team.

Thank you,
Abdul Rabbani
