### ISSUE TITLE
Set `safe_block_hash` to the justified block hash

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3189]
## Description

As pointed out by @michaelsproul, we are setting the `safe_block_hash` value as per an old specification:

https://github.com/sigp/lighthouse/blob/38050fa460c28812f5c2026765fe12f497f03ef5/beacon_node/execution_layer/src/lib.rs#L851-L857

The new specification declares that we should use the block hash of the *justified checkpoint* instead:

https://github.com/ethereum/consensus-specs/blob/dev/fork_choice/safe-block.md

**Comment by paulhauner** [comment]
I will fix this in #3175

**Comment by dapplion** [comment]
A network deployment with only lighthouse and nethermind nodes stalled because nethermind errors on all fork-choice update calls with:

`"Inconsistent forkchoiceState - safe block hash. Request: ForkchoiceState: (HeadBlockHash: 0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b, SafeBlockHash: 0xa2e14ea188d4dc9b247b45367a4b45b45eabfe5ebbf0cd15eaba5ccc4902ff7b, FinalizedBlockHash: 0x528f0716d2431e2cf59c93ef2f9af7350dd409de4b40fdae617bef4b15f7d02d) PayloadAttributes: (Timestamp: 1656283875, PrevRandao: 0xb5aec702d8c74b392586b2c39acc51b5ebe0313e951429bd65f5fc1b1a1dda2a, SuggestedFeeRecipient: 0xf97e180c050e5ab072211ad2c213eb5aee4df134)`

- Full details and description of the incident: https://github.com/gnosischain/consensus-deployment-ansible/issues/6

**Comment by michaelsproul** [comment]
The relevant check in Nethermind that we're tripping is here:

https://github.com/NethermindEth/nethermind/blob/a35d4f1d192494b61d91d34bc74bfbf8866aaa8b/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs#L175-L180

The consistency check requires:

1. The safe block hash is zero, or
2. The safe block hash is part of Netheremind's canonical chain

https://github.com/NethermindEth/nethermind/blob/a35d4f1d192494b61d91d34bc74bfbf8866aaa8b/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs#L243-L246

The block currently being imported isn't considered part of the canonical chain, so our current implementation will fail both checks. Using the justified block hash as per the spec _should_ unblock this.

**Comment by michaelsproul** [comment]
Actually I'm not sure that the block currently being imported isn't considered part of the canonical/"main" chain. These lines would seem to suggest it gets added before the consistency check: https://github.com/NethermindEth/nethermind/blob/a35d4f1d192494b61d91d34bc74bfbf8866aaa8b/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs#L161-L166

**Comment by michaelsproul** [comment]
I actually think the ultimate cause of death for the Gnosis devnet was a payload reconstruction issue: https://github.com/gnosischain/consensus-deployment-ansible/issues/6#issuecomment-1169445538

**Comment by michaelsproul** [comment]
I'll take this

**Comment by paulhauner** [comment]
Resolved via #3347 :tada:
