### ISSUE TITLE
Beacon data directory grows indefinitely

### ISSUE THREAD

**Issue by jmcruz1983** [sigp/lighthouse#3207]
## Description

Running beacon with `--datadir=/data` and mounted that directory in a separated volume,
I noticed following issue that volume keeps growing and thus I need to resize it,

Running for about 90 days already filled up 100 GiB

<img width="1634" alt="beacon" src="https://user-images.githubusercontent.com/15966694/169791407-b70a05bb-a534-465d-8641-e260ee0a8e9c.png">

From beacon options I understand that auto-compacting database is enabled by default:

```
OPTIONS:
        --auto-compact-db <auto-compact-db>
            Enable or disable automatic compaction of the database on finalization. [default: true]
```

## Version

Version used is public `v2.2.1`

## Conclusion

Is there any recommended size for beacons `datadir`?
Is auto-compacting working as expected?
Any mitigation?

Thanks

**Comment by michaelsproul** [comment]
Most of that space (~80GB) is consumed by the beacon blocks themselves, and there are more of them to store with each passing day. We have a few plans up our sleeve to curtail the growth:

1. Apply compression to the blocks (likely a 2-4x reduction). This can be done at any time but needs to be done carefully and with a DB migration. We'll probably do it after the merge.
2. Limit the storage of historical blocks (similar to EIP-4444). This is a change of the P2P protocol guarantees, and requires agreement and coordination with the other clients and the community. It will no longer be possible to sync from genesis if everybody adopts this change.
3. Add a mode for running without historical states. These states aren't necessary for validating nodes, so dropping them can save around 20GB of space. This might be added as a flag before the merge, depending on time constraints.

I'll open targeted issues for the 3 planned upgrades tomorrow because currently they're not on Github.

As a temporary workaround you can:

1. Make sure new nodes start with checkpoint sync so that they store as few historical states as possible.
2. Make sure you're using `--slots-per-restore-point 8192`, which is the default for new databases as of v2.2.0.

If you're willing to re-sync existing nodes you could get both benefits, although you'll have to download all of the historic blocks again which I know has caused issues with your setup in the past (#2904). I re-synced my own BN about two months ago and it's using 83.6GB, split 79GB for the `chain_db` (the blocks) and 4.6GB for the `freezer_db` (historic states).

**Comment by jmcruz1983** [comment]
Thanks @michaelsproul for suggestions,
I'll keep an eye on upcoming upgrades & feature flags,

About checkpoint sync, we do use that one to avoid full re-sync,
but as side effect beacon node becomes bit unstable for some hours (like 24h)
as it is backfilling in the background and getting CPU spikes,
Can you confirm that this behaviour is still happening?
Thanks

**Comment by michaelsproul** [comment]
> Can you confirm that this behaviour is still happening?

Yeah, we've had a few reports of that. We also need to open an issue for rate-limiting block backfill, thanks for the reminder!

**Comment by michaelsproul** [comment]
Ok, closing in favour of 5 new issues which I've finally put down on paper!

#3212 #3211 #3210 #3209 #3208
