### ISSUE TITLE
Goerli / Prater network alias

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3338]
## Description

This was brought up in Discord by @yorickdowne. It feels like we should support `--network goerli` because it's the longer-standing network name and it's not intuitive to have a different EL and CL network name. We've had a discrepancy in EL/CL names the past but not on testnets that are planned for long-term use.

It's not as easy as I originally thought to support both names though. A few things we could maybe do:

1. [Alias](https://docs.rs/clap/latest/clap/struct.PossibleValue.html#method.alias) the `prater` value in `clap` unfortunately it isn't possible to alias values until we upgrade to `clap` `v3.0`. This also would lead to some weird behavior. Value aliases are hidden (I think) so we could only display one of the two names. You would also potentially have the default datadir's name be different from the network name you provided.
2. Add a built in network config named `goerli` that's just a duplicate of the `prater` config. This would be easy to do but more of a pain to maintain. You would also instantiate a different datadir based on which network name you are using which is.. weird.
3. Support aliases in `Eth2NetworkConfig::constant` - this seems like it might be a decent solution but we'd have to create something like a new `HARDCODED_NET_NAMES_WITH_ALIASES` array and use that with `clap` possible values. We would then *also* have to update `get_network_dir` to make sure aliases are used there because we are directly getting the network dir from the `network` flag
4. Leave everything as-is, I'm not totally sure it's worth the trouble

**Comment by paulhauner** [comment]
I have a feeling that other consensus clients will adopt this alias and that we'll be expected to as well. I would lean towards (3), I'm not exactly sure how to go about it though. I suspect it's possible but it'll involve fiddling with some macros.

**Comment by paulhauner** [comment]
I'm going to have a play around and see if I can make this work now.

**Comment by paulhauner** [comment]
I didn't consider this properly, but if we just use an alias then users will use `--network goerli` and end up with a `.lighthouse/prater` data directory. That might be a bit challenging for our documentation.

I'm going to have a look at making a unique Goerli network that shares the same genesis state as Prater. I think the only real downside to just having Prater/Goerli separate is the duplication of the genesis state.

**Comment by paulhauner** [comment]
I have two competing implementations at:

- #3346
- #3348

**Comment by paulhauner** [comment]
Regarding option A (#3346) vs option B (#3348), it seems that we have consensus among LH developers that option A is preferred. I am also of that mind.

The difference between the two is:

- Option A: use `--network goerli` and get a datadir in `~/.lighthouse/goerli`
- Option B: use `--network goerli` and get a datadir in `~/.lighthouse/prater`

I think the nice things about option B is that it:

1. Allows *existing* users to start using `--network goerli` today without requiring any extra effort.
2. Whilst it has the weirdness of `--network goerli` creating a `./lighthouse/prater` directory, we leave the door open to an automatic migration in the future.

Regarding (1), I don't see a huge amount of value in getting *existing* users to switch from "prater" to "goerli". I think they already have a very good understanding that the two networks are related and merging together. The idea that your Prater CL connects to a Goerli EL is well understood for existing users.

Regarding (2), it would be nice to do an automatic directory migration. However, I'm aware that this is not as simple as `mv prater goerli`. Since the `validator_definitions.yml` file (regretfully) uses absolute paths we're going to need to do some YAML twiddling as well. I'm also concerned about the scenario where someone with an automated devops environment switches to `--network goerli` but leaves their scripts to assume the datadir is at `.lighthouse/prater`. Then, we come along with the automatic-migration release and move that directory on them.

So, with option B we are saying:

*"You can change your `--network` flag now and but we'll leave your datadir where it is. However, we might or might not move that datadir in the future."*

Whereas with option A we are saying:

*"If you want to keep everything the same, don't touch your `--network` flag. If you want to change your `--network` flag, then you're going to need to manually migrate your datadir."*

Also with option A we know the following facts:

1. All *existing* Prater devops setups are necessarily compatible with supplying "prater" to their CL and "goerli" to their EL.
1. All *new* devops setups can use "--network goerli" they'll get an entirely predictable datadir that we're not planning to move.

Given that "prater" isn't an offensive or damaging word and it's totally OK if it lingers in existing setups, I'm much more partial to the idea that option A is consistent, stable and doesn't suggest we *might* do something later.
