### ISSUE TITLE
Flag to define headers in engine API requests

### ISSUE THREAD

**Issue by pablomendezroyo** [sigp/lighthouse#3409]
### Description

With the upcoming merge, 1 EL node cannot receive the head chain from multiple CL nodes due to subjectivity. For this reason, makes sense to look for ways to restrict the use of the engine API in the EL, so it is used by one CL at a time.

### Describe the solution you'd like

In addition to the `auth-token` would be nice to add headers to the EL endpoint (`--execution-endpoint`) requests, to indicate the Host who is requesting. This could be used in conjunction with the host whitelist in Geth `--authrpc.vhosts value`, see [geth docs](https://geth.ethereum.org/docs/interface/command-line-options).

**Comment by michaelsproul** [comment]
Geth's `vhosts` flag checks the HTTP request's [`Host`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) header against the server's list of allowed hostnames. So if you're hosting Geth on `localhost` (with `--authrpc.vhosts localhost`, the default), it will refuse requests made to `geth.com` (assuming traffic from `geth.com` is routed to Geth via a reverse proxy).

To use this to enforce engine connections from a single CL you would need to have the controlling CL use a different hostname for Geth than the other API consumers. You could have `engine.geth.com` and `rpc.geth.com`, where `engine.geth.com` is only accessible to the controlling CL, and Geth enforces this with `--authrpc.vhosts engine.geth.com`. But then you still need to lock down `engine.geth.com` using authentication (a JWT?) or there's nothing to stop clients just putting `Host: engine.geth.com` in their requests and bypassing the `vhosts` check.

I'm open-minded to the idea of extra headers on engine API requests, but I think the above example demonstrates that it would require more than just Geth's `vhosts` flag to be useful. I suspect you'd need some kind of multiplexer middleware which checks that certain engine API requests are from the controlling CL and only forwards them if they are. Seeing as the CLs support JWTs already, I think you could use a unique JWT for each CL like this:

```
CL1 -> jwt1 ->
CL2 -> jwt2 -> middleware -> jwt4 -> EL
CL3 -> jwt3 ->
```

Each CL could use a unique [`id`](https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md#jwt-claims) in its claims so that the middleware knows which JWT secret to use when verifying. The middleware would then only forward sensitive requests (like `forkchoiceUpdated`) for the currently nominated controlling CL (which could change dynamically!). For this it would use a separate JWT secret known only to the middleware and the EL. Anyway, this scheme _still_ doesn't require custom headers and would be do-able using Lighthouse's existing `--execution-jwt-id` flag.

**Comment by pablomendezroyo** [comment]
thank you for the suggestion!
