### ISSUE TITLE
Missing head events

### ISSUE THREAD

**Issue by aratz-lasa** [sigp/lighthouse#3575]
## Description

When I subscribe to head events through `eth/v1/events?topics=head`, from time to time, I get a jump in the slots. In other words, I miss some slots. Moreover, when I miss the slot, I usually get a event which is completely blank and cannot be unmarshalled to JSON.

## Version

I'm using the v3.1.0 version.

## Expected Behaviour

I expect to receive head events for all the slots.

## Steps to resolve

I'm not sure how to resolve this.

**Comment by michaelsproul** [comment]
The blank events are keep-alive comments, which are part of the SSE spec and mentioned in the beacon chain spec: https://ethereum.github.io/beacon-APIs/#/Events/eventstream

The absence of head events at some slots is probably due to skipped slots. The current semantics of the `head` event is that it fires only when the head changes, so there won't be any event published if a slot is skipped (the proposer fails to publish a block).

**Comment by aratz-lasa** [comment]
Okay, @michaelsproul thank you very much for your fast response!
