### ISSUE TITLE
Feature request for a more streamlined update process

### ISSUE THREAD

**Issue by uwuforever** [sigp/lighthouse#3633]
From https://stackoverflow.com/questions/1712033/replacing-a-running-executable-in-linux it should be possible to replace a running executable with `execve` without restarting it.

The update experience would be so nice if Lighthouse could detect if its binary has been overwritten with a new version, and either simply use execve to seamlessly switch over, or have an RPC API call that could trigger it. As a bonus this would avoid any missed attestations from the doppelganger protection, while being safer.

An update would then consist of just these 2 commands:

1. Check for update: `cd ~/lighthouse && git pull && git checkout stable && make`
2. Replace running lighthouse binary, keeping a copy just in case: `sudo mv $HOME/.cargo/bin/lighthouse /usr/local/bin/lighthouse -u -b -f --suffix=.old`

**Comment by michaelsproul** [comment]
I'm hesitant to add anything like this because I don't think it really offers a substantial UX improvement over restarting the binary manually. If we used `exec` to run the new binary it would _not_ bypass Lighthouse's startup sequence, whether that's doppelgänger protection (VC) or re-loading the database (BN). To do anything more sophisticated would be very complex – somehow keeping the in-memory structures from one version while switching to the new version would be very fraught, and would impose weird constraints on the kinds of changes we could make between versions. In other words, the only viable implementation would be equivalent to just `sudo systemctl restart lighthouse`, which is easily scripted.

As a workaround for starting the VC faster one can simply not use doppelgänger protection most of the time. Or we could add a doppelgänger protection mode which skips the actual checks unless the binary has been offline for more than N minutes.

For the BN we also have plans to speed up restarts by making the DB faster to re-load.

**Comment by michaelsproul** [comment]
This is the BN feature to improve startup times: https://github.com/sigp/lighthouse/issues/3505

**Comment by uwuforever** [comment]
Ah okay, that's a lot less useful than I was expecting. I'm happy to just stick to manual restarts in that case.

Could doppelganger protection detect that it was restarted on the same system? Maybe keep a copy of the last few attestations from this particular install in a temp file, so when the VC starts up again and detects the previous attestations, it can immediately confirm that there is no doppleganger risk
