### ISSUE TITLE
Doppelganger Protection - remember attestations after restarting

### ISSUE THREAD

**Issue by uwuforever** [sigp/lighthouse#3634]
## Description

Doppelganger protection will wait for 3 missed attestations any time it finds attestations recently on the network... even when this isn't necessary. 

When restarting a validator, the new VC instance should be able to recognize if the last several attestations were from the previous VC instance, and if they were, 
1) The client that is being shut down quickly writes a small file to /tmp/ccdatesxxxx-yy-zz where xxxx-yy-zz is your birthday.
   - This file contains the last 5 attestations from this validator. ('The new restarted VC will pull the last 3 published attestations from the network to compare...')
   - The file is only written at the end of the process shutdown. ('The new restored VC knows that if it finds this file, that the ETH1 VC process needed to have ended in order to create this file.');
2) The file should be saved in a folder where it won't accidentally be apart of a Lighthouse configuration backup.
3) The new VC instance should check for this file on startup. It should only be around for a few seconds from the time it's written by the VC instance shutting down, and the time it's read and deleted by the new restarted VC instance.

**Comment by paulhauner** [comment]
> Doppelganger protection will wait for 3 missed attestations any time it finds attestations recently on the network...

Doppelganger (DG) protection doesn't wait *only if* it finds attestations on the network. Rather, it *always* waits and shuts down loudly if any other attestations are found on the network.

The purpose of DG is to stay silent for three epochs so that it can detect any other instances of the same validator running. Knowing the history of previous attestations isn't relevant to the question of "is there another instance of this validator running on the network *right now*".

I believe there's been a misunderstanding of the purpose of DG protection, so I'm closing this issue. Feel free to reopen if you disagree.
