### ISSUE TITLE
Compile with beta compiler on CI

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3709]
## Description

We've been "rugged" by new Rust releases a couple of times (recently: https://github.com/sigp/lighthouse/issues/3695). I think we could avoid this by compiling with the Beta compiler on CI. This will give us a bit more lookahead on changes that are going to break releases.

## Steps to resolve

- Add a job to `test-suite` which compiles Lighthouse with Rust beta. I don't think we should block Bors on this job initially in case the beta compiler breaks in a strange way. To rule out linking errors the build should probably run `make` to completion, not just `cargo check`.

**Comment by danielrachi1** [comment]
Hi! I'm working on this and I'm already testing a possible solution. I'll create the PR in a few hours if my test workflows behave as expected.
My intention is to add a job that does the workaround you mentioned in #3695, but using `beta` instead of `1.64`.
After installing the dependencies listed in the [build from source guide](https://lighthouse-book.sigmaprime.io/installation-source.html), It'll run `rustup override set beta` and then run make. (I agree we should run `make` instead of `cargo check`.)

**Comment by michaelsproul** [comment]
Fixed by #3717 thank you @danielrachi !
