### ISSUE TITLE
GUI - Participation Rate Api

### ISSUE THREAD

**Issue by rickimoore** [sigp/lighthouse#3765]
## Description

The main dashboard view in the lighthouse ui design displays a component that tracks the overall participation rate in percentage format.

![Screenshot 2022-12-01 at 16 08 42](https://user-images.githubusercontent.com/12932889/205102353-89f73e19-295c-4295-ad08-1240e93b1475.png)

## Expected Behaviour

There should be an api that accepts an array of validator pub-keys and returns a percentage value based on their participation rate.

**Comment by AgeManning** [comment]
I believe this is being handled in #3724. I think @macladson is working on it. 

The actual number we could present there is maybe two numbers. Maybe we should show:
- Percentage missed head votes
- Percentage of full attestation rewards achieved

So instead of `participation rate` we display `missed head votes` and `full attestation rewards`.

**Comment by michaelsproul** [comment]
> Percentage of full attestation rewards achieved

This will require an archive node/beacon.watch, and likely the new reward APIs from https://github.com/sigp/lighthouse/issues/3661

**Comment by AgeManning** [comment]
This has been resolved. Using the standard HTTP API for this.
