### ISSUE TITLE
Cache Validator Info For Last 10 Epochs

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#3804]
## Description

The UI builds a graph which requires the balances of the validators over the last 10 epochs. Currently it is requesting this via the 
/eth/v1/beacon/states/{states}/validators?id={vals} API end-point. 

The issue is that the request takes a very long time in order to complete, likely because its trying to fetch and old state. We also need the validators balance from a year ago and also a month ago. 

In order to make this user friendly and not have to wait > 1m to collect these endpoints, I was thinking when the `--gui` CLI flag is set, we could cache these values. 

I.e Store a cache that holds the last 10 epochs for validators we are monitoring and then make this endpoint return super fast.

As for the state a year ago, perhaps this is a problem for another time, unless anyone has some suggestions (maybe @michaelsproul)

**Comment by michaelsproul** [comment]
Caching could be a good short-term solution, but nodes that have checkpoint synced only have access to states from when they started, and can't access states from a month/year ago even if they're willing to pay slow processing times (they have to opt in to reconstructing historic states, which takes about a week).

This seems to be a pretty fundamental tension in the GUI: we want users to be able to access historic data quickly on their own node, but we also don't want them to have to pay the expensive storage cost to make this feasible. Tree states helps a bit because it makes running an archival node cheaper in terms of disk space, but there'll still be users who don't want to opt in to _any_ extra storage for historic states. If we implement https://github.com/sigp/lighthouse/issues/3211 users can even run in perpetuity with no historic states at all.

Given this, my preference is:

- Periodically cache 10 epoch, 1mo, 1y balances on a best-effort basis. If any required state doesn't exist, cache its non-existence and serve an error on the balance endpoint.
- When balance data isn't available, have the UI fail gracefully and suggest enabling `--reconstruct-historic-states`.
- Optionally allow users to pull this data from somewhere else, e.g. `beacon.watch`, `beaconcha.in`, or another BN with history.

**Comment by AgeManning** [comment]
Yeah, agreed. I was thinking we don't worry about the long-term cases. Potentially these can be pulled from somewhere else. 

But the short-term 10 epochs I think should be do-able in a cache. I'd imagine most BN's will be running for longer than 10 epochs.

**Comment by macladson** [comment]
I had a bit of a different take in #3863. I instead expanded the scope of the validator monitor to cache additional values. It will need to populate the values after the node boots for the first time but does not require any state reads.

Unfortunately this does not solve historical values (1 month / 1 year) so is not a complete solution.
