### ISSUE TITLE
Produced Orphaned block

### ISSUE THREAD

**Issue by PacoBits** [sigp/lighthouse#3963]
We have produced a forked/orfan block:
https://beaconcha.in/slot/5770016
Validator: 338395
Slot: 5770016
Epoch: 180313

We have a 3-layer configuration with the validator client, the Beacon node and the execution client running separately.
We are using Mev-boost.
The setup is working well before and after the orfand block produced. So the problem is related to something "casual"

```

node07         | Feb 10 16:30:36.495 INFO Successfully published block            slot: 5768551, graffiti: Some("Block by Stakely Lido07"), attestations: 97, deposits: 0, block_type: Blinded, service: block
node07         | Feb 10 19:14:48.068 INFO Successfully published block            slot: 5769372, graffiti: Some("Block by Stakely Lido07"), attestations: 128, deposits: 0, block_type: Blinded, service: block
node07         | Feb 10 19:20:35.990 INFO Successfully published block            slot: 5769401, graffiti: Some("Block by Stakely Lido07"), attestations: 77, deposits: 0, block_type: Blinded, service: block
node07         | Feb 10 21:23:41.061 INFO Successfully published block            slot: 5770016, graffiti: Some("Block by Stakely Lido07"), attestations: 74, deposits: 0, block_type: Blinded, service: block
node07         | Feb 10 22:49:00.007 INFO Successfully published block            slot: 5770443, graffiti: Some("Block by Stakely Lido07"), attestations: 105, deposits: 0, block_type: Blinded, service: block
node07         | Feb 11 00:23:35.871 INFO Successfully published block            slot: 5770916, graffiti: Some("Block by Stakely Lido07"), attestations: 99, deposits: 0, block_type: Blinded, service: block
```

Validator setup and version: Lighthouse/v3.4.0-38514c0
```
lighthouse vc
--beacon-nodes http://LH,http://SERVER_ON_MAINTENANCE,http://ip3
--network mainnet
--metrics
--metrics-allow-origin *
--graffiti "Block by xxxxxxx"
--suggested-fee-recipient 0x388Cxxxxxxxxxxxx
--init-slashing-protection
--metrics-port xxx
--http
--builder-proposals
```

Beacon setup and version: Lighthouse/v3.4.0-38514c0
```

      lighthouse beacon
      --network mainnet
      --execution-jwt  /xxxxxxxxxxxxxxx
      --execution-endpoint  http://localhost:xxxxx
      --subscribe-all-subnets
      --import-all-attestations
      --graffiti "Block by Stakely.io - blh01"
      --metrics
      --metrics-allow-origin xxxxx
      --http
      --http-address xxxxxxxx
      --http-port xxxxx
      --port xxxxxxx
      --checkpoint-sync-url https://mainnet-checkpoint-sync.stakely.io/
      --suggested-fee-recipient  0xxxxxxxxxx
      --builder http://xxxxxxx
```

Execution setup and version: Geth/v1.10.26-stable-e5eb32ac/linux-amd64/go1.18.8
```

      --mainnet
      --syncmode=snap
      --http
      --http.api "eth,net,web3,engine,admin"
      --http.corsdomain "*"
      --http.addr 127.0.0.1
      --http.port xxxx
      --cache  16384
      --port xxxx
      --authrpc.port xxx
      --authrpc.jwtsecret "xxxxxx"
      --authrpc.vhosts "xxxx"
```
Lighhouse Beacon logs are relevant  because the first lines show the BN loses several seconds because a new  block received changes the parent root of the Prepared beacon proposer for slot 5770016.

[lh-bn-orfandblock10022023.txt](https://github.com/sigp/lighthouse/files/10713019/lh-bn-orfandblock10022023.txt)

[mev-boost-orfandblock10022023.txt](https://github.com/sigp/lighthouse/files/10713027/mev-boost-orfandblock10022023.txt)

Important note: VC is connected to several BNs, one of the then is shut down because it is currently undergoing maintenance.This doesnt affect this problem but you'll see warnings in VC logs. 

[lh-vc-orfandblock10022023.txt](https://github.com/sigp/lighthouse/files/10713026/lh-vc-orfandblock10022023.txt)

**Comment by michaelsproul** [comment]
Hey @PacoBits thank you for the detailed report. We're always interested in looking into these cases to ensure Lighthouse is behaving as close to optimally as possible.

It seems the problem in this case lies in the connection between the BN and the VC. I'll lay out the timeline below so you can see what I mean.

- The start of slot 5770016 is `21:23:35`. We see a correct proposer preparation message sent at `21:23:24`, a full 11 seconds prior to this. The previous proposer preparation message you saw (before the parent block arrived) is not an issue as it will be overridden by the more recent one.
- The BN requests a payload from the relay 0.445s into the slot, which is quite quick. Some delay here might be attributed to the link between the VC and the BN.
- The BN receives a payload header from the relay after ~950ms, at 1.4s into the slot. This 950ms is the maximum time that mev-boost will wait for a header, and can be adjusted down with the `-request-timeout-getheader` flag. The reason for this step taking the maximum time is that the bloxroute relays timed out. Still, we're only 1.4s into the slot at this point, so we should have time to publish the block before the 4s attestation deadline.
- Unfortunately we end up publishing the block at `21:23:39.647`, i.e. 4.6 seconds into the slot (late). The logs are a bit bare at this point because the VC only logs this at debug level, but the things that need to happen between the previous step and publishing the header are:
   - Downloading the header to the VC.
   - Signing the header in the VC.
   - Uploading the signed header back to the BN.
   
  If the internet connection between the VC and the BN is slow or unreliable that _could_ explain this step taking ~3.2 seconds.

Because the block was published late, it got re-orged by another Lighthouse node, which will now re-org any blocks that fail to get enough attestations (to incentivise on-time blocks).

In terms of practical next steps there are a few things to try:

- Investigate the latency on the connection between the VC and the BNs. If they are in different geographic regions this will add quite a lot of latency which be baked into block proposal times, particularly when using `mev-boost`.
- Try lowering the `getheader` timer on `mev-boost`. This doesn't seem to be the main problem but could help temporarily while you debug network issues.
- DM me debug logs from the validator client. You can find them in `$datadir/beacon/validators/logs/`. You can DM them to me on Discord (`@sproul#3907`). This will help confirm there's no inefficiency lurking in the VC.

**Comment by PacoBits** [comment]
Thank you for your detailed analysis @michaelsproul 
I am sharing with you debug logs from VC on discord. 

Leaving the issue open to share conclusion
