### ISSUE TITLE
Add Attestion Inclusion Distance in the HTTP API

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#4097]
It probably would be nice to add the attestation inclusion distance for monitored validators to display in the GUI. 

This is a tracking issue for this

**Comment by int88** [comment]
Maybe I could try this one? @AgeManning

**Comment by AgeManning** [comment]
Yep sure if you want to take it on. 

I'm not sure how much you know about lighthouse and the HTTP API. We are using warp, which makes the types kind of tricky. 

I think the idea of this issue is to add an average attestation inclusion distance as an extension (or extra field) to this: https://github.com/sigp/lighthouse/pull/3760

You could look at that PR to figure out how to extend it. I've not yet looked into whether we store the inclusion distance in the metrics, but we could add it. 

Let me know if you have any questions. I think @macladson will also be able to help out and have thoughts on how this could be implemented.

**Comment by int88** [comment]
[VALIDATOR_MONITOR_PREV_EPOCH_ON_CHAIN_INCLUSION_DISTANCE](https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/src/metrics.rs#L593) seems to be the metric we want to expose, but actually it's [the min attestation inclusion distance](https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/src/validator_monitor.rs#L675).

We should try to write some code to calculate the average distance, [this method](https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/src/validator_monitor.rs#L163) maybe a good place.

WDYT? @AgeManning

**Comment by michaelsproul** [comment]
I think min inclusion distance is the right choice, the min is per validator so it just accounts for the same attestation being included in multiple blocks. E.g. if my attestation is included after 1 slot and then again after 3 slots in a different block the min distance will be 1

**Comment by AgeManning** [comment]
Yep. If we can report the min for the last epoch in the API returned value, the UI (which will consume this endpoint) can calculate averages and stuff for us for periods greater than 1 epoch. 

Just going to cc @rickimoore in on this too.

**Comment by int88** [comment]
Maybe `lighthouse/analysis/attestation_performance/{index}` is a better than `lighthouse/ui/validator_metrics` as an endpoint to get attestation inclusion distance.

Because the `validator_metrics` endpoint doesn't have epoch information in the query and the metrics it response are those across all epoches.

`attestation_performance` endpoint is the opposite, we could get attestation performance of some validators in some epoches. Also it has `delay` field which is quite close to the metric we want to expose, although I think it only work under `Base` fork version.

@AgeManning WDYT?

**Comment by michaelsproul** [comment]
Using the metrics is preferable to using the analysis endpoint because they're basically "free" to compute, and will work for modern forks (nobody uses `Base` any more). By contrast the analysis endpoints are expensive to compute because they need to load historic states from disk, which is a) slow and b) not always guaranteed to work if those states have been deleted

**Comment by int88** [comment]
If use metrics, maybe we could just use min_inclusion_distance of the latest epoch.

Because for other metrics like `attestation_target_hits` is accumulated with epoches. So it's maybe inappropriate to extend the metrics endpoint that use epoch as the query parameter.

@michaelsproul  WDYT?

**Comment by michaelsproul** [comment]
Yeah I think that would be OK, just the min delay per validator for the most recent epoch, added to `/lighthouse/ui/validator_metrics`. @AgeManning can comment on whether he thinks that's sufficient for the UI

**Comment by AgeManning** [comment]
Resolved in #4148
