### ISSUE TITLE
Fail compiling simulator rust error E0275

### ISSUE THREAD

**Issue by whysthatso** [sigp/lighthouse#4144]
Installing from Arch Linux AUR, i get the below compile error. This is trying to compile v3.5.1 (latest version in AUR package)

I'm currently running Lighthouse v3.1.2-01e84b7 and have not had compile issues before.

Logs in this gits due to length: https://gist.github.com/whysthatso/c7656c1877bbce3888f6e305db5f5219

**Comment by michaelsproul** [comment]
Updating either Lighthouse or `rustc` (if you're able) should fix this. This error was a very annoying one that would crop up from time to time on certain compiler versions. It's basically the compiler giving up because the types are too complex. We've fixed it in our latest release by simplifying the types so that compiling is reliable across rust versions.

**Comment by michaelsproul** [comment]
Closing as resolved
