### ISSUE TITLE
Fix exit verification at fork boundaries

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#4184]
## Description

In #4183 we made a patch to fix high CPU usage for exit verification across skip slots.

This patch doesn't cover the case where we receive an exit for epoch `E + 1` when the head state is in epoch `E` and those two epochs are across a fork boundary.

**Comment by michaelsproul** [comment]
I think the signature check is OK actually, because it uses the exit's internal epoch:

https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/consensus/state_processing/src/per_block_processing/signature_sets.rs#L390-L395

But the other checks relative to current epoch are liable to fail, e.g.

https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/consensus/state_processing/src/per_block_processing/verify_exit.rs#L46-L53

Plumbing an optional wall-clock epoch into `verify_exit` could be one way to verify future exits from the current head state

**Comment by paulhauner** [comment]
I've started working on a fix in #4183, so we might not need this issue after all.

**Comment by michaelsproul** [comment]
Closed by #4183
