### ISSUE TITLE
BlockRootsIterator skips the block at the start slot

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#419]
## Description

The `BlockRootsIterator` iterates backwards over all blocks from a given slot, but doesn't ever return the block at the `start_slot` which the iterator is instantiated with.

## Present Behaviour

Iterates backwards over blocks from `start_slot - 1` (inclusive)

## Expected Behaviour

Iterates backwards over blocks from `start_slot` (inclusive)

## Steps to resolve

I think we should either change the behaviour so that the block at the `start_slot` is included, or we should document that the iterator behaves as it does.

I tried changing the impl of `Iterator` so that it decrements `self.slot` _after_ retrieving the block root, but this broke a bunch of things in the reduced-tree fork choice, so I didn't push through with it.

**Comment by paulhauner** [comment]
Good pick up, thanks for raising this. I've been meaning to explain my rationale here.

The root at `state.slot` is a little tricky. Firstly, we can never get it from `state.block_roots` because it only gets included when `process_slot` transitions into the next slot.

There is the possibility that if `state.beacon_block_header.slot == state.slot` we could determine the beacon_block root, however that means running `tree_hash(state)` and `tree_hash(state.beacon_block_header)`.

Therefore, I feel that it's not worth returning the `state.slot` root because it's potentially going to do a couple of very expensive operations. The way the iterator works means that, in some cases, you'll have to do these expensive hashes _even if_ you don't want the first block root (i.e., you're skipping past it to get a prior block).

**Comment by kirk-baird** [comment]
This may cause issues when trying to target slots that are not the current.
For example:
`current_slot = 100` 
`target_slot = 50`
`BlockRootsIterator::new(target_slot)` will start counting down from `49` and skip the `target_slot`

Proposing a solution to:
Iterate backwards from `start_slot` (inclusive)
If `start_slot == state.current_slot -> return None`

This will involve putting `self.slot -= 1` at the end of `next()` rather than the beginning.
Adjustments will need to be made to existing calls to `BlockRootsIterator::new(target_slot)` and `BlockRootsIterator::owned(target_slot)` to `target_slot - 1`

**Comment by paulhauner** [comment]
You're right, it's unnecessarily strict. Good catch!

Looking foward to seeing the fix in your PR :)

**Comment by paulhauner** [comment]
Solved in recent PRs.
