### ISSUE TITLE
Update Client and documentation about working withdrawals

### ISSUE THREAD

**Issue by xtc0r** [sigp/lighthouse#4196]
## Description

When performing a volunteer exit lighthouse prints the following warning:

"WITHDRAWING STAKED ETH IS NOT CURRENTLY POSSIBLE"

Also in the lighthouse documentation it says:
"Even though users can currently perform a voluntary exit, they cannot withdraw their exited funds at this point in time."

## Version

v4.0.2-rc.0

## Present Behaviour

See Description

## Expected Behaviour

No more warnings about withdrawls as we are post shapella now.

## Steps to resolve

Update client and documentation.

**Comment by eserilev** [comment]
@michaelsproul I'd like to pick this up if thats ok

I can open a PR to remove the prompt: "WITHDRAWING STAKED ETH IS NOT CURRENTLY POSSIBLE"

in terms of updating the documentation, is that a separate repo? 

I think it might be helpful to mention in the documentation that in order to re-claim your 32ETH you must set your 0x01 withdrawl address

**Comment by chong-he** [comment]
> 
Thanks @eserilev 

Hi I am updating the documentation on voluntary exit, will also include the info on withdrawals.

Thanks again

**Comment by chong-he** [comment]
Resolved in #4207
