### ISSUE TITLE
Beacon API events SSE stream unexpected disconnections

### ISSUE THREAD

**Issue by Savid** [sigp/lighthouse#4245]
## Description

When connecting to the [`/eth/v1/events`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events/eventstream) event stream, clients will get unexpected disconnections from the lighthouse beacon node. Especially on the `attestation` topic for mainnet while subscribing all subnets.

## Version

Rust - `1.69.0 (84c898d65 2023-04-16)`
`unstable` - commit `7456e1e8faac7a581705f8e71b0dc4f09a36ee5c`
`stable` - commit `693886b94176faa4cb450f024696cb69cda2fe58`

## Present Behaviour

To replicate the current behaviour easily connect via curl;

```bash
curl "http://127.0.0.1:5052/eth/v1/events?topics=attestation" -H "accept: text/event-stream"
```

Eventually you'll get disconnected with the libcurl error;

```bash
curl: (18) transfer closed with outstanding read data remaining
```

If you want to speed this up run the beacon node with `--subscribe-all-subnets --import-all-attestations` flags on mainnet to have more attestation events published. With a "fast" machine you will get disconnected multiple times a slot.

## Expected Behaviour

Should not disconnect unexpectedly.

**Comment by michaelsproul** [comment]
I think this could be due to the channel filling up, and the stream being terminated by our error handling here:

https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/http_api/src/lib.rs#L3820-L3822

The broadcast receiver will return "lag errors" as described [here](https://docs.rs/tokio/1.28.0/tokio/sync/broadcast/index.html#lagging) when the channel fills up:

> If a value is sent when the channel is at capacity, the oldest value currently held by the channel is released. This frees up space for the new value. Any receiver that has not yet seen the released value will return [RecvError::Lagged](https://docs.rs/tokio/1.28.0/tokio/sync/broadcast/error/enum.RecvError.html#variant.Lagged) the next time [recv](https://docs.rs/tokio/1.28.0/tokio/sync/broadcast/struct.Receiver.html#method.recv) is called.

I think we could map these `RecvError::Lagged` errors into no-op events, maybe a comment that says ":dropped some events".

We could also set some more generous defaults for the channel capacity, which is currently hardcoded at 16 here:

https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/beacon_chain/src/events.rs#L7

Different capacities for different events would probably make sense, and a way to adjust them via the CLI (maybe an integer multiplier that applies to all channel capacities).

**Comment by michaelsproul** [comment]
Implementation of this fix should happen on top of https://github.com/sigp/lighthouse/pull/4462

**Comment by michaelsproul** [comment]
WIP PR for initial testing here: https://github.com/sigp/lighthouse/pull/4500

I haven't been able to get it to produce the `:error - dropped N messages` comment yet, but will run it for a few hours and see what happens

**Comment by Savid** [comment]
awesome, thanks. Just built an [image](https://hub.docker.com/layers/ethpandaops/lighthouse/xatu-sentry-channel-test-9f3c103/images/sha256-226a5ca5514f6e1390470e7b1306d35b9253f20bada2952ef4b28d00fc294ee5). Will roll it out to one of our mainnet sentries and let you know how it looks
