### ISSUE TITLE
Old mdbx-sys starting to become an issue on fresh/newer linux installs

### ISSUE THREAD

**Issue by DaveWK** [sigp/lighthouse#4354]
## Description

I noticed that on some of my fresh linux installs that the old version of mdbx-sys that is included by default no longer compiles correctly.. In the build logs I see:

```error: failed to run custom build command for `mdbx-sys v0.11.6-4 (https://github.com/sigp/libmdbx-rs?tag=v0.1.4#096da80a)`

Caused by:
  process didn't exit successfully: `/opt/src/lighthouse/target/maxperf/build/mdbx-sys-c3a9ecd0986e3970/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"MDBX_version_info_struct_(unnamed_at_/root/_cargo/git/checkouts/libmdbx-rs-c1b523f5b64ff08c/096da80/mdbx-sys/libmdbx/mdbx_h_611_3)" is not a valid Ident', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.58/src/fallback.rs:811:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...```

I believe this is due to more recent linux builds using a newer glibc version. I can work around this by doing:
```
CARGO_INSTALL_EXTRA_FLAGS="--no-default-features" FEATURES=slasher-lmdb,modern,jemalloc PROFILE=maxperf make
```

but wanted you to be aware that this was occurring. It seems like there's been some updates to mdbx (which still claims to support windows on newer versions?)

## Version
Any/all

**Comment by michaelsproul** [comment]
Thanks, we're aware of the issue. I've been mulling over the best way to deal with it. I think we have 2 options:

1. Deprecate MDBX and avoid building it by default. We can switch back to LMDB by default.
2. Update the MDBX bindings, possibly using work from the Reth devs (https://github.com/paradigmxyz/reth/pull/2703). This would retain Windows support and improve Linux distro compatibility. The note in our docs about Windows support being removed upstream was mostly to do with the old MBDX Rust bindings (from which Windows support was deleted), and statements from the MDBX author which I think he's now gone back on.

Option 1 would also remove the need for https://github.com/sigp/lighthouse/pull/4305 or https://github.com/sigp/lighthouse/pull/4305.

I have a slight preference for Option 1, because I'm personally sick of dealing with MDBX-related issues. But perhaps the pragmatic solution is Option 2 (or a combination of updating MDBX _and_ deprecating it).

**Comment by DaveWK** [comment]
Not sure if this is helpful or not , but did noticed this repo seems to be keeping up w/ the lmdbx revs: https://github.com/vorot93/libmdbx-rs  and according to #7 on the doc, it still has windows support: https://libmdbx.dqdkfa.ru/

**Comment by michaelsproul** [comment]
Those are the bindings we used to use. I added Windows to support to them, and Artem deleted the support in this commit https://github.com/vorot93/libmdbx-rs/commit/bd749c2d6c740eb9b5ab0c07140f2413723a18bb.
