### ISSUE TITLE
Slow proposer duties endpoint

### ISSUE THREAD

**Issue by anukul** [sigp/lighthouse#4396]
## Description

Benchmarking validator endpoints in the beacon API, noticed that the proposer duties endpoint (`/eth/v1/validator/duties/proposer/{epoch}`) is significantly slower on lighthouse compared to other nodes

## Version

Lighthouse/v4.1.0-693886b/x86_64-linux

## Present Behaviour

Slow response (100s)

I do see that other nodes (e.g. nimbus) also return a slower response (~20s) possibly until a cache is populated, but lighthouse is consistently slow.

## Expected Behaviour

Faster response, comparable to other consensus nodes (~1s)

**Comment by michaelsproul** [comment]
How old is the epoch which you're requesting duties for? I'm guessing it's quite old and you're hitting a historic state load, which can 60 seconds or more depending on your database configuration (see: https://lighthouse-book.sigmaprime.io/advanced_database.html).

We have a project to overhaul the database so that historic state queries are super fast with minimal disk usage (<150GB). Currently making them fast requires several TB of storage. You can read a bit about the database overhaul project here: https://github.com/sigp/lighthouse/releases/tag/v3.4.0-tree.1. There's currently no Capella-compatible release of this project, but we'll be releasing one in the next ~week.

**Comment by anukul** [comment]
Yeah I think your analysis is accurate, because it was an old epoch. Thanks! :)
