### ISSUE TITLE
Non Lighthouse peers dropped after checkpoint sync on 4844 devnet-7

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4532]
## Description

I noticed that after I checkpoint syncing on devnet-7, Lighthouse pretty much disconnect / ban most non lighthouse peers pretty quickly because peers aren't able to serve us `blob_sidecars_by_range` quick enough

2 Teku & 4 Lodestar peers get disconnected due to `Negotiation timeout`
Prysm peer rate limits us `RPC response was an error: The request was invalid with reason: rate limited`
And I ended up with only 5 peers (4 Lighthouse & 1 Teku).

I'm running with `--self-limiter=blob_sidecars_by_range:512/10`, slightly lower than our default `768/10`
https://github.com/sigp/lighthouse/blob/f1f04bc68a5506c839693d25bc8c626c48ec8669/beacon_node/lighthouse_network/src/rpc/methods.rs#L38

**Comment by jimmygchen** [comment]
Age suggested that this happens more on small networks with small number of peers. We could work around this by:
- Adding `--disable-peer-scoring` flag, so we don't disconnect / ban the peers when they time out
- Use a lower self limiting rate

**Comment by jimmygchen** [comment]
@realbigsean ^ I think we can probably close this given the comment above - it only happens on small testnets. 
Do you think it's worth applying some sort of self limiting at per-peer level? Probably not high priority but maybe something worth considering.

**Comment by realbigsean** [comment]
Yea I think we can close this in favor of this more general rate limiting issue: https://github.com/sigp/lighthouse/issues/4448

> Do you think it's worth applying some sort of self limiting at per-peer level

interesting thought, but doing it based on connected peers might not be the best way, because we have changed this numebr pretty drastically in the past, it's gone from 50 to 100 for example at default and we wouldn't have wanted to change leniency in these cases. There might be something there with basing it off of "peers seen" or "total network peers" because this gives us an idea of how many options for peers we have, and the more options we have the less lenient we can be in scoring
