### ISSUE TITLE
Unexpected `Unsupported endpoint version` on REST API

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#4620]
## Description

When sending an exit message for a validator that has already exited to `eth/v1/beacon/pool/voluntary_exits`, Lighthouse v4.3.0 returns:

```
{
  "code": 400,
  "message": "BAD_REQUEST: Unsupported endpoint version: v1",
  "stacktraces": []
}
```

The same call for a validator that hasn't been exited yet, succeeds.

## Version

`v4.3.0`

## Expected Behaviour

Send a `message` that is more descriptive of the actual error encountered

## Additional info

I have seen user reports of other REST calls that also fail with `Unsupported endpoint version` where a different message may be more appropriate.

**Comment by michaelsproul** [comment]
This was long-standing bug which we _finally_ fixed in https://github.com/sigp/lighthouse/pull/4595. Almost all occurences of it should be gone now, including from the POST endpoint for voluntary exits.

The original bug is here: https://github.com/sigp/lighthouse/issues/3404

The fix will be in our next release

**Comment by yorickdowne** [comment]
Excellent thank you!

**Comment by chaseadam** [comment]
I received this when I attempted to POST incorrect "Content-Type" to `/eth/v1/beacon/pool/bls_to_execution_changes` and also when attempting to incorrectly post to `/eth/v1/beacon/pool/bls_to_execution_change` (no s on the end).

What ended up working for me:
`curl -vvv --json @<JSON file> http://<BN HTTP>/eth/v1/beacon/pool/bls_to_execution_changes`
