### ISSUE TITLE
HTTP API Prevents Graceful Shutdown w/ Chrome

### ISSUE THREAD

**Issue by spble** [sigp/lighthouse#478]
## Description

With the inclusion of the `graceful_shutdown` function in the RESTful HTTP API, Lighthouse should properly shutdown on an interrupt such as `Ctrl+C`, however it does not.

## Present Behaviour

 1. Start the `beacon_node`
 2. Make a HTTP request to the API
 3. Shutdown the `beacon_node`
 4. `beacon_node` hangs indefinitely, until...
 5. Make another HTTP request to the API
 6. `beacon_node` exits.

## Expected Behaviour

 1. Start the `beacon_node`
 2. Make a HTTP request to the API
 3. Shutdown the `beacon_node`
 4. `beacon_node` exits.

## Steps to resolve

There are several issues on the hyper github which may assist in resolving this issue, these must be revised and a solution devised that is elegant and encompasses all of the client services (API, RPC, etc.).

e.g. https://github.com/hyperium/hyper/issues/1681

**Comment by paulhauner** [comment]
Note: this issue is only present when using Chrome to access the API. Using `curl` does not result in Hyper "hanging".

This leads me to believe that Chrome is keeping a connection alive and Hyper is acting correctly.

I still think we should leave this open until we figure out exactly what's going on with Chrome :)

**Comment by adaszko** [comment]
I take a look into this one.  Ping me if you have any additional information please.

**Comment by adaszko** [comment]
Turns out Chrome doesn't cause the Hyper HTTP server to hang.  The shutdown simply takes a bit longer with Chrome.

Here's how to the `^C` looks with Firefox:
![image](https://user-images.githubusercontent.com/165678/76073357-c7815b80-5f99-11ea-8b5a-d72d3bfc086c.png)

And with Chrome:
![image](https://user-images.githubusercontent.com/165678/76073400-d5cf7780-5f99-11ea-830a-b327a12c83ba.png)

It can be seen that [Chrome sends keepalives until it's connection timeout elapses](https://superuser.com/a/316453).  It's a separate confounding factor that Chrome has larger connection timeout settings than other browsers: 300 seconds compared to e.g. Firefox'es 90 (by default).

My opinion based on that is that the issue can be closed as there's nothing the built-in HTTP server does wrong.

**Comment by paulhauner** [comment]
Great, thanks @adaszko!

I'm confident in saying that this is expected and reasonable behavior and that this issue can be closed :)

**Comment by surya-prakash-susarla** [comment]
Hey folks, quick question, I have been trying to create a server which simply shuts down after a GET request is received (an OAuth response scenario) and I seem to be running into the same issue. Using hyper with Safari works perfectly but with Chrome I run into the issue above where the exit only happens after the second request is made. Can anyone suggest a workaround for this?
