### ISSUE TITLE
Rewards API: proposer rewards are incorrectly included in phase 0 attestation rewards

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4856]
## Description

[Attestation Rewards API specification](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Rewards/getAttestationsRewards)

While reviewing #4512, we noticed that **Phase 0** proposer rewards are being incorrectly included  as part of  `inclusion_delay`, which falls under attestation rewards. We know this because the attestation rewards tests below are passing without taking block rewards into account: 

https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130 
https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L171
https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L223

If we add block rewards to the validator balances, these tests will fail. 

Thanks to @zack-scott for working on Altair attestation rewards calculation and adding tests in #4807, which helped uncover this bug! ☺️ 

## Version

Lighthouse 4.5.0

## Present Behaviour

`inclusion_delay` in attestation rewards response incorrectly includes proposer rewards, which means the `total_rewards.inclusion_delay` could exceed `ideal_rewards.inclusion_delay` if the validator is a proposer in the epoch.

## Expected Behaviour

`inclusion_delay` in attestation rewards response should exclude proposer rewards amount.

## Additional Info

Some suggestions on fixing this:
- [Calculate block rewards](https://github.com/sigp/lighthouse/pull/4807/files#diff-1169096a7f174331a2c69819e18b6ede3d40f3951d539f6d6f0de38e01878b39R250-R257) in the tests and apply the rewards to validators balance, this should make the phase 0 rewards tests listed above fail.
- When calculating attestation rewards, we pass a `Vec` of validator indices to [`get_attestation_deltas_subset`](https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L86), which in turn calls the [`get_attestation_deltas`](https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L106) function to calculate attestation rewards delta. Note that this same function is also used by the consensus crate during state processing, and we currently use the following logic to decide whether to include validator delta for the rewards API:
https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L122-L127

The `include_validator_delta` function is then used to compute:
1. whether to include compute attestation rewards deltas for the validator
2. whether to add proposer rewards delta to the validator delta

This is fine for consensus state processing, however we should exclude the proposer rewards (2) above when calling this function from the rewards API. 

A nice suggestion from @michaelsproul is to replace the `maybe_validators_subset` `Option` here with an enum (e.g. `RewardsCalculationType` or a better name!), which contains `Consensus` and `API(&Vec<usize>)` variants, and always exclude proposer rewards if `rewards_calculation_type == API`.

https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L106-L111

**Comment by Gua00va** [comment]
I would like to work on this.

**Comment by Gua00va** [comment]
@jimmygchen, Is this reolved in #4807?

**Comment by Gua00va** [comment]
@jimmygchen, Why is ok to include inclusion delay in Consensus but not in thr Rewards API?

**Comment by zack-scott** [comment]
@Gua00va from what I understand, the inclusion delay is okay to include in Rewards API for Phase0. The issue is that the inclusion delay is also counting proposal rewards that you would see from the `/eth/v1/beacon/rewards/blocks/{block_id}` API.

The present behavior is:
`inclusion_delay` in attestation rewards response incorrectly includes `proposer rewards`, which means the `total_rewards.inclusion_delay` could exceed `ideal_rewards.inclusion_delay` **if the validator is a proposer in the epoch**.

The Phase0 reward test is passing at the moment without taking into account proposal rewards, which is wrong due to inclusion_delay double counting. One of the tests passing for Phase0 that shouldn't is below:
https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/tests/rewards.rs#L171


The Altair test I wrote for inactivity leak is taking into account the proposal rewards with the logic starting on the line below:
https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/tests/rewards.rs#L242

For the [Phase0 test](https://github.com/sigp/lighthouse/blob/unstable/beacon_node/beacon_chain/tests/rewards.rs#L171), we will need to take into account the proposal rewards similar to the Altair test, and we need to remove the proposal reward double counting in the `inclusion_delay` for Phase0.

**Comment by Gua00va** [comment]
Ahh, Got it!

**Comment by Gua00va** [comment]
Okay, so I have studied the whole issue and tried to understand it. Here is what I understood :

So in Phase 0, we have attestation rewards and proposer rewards. The problem here is that `inclusion_delay` is also including proposer rewards when we call this function : 
https://github.com/sigp/lighthouse/blob/d4f26ee123a3185b7e43b08dec69681265e1fde2/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L106
On the following line proposer rewards are being included 
https://github.com/sigp/lighthouse/blob/d4f26ee123a3185b7e43b08dec69681265e1fde2/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L165 

So the given tests are passing even though we have not included block rewards in them because if I compute block rewards and add it to the validator balances, the proposer rewards (_for including attestations from other validators_ in the case of "base") will be included twice.
Please correct me if I am wrong.

**Comment by zack-scott** [comment]
>So the given tests are passing even though we have not included block rewards in them because if I compute block rewards and add it to the validator balances, the proposer rewards (for including attestations from other validators in the case of "base") will be included twice.

@Gua00va yes, the above statement looks correct to me. 

I am quoting the original post from @jimmygchen that states the suggestion to fix this from @michaelsproul below:

> A nice suggestion from @michaelsproul is to replace the `maybe_validators_subset` `Option` here with an enum (e.g. `RewardsCalculationType` or a better name!), which contains `Consensus` and `API(&Vec<usize>)` variants, and always exclude proposer rewards if `rewards_calculation_type == API`.
> 
> https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs#L106-L111

**Comment by jimmygchen** [comment]
@Gua00va yep, seems like you're on the right track! 
Thanks @zack-scott for adding the details! 🙏

**Comment by Gua00va** [comment]
@jimmygchen, I have given it a try.

**Comment by Gua00va** [comment]
@jimmygchen, I have given it a try. Could you please review it. Thanks!!

**Comment by jimmygchen** [comment]
Fixed in #5101 🎉
