### ISSUE TITLE
Error responses from beacon rewards APIs

### ISSUE THREAD

**Issue by edwmurph** [sigp/lighthouse#4993]
## Description

the following 2 beacon api endpoints are returning error responses. i suspect it has something to do with my configuration but couldn't find any documentation that explains the problem

```
beacon1-0:/$ curl \
  --silent \
  -X 'POST' \
  'http://localhost:5052/eth/v1/beacon/rewards/attestations/247855' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '["<validatorindex>"]' \
  | jq
{
  "code": 404,
  "message": "NOT_FOUND: missing state at slot 7931423",
  "stacktraces": []
}
beacon1-0:/$ curl \
  --silent \
  -X 'GET' \
  'http://localhost:5052/eth/v1/beacon/rewards/blocks/<block>' \
  -H 'accept: application/json' \
  | jq
{
  "code": 404,
  "message": "NOT_FOUND: Parent state is not available! MissingBeaconState(<hex>)",
  "stacktraces": []
}
```

## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?

`sigp/lighthouse:v4.5.0-modern`

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

getting 404 errors

## Expected Behaviour

How _should_ the application behave?

200 responses

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

n/a

**Comment by michaelsproul** [comment]
You need to reconstruct historic states for access to old state data. The flag to do this is `--reconstruct-historic-states`. However, on `stable` Lighthouse, this will either be very slow or use a tonne of space (like multiple terrabytes). You can read about the tradeoffs here: https://lighthouse-book.sigmaprime.io/advanced_database.html

We have developed a better archive node on the `tree-states` branch, but it currently requires a re-sync. Seeing as you don't have an archive node yet and would need to wait a week to build one on stable Lighthouse, you may consider re-syncing with tree-states. There's a release here which explains in more detail: https://github.com/sigp/lighthouse/releases/tag/v4.5.444-exp. Although I would recommend building the current `tree-states` branch due to a recently fixed bug (we are planning a new release very soon, just waiting on some other bug fixes).

**Comment by edwmurph** [comment]
Thank you for the information that makes sense!

**Comment by chong-he** [comment]
Closing this issue as the question has been answered
