### ISSUE TITLE
Use `alloy` instead of `ethers_core` for decoding execution layer types

### ISSUE THREAD

**Issue by ethDreamer** [sigp/lighthouse#5207]
## Description

We currently use `ethers_core` in a few places to decode execution layer types. This crate is no longer maintained. But the reth team is maintaining another collection of crates under the name `alloy` to facilitate this functionality. We already use this for verifying the versioned hashes during optimistic sync. We should update the other locations as well.

**Comment by dospore** [comment]
Id be interested in putting a PR in for this issue

**Comment by michaelsproul** [comment]
@dospore Awesome, thanks! You should probably base your work off https://github.com/sigp/lighthouse/pull/4832 (or wait until it merges to unstable)

**Comment by dospore** [comment]
@michaelsproul making progress on this. Have a PR more or less ready to go working off #4832. Just needed some help with whats the best path with serialising. Since ethers_core::types::Transaction is serialisable but the alloy type (TxEnvelope) which is used in the linked pr is not. I can write a wrapper struct that converts from [TxEnvelope](https://github.com/alloy-rs/alloy/blob/main/crates/consensus/src/transaction/envelope.rs) into a serialisable type but thought id ask for some clarification first. Since there is also [this Transaction type](https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types/src/eth/transaction/mod.rs) which matches the current ethers_core Transaction but it is not [RlpDecodable](https://docs.rs/alloy-rlp/latest/alloy_rlp/trait.Decodable.html) which it will need to [decode the raw tx here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/execution_layer/src/engine_api.rs#L219)

**Comment by michaelsproul** [comment]
Closed by

- #5301

:tada:
