### ISSUE TITLE
When Enabling Checkpoint Sync, Restarting Lighthouse Disables Checkpoint Sync

### ISSUE THREAD

**Issue by JamesCropcho** [sigp/lighthouse#5342]
## Description

Given a deployment where checkpoint sync is turned on, issuing a 'restart' to Lighthouse disables checkpoint sync.

#### Output of `lighthouse --version`

```
Lighthouse v5.0.0-b5bae6e
BLS library: blst-modern
SHA256 hardware acceleration: true
Allocator: system
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (false)
```

#### Command Issued for Building
```
PROFILE=maxperf RUSTFLAGS='-C target-cpu=native' FEATURES="modern" make
```

#### Output of `rustc --version`

```
rustc 1.76.0 (07dca489a 2024-02-04)
```

## Steps to Reproduce

1) Provision a fresh/empty `datadir` for Lighthouse
2) Create a new Lighthouse service whose configuration includes the following elements:

```
--datadir /var/lib/lighthouse [fresh/empty datadir]
--prune-payloads false
--checkpoint-sync-url https://mainnet.checkpoint.sigp.io
--disable-backfill-rate-limiting
```
3) Start Lighthouse service

**Output**: Lighthouse's log will include the following:

```
INFO Starting checkpoint sync                remote_url: https://mainnet.checkpoint.sigp.io/, service: beacon
INFO Loaded checkpoint block and state       block_root: 0x8d20a5eb0ef41d77790e31e0c007709647537757320bf9f63a51ba2e0f080e4e, state_slot: 8547552, block_slot: 8547552, service: beacon
INFO Beacon chain initialized                head_slot: 8547392, head_block: 0x20eb…2202, head_state: 0x9bfb…34bc, service: beacon
```
…
```
INFO Downloading historical blocks           est_time: 9 hrs 45 mins, speed: 29.33 slots/sec, distance: 1030976 slots (20 weeks 3 days), service: slot_notifier
```

4) Restart Lighthouse service

**Output**: Lighthouse's log will include the following:

```
INFO Refusing to checkpoint sync             msg: database already exists, use --purge-db to force checkpoint sync, service: beacon
INFO Starting beacon chain                   method: resume, service: beacon
INFO Beacon chain initialized                head_slot: 8547760, head_block: 0x3110…8635, head_state: 0xf0a8…11df, service: beacon
```
…
```
INFO Sync state updated                      new_state: Syncing Historical Blocks, old_state: Synced, service: sync
INFO Sync state updated                      new_state: Synced, old_state: Syncing Historical Blocks, service: sync
INFO Sync state updated                      new_state: Syncing Historical Blocks, old_state: Synced, service: sync
```
…
```
INFO Downloading historical blocks           est_time: 8 hrs 31 mins, speed: 33.33 slots/sec, distance: 1022976 slots (20 weeks 2 days), service: slot_notifier
```

**Output**: Disk usage:

The `datadir` disk usage will quickly grow to several gigabytes (and presumably much larger). This is in contrast to a deployment whose configuration includes `--purge-db`. Such a deployment will always checkpoint sync, _however_ upon restarting the service, the backfill sync will resume from the initial distance (in other words, Lighthouse is not saving the historical blocks; the backfill sync always starts from scratch).

## Expected Behaviour

I would like to be able to use checkpoint sync _while_ persisting the historical blocks backfill progress across restarts.

**Comment by michaelsproul** [comment]
Checkpoint syncing while retaining the historic blocks is not a straight-forward change to make, and IMO not worth it on the complexity-benefit tradeoff. I'll explain:

When you checkpoint sync, Lighthouse tracks a single range of unknown historic blocks between `0..oldest_block_slot`. You can see the `oldest_block_slot` in `curl http://localhost:5052/lighthouse/database/info`. Essentially Lighthouse knows that there is a single "gap" in its knowledge of historic blocks and downloads backwards from `oldest_block_slot` until it either reaches 5 months of backfill (default) or slot 0 (if using `--genesis-backfill`). The `oldest_block_slot` is part of Lighthouse's on-disk database and is persisted between restarts.

If we were to support re-syncing with checkpoint sync while retaining historic blocks, then Lighthouse would need to support an arbitrary number of open intervals that are lacking blocks, i.e. we would have to download blocks in `0..a`, `b..c`, `d..e`, etc. Every time Lighthouse were restarted with checkpoint sync it could potentially create a new gap. To make this work would require changing:

- The on-disk database schema, so that it could keep track of a `Vec<(Slot, Slot)>` for the gaps.
- The backfill sync logic, so that it is multi-gap aware and doesn't try to re-download blocks that are already stored.

This isn't impossible to do, but it would require substantial engineering & testing work which IMO would be better spent elsewhere.

I also think the feature of re-checkpoint syncing while retaining historic blocks is of limited utility because:

1. If Lighthouse is offline for only a short time then there is no need to checkpoint sync: you can re-sync to the head in a few minutes using regular forwards sync.
2. Therefore the feature would only be useful in cases where Lighthouse is shutdown for a long period (24h+ to multiple days). In this case, regular sync will catch back up in a few hours most likely, or maybe a day at max, which as a proportion of the time offline is not particularly significant. Further, if the node is relied on by validators or for HTTP infrastructure, then the operator is incentivised to prevent nodes going offline for multiple days in the first place. If the nodes are the sole BNs of some validators, then they really should not be shutdown for multiple days. If they are backup BNs, then the re-sync time for forwards sync can probably be tolerated while the primary BNs continue to take the production workload (as they have been already for 1+ days while the backup BNs were offline). Or, they can re-sync with checkpoint sync and re-do a little bit of work re-doing backfill.

The other way to address the pain point of re-syncing without checkpoint sync is optimising sync speed. This has many benefits across the whole client rather than just covering one obscure case, and would be a better use of our engineering efforts & code complexity budget.

Let me know if you disagree. I'm interested to know why you've encountered multiple instances where re-checkpoint syncing & retaining blocks would be useful.

**Comment by JamesCropcho** [comment]
I'm grateful for the thorough response, Michael.

No, I do not disagree, having closely read your arguments.

> I'm interested to know why you've encountered multiple instances where re-checkpoint syncing & retaining blocks would be useful.

Certainly: I encounter "cases where Lighthouse is shutdown for a long period (24h+ to multiple days)" when I am restoring a beacon node—or creating a new one—and starting from a semi-recent disk volume snapshot (in realm, of being, say 90 days behind).

But again, to clarify: I can totally see how it would be not worth it to add this capability, given your exposition.
