### ISSUE TITLE
Geth port isn't freed after stopping a local testnet

### ISSUE THREAD

**Issue by danielrachi1** [sigp/lighthouse#5382]
## Description

`stop_local_testnet.sh` and `clean.sh` fail to properly stop all geth instances. Causing the port to remain busy after restarting the local testnet, which prevents new testnets to run until all geth processes are killed manually.

## Version

Branch: `unstable`
Version: `v5.0.0-f93844e`

## Present Behaviour

1. Go to `scripts/local_testnet/` and run `./start_local_testnet.sh genesis.json`
2. Wait for the script to finish and run `tail -f ~/.lighthouse/local-testnet/testnet/geth_1.log`
3. After a small wait, the testnet will start advancing:
    ![image](https://github.com/sigp/lighthouse/assets/67139425/e47ad400-bddf-4cb4-bfb7-f52b0b084e4e)
4. Re-start the testnet by running `./start_local_testnet.sh genesis.json` again. (`stop_local_testnet.sh` and `clean.sh`) are part of this script.
5. Wait for the script to finish and run `tail -f ~/.lighthouse/local-testnet/testnet/geth_1.log`
6. The geth instances will fail to start because their ports will be busy:
    ![image](https://github.com/sigp/lighthouse/assets/67139425/f5aeac4d-7f26-44fe-bc9b-51f8e0543942)
7. Run `./stop_local_testnet.sh && ./clean.sh`
8. Run `htop` and search for `geth`. A bunch of geth processes will still be running:
    ![image](https://github.com/sigp/lighthouse/assets/67139425/99ed5f07-8499-4531-a379-587de0d7bb9b)
9. Kill the geth processes manually.
10. Run `./start_local_testnet.sh genesis.json` again. Now the testnet will start with no issues:
    ![image](https://github.com/sigp/lighthouse/assets/67139425/a162a073-8c8a-47d2-b163-c3a939a2d443)

## Expected Behaviour

In step 4 a new testnet should be started with no issues. Also, `./stop_local_testnet.sh && ./clean.sh` should kill all geth processes.

**Comment by chong-he** [comment]
~~In Step 4, when you restart the testnet, you will need to stop the testnet properly: `./stop_local_testnet.sh` and then run `./start_local_testnet.sh genesis.json`. Otherwise it is like you are trying to start another instance of testnet (geth and lighthouse which are already running) , it will fail as the error you show in Step 6.~~

~~If you run `./stop_local_testnet.sh`, all processes would be stopped properly. This can then be followed by a `./start_local_testnet.sh genesis.json`.~~


Edit: let me look further as the `./start_local_testnet.sh genesis.json` contains the stopping as well. I will get back later

Update: This is due to the change in `geth.sh` in #5137 that modifies the script to enable logging for geth. This may not be necessary as we already save the logs for `geth` in `./start_local_testnet.sh genesis.json` . The logs are in ` ~/.lighthouse/local-testnet/testnet/geth_1.log` (and geth_2 etc)

If you remove this line: 
https://github.com/sigp/lighthouse/blob/10a38a8aae8b4d1b9665828cefabd2e2c534b8b9/scripts/local_testnet/geth.sh#L54

and the backlash `\` in the previous line (line 53), then the script will work.

Hope this clarifies

**Comment by danielrachi1** [comment]
That fixed it, thanks!

Just updated #5383

**Comment by chong-he** [comment]
Closed by #5383
