### ISSUE TITLE
beacon data dir size is too big for goerli

### ISSUE THREAD

**Issue by andkom** [sigp/lighthouse#5490]
## Description

beacon data dir is too big for **goerli**:

beacon: 1.2TB
geth: 0.533TB

but for **mainnet**:

beacon: 0.392TB
geth: 1.4TB

is it possible to optimize somehow?

## Version

Lighthouse/v4.0.1-a53830f

## Present Behaviour

beacon client takes more disk space for goerli then for mainnet

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
Goerli is in a bad state at the moment. Stable Lighthouse needs tonnes of disk space due to the non-finality and the number of forks. The [`tree-states` releases](https://github.com/sigp/lighthouse/releases/tag/v5.1.222-exp) use less space but run out of memory.

We're doing some work on reviving it and optimising the client so that it can handle these sorts of adverse conditions. Until that's done, there's no workaround apart from adding more disk, more CPU, more RAM. It's not ideal, I know.

**Comment by michaelsproul** [comment]
Sorry I didn't mention the most important thing: Goerli is deprecated, so unless you want to get involved in the resuscitation effort, better to move to Holesky.

**Comment by andkom** [comment]
switched to sepolia:

geth: 248 GB
beacon: 46 GB
