### ISSUE TITLE
Ask for help！！！   peers:0

### ISSUE THREAD

**Issue by yootou** [sigp/lighthouse#5763]
May 10 23:50:17.013 INFO Searching for peers                     current_slot: 9046749, head_slot: 9045375, finalized_epoch: 282666, finalized_root: 0x871d…c203, peers: 0, service: slot_notifier

Peers is 0. Is there any way to specify a stable peers list?

**Comment by dapplion** [comment]
Hey @yootou could you provide more details on your setup?
- If possible share the full command with what you are running lighthouse or all its options
- What network are you running? Mainnet, local devenet, etc
- Are you specifying a custom set of bootnodes?
- Is this node running in the cloud or a local machine?

**Comment by yootou** [comment]
lighthouse bn --network mainnet --execution-endpoint http://localhost:8551 --execution-jwt d:/ethereum/ethdata/geth/jwtsecret --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --http --datadir=d:/ethereum/lighthouse --genesis-backfill

This node is running on the local computer. There are no custom boot nodes. How to set up a custom boot node? I did not see the parameters in the configuration file in the official documentation. Thank you, @dapplion

**Comment by AgeManning** [comment]
The parameter you are chasing is `--boot-nodes`. A list of the documentation can be found here: https://lighthouse-book.sigmaprime.io/help_bn.html

However, we already have hardcoded quite a few boot nodes, so I think it's very unlikely that you cannot connect to any of them. The issue is going to be with your network I'd imagine. You need to be able to send/receive traffic on ports 9000 tcp/udp at a minimum. 

I'd check your local computers firewall and then the router and make sure these ports are port-forwarded.
