### ISSUE TITLE
Unnecessary saturating_sub in shuffler

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#59]
https://github.com/sigp/lighthouse/blob/7995200903e42d3a5e4a933d7f90278a6568abb4/beacon_chain/utils/vec_shuffle/src/lib.rs#L32

Underflow impossible due to `if list.is_empty()` check above. Remove `saturating_sub()`.

**Comment by mjkeating** [comment]
A couple of questions:

1. Was an underflow really possible 'in an empty list' here? The code directly above looks for an empty list and returns OK if one is found. Perhaps using `saturated_sub()` is good practice in any case since it doesn't rely on such checks.
2. This shuffler now seems to live in util/vec_shuffle where the change to `saturating_sub()` has been made. Did we want to make this change elsewhere as well? I noticed there are a few other places that `vec.len() - 1` is being used - although the logic may ensure a non_empty vector.

**Comment by paulhauner** [comment]
Oh, it looks like this issue may have been outdated. Sorry! Looks like there's a bit of conflict between my change and @pinkiebell's change.

You're correct, this crate was moved and is now called `vec_shuffle`.

I prefer to only use saturating math where it's necessary. It's not so much that it's slower, it's more to avoid the scenario where one thinks they can not think deeply about integer wrapping because "if we use saturating it's safe". We could cause consensus issues by leaning on saturation too heavily.

In this case, it's impossible for that subtraction to underflow, so lets drop the `saturating_sub`. I'll update the issue :)

Thanks for point this out!

**Comment by paulhauner** [comment]
Fixed in #72 :)
