### ISSUE TITLE
local-testnet persistency

### ISSUE THREAD

**Issue by lzmrd** [sigp/lighthouse#6123]
## Description

I'm trying to setting up a private network, using this repo as starting point. I can start it up with the command `./start_local_testnet` but when I stop it I loose all the data. I need my data to be persistent. 

## Version

Lighthouse v5.1.3-3058b96+
Rustup: 1.27.1 (released on April 24, 2024)
Rustc (Rust Compiler): 1.78.0 (released on April 29, 2024)
Geth
Version: 1.14.3-stable
Git Commit: ab48ba42f4f34873d65fd1737fabac5c680baff6
Git Commit Date: 20240509
Architecture: amd64
Go Version: go1.22.3
Operating System: linux

**Comment by michaelsproul** [comment]
we don't provide support on running your own chain or private networks, you'll have to figure it out

**Comment by lzmrd** [comment]
Ok, but why?? I thought that Web3 mood was to share knowledge. U can work on closed source projects if you prefer @michaelsproul

**Comment by michaelsproul** [comment]
you don't have any entitlement to my time and effort

**Comment by lzmrd** [comment]
Yeah bro, but calm down. I haven't tagged your profile. I don't even know who you are! I've just opened an issue, like anyone else would. If you don't want to answer, it doesn't mean no one else will. I really can't understand your behavior.

**Comment by michaelsproul** [comment]
I'm sorry for responding harshly. We get a lot of people showing up and wanting help running private networks, and we (SigP Lighthouse devs) have adopted a policy of not helping in these cases because:

1. It is very time consuming to debug private networks, especially once the author starts making changes beyond what our scripts do.
2. Helping people debug their private networks deprives them of the skills they'll need to maintain it once it's running. If you are launching a new blockchain based on Lighthouse you need to be able to dig into the code and solve problems for yourself.
3. Unless the private network is stress-testing Lighthouse or the protocol, it is of little of value for Ethereum.

Your specific question about persisting data is the sort of thing that I don't think is useful to us when testing, and is _only_ useful for running private networks.

The v5.1.3 local testnet scripts are also completely unsupported since we merged this PR to simplify maintenance:

- https://github.com/sigp/lighthouse/pull/5865

You could check out the new scripts, which are based on Kurtosis, and see if you can get something that suits your usecase.

**Comment by lzmrd** [comment]
Ok, now I understand your point and it makes sense. Thank you for explaining.
