### ISSUE TITLE
Slot timer printing "inf" and "NaN"

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#687]
## Description

The [notifier](https://github.com/sigp/lighthouse/blob/master/beacon_node/client/src/notifier.rs) is printing things like this:

```
Dec 10 00:24:30.035 INFO Syncing                                 distance: 15663 slots (2 days 4 hrs), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 4, service: slot_notifier
``` 

There must be something off with the float math here, my bad.

**Comment by pawanjay176** [comment]
Happens when head_slot doesn't change over intervals. 
The `speedo` accumulates `(head_slot, instant)` with same `head_slot` for different instants.
So the distance calculation here `slots_per_second` function returns 0.0 we get a `Vec<f64>` of zeros.
https://github.com/sigp/lighthouse/blob/e4c56e6c5c929a3112c4a08852be54345b0acc0a/beacon_node/client/src/notifier.rs#L269-L279

Hence, the function returns `Some(0.0)` and `est_time` returns `inf`.
We can fix this by returning `None` if `sum == 0`.
