### ISSUE TITLE
Arm7 support (Raspberry Pi 4 32bits)

### ISSUE THREAD

**Issue by diglos** [sigp/lighthouse#706]
Hi

Lighthouse compiles on Raspberry Pi 4 (Raspbian distro is still 32bits) but throws an error message:

```
CRIT Lighthouse only supports 64bit CPUs     detected: 32bit
Failed to start Lighthouse: Invalid CPU architecture
```

Is there any way of getting support for ARM7?

Thanks!

**Comment by paulhauner** [comment]
Hi, sorry @diglos we're not planning to support 32bit at the moment.

For the Pi4, there are some 64bit Linux distros out there. I have used Manjaro with success in the past.

I will close this for now, thanks for bringing it up though.

**Comment by michaelsproul** [comment]
Amongst the reasons that 32-bit support is a bit involved are:

* For simplicity, it's nice to assume that `usize`s are 64 bits. The spec uses a lot of `u64`s as indexes into vectors, lists, etc, and they inevitably end up getting converted to `usize`s. Changing this in Lighthouse would require very careful consideration of all the places where conversions between the two are made (possible, but not a priority right now).
* We're experimenting with [LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database) as a possible on-disk database. It uses memory mapped files to represent the entire on-disk database as virtual memory, which only really works on 64-bit+ machines, because the 4GiB of address space afforded by 32-bit architectures isn't enough to represent the entire database _and_ the rest of the process's memory.

**Comment by diglos** [comment]
Hi.
Understood, thanks for the response.
I'm afraid I can not maintain an image just for one client so in the Eth on ARM images I'll include Prysm and Nimbus for Raspberry 4 and Prysm, Nimbus and Lighthouse for ARM64 (NanoPC-T4 and RockPro64).
Thanks again!
