### ISSUE TITLE
Eth1 block/genesis cache issue

### ISSUE THREAD

**Issue by Buttaa** [sigp/lighthouse#711]
![image](https://user-images.githubusercontent.com/26490734/70664891-a1367300-1c6b-11ea-8c22-5265a2b4df49.png)

**Comment by paulhauner** [comment]
Hi @Buttaa, presently you're connected to our public Goerli node and it appears to be experiencing some congestion (it is also in Sydney, so there might be some lag).

We will look into providing additional public nodes, however you can run your own eth1 node to solve this issue (this is in fact preferred, otherwise our servers provide a point of trusted centralization).

Here's the command we run on our node:

```
geth --goerli --rpc --gcmode=archive --syncmode=full
```

**Comment by AgeManning** [comment]
Marking resolved. Known issue and workaround given.
