### ISSUE TITLE
Document the need to open port 9000

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#730]
I had to open port 9000 (for both TCP and UDP traffic) on my router for synching to start.

**Comment by AgeManning** [comment]
This shouldn't be necessary. Regardless of whether you are behind a NAT or not, you should be able to connect to any peer who has their ports open. 

I think this may have occurred whilst the main peers were struggling with disk space (due to another crash) and were not responding to your RPC requests. 

In the future, you don't need to port forward these ports, although it is required if you want other peers to discover and connect to your node.

**Comment by JustinDrake** [comment]
Ok, I'll try again soon :) What I observed on Sunday was pretty binary:

* port 9000 closed—sync speed of 0.00 slots per sec
* port 9000 open—sync speed >0.00 slots per sec
