### ISSUE TITLE
Lighthouse fails to start with `testnet` and specific `datadir`

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#767]
## Description

Setting up a local testnet with the `testnet quick` sub-commands and trying to persist a custom `datadir` will fail due to the directory already existing. 
https://github.com/sigp/lighthouse/blob/master/beacon_node/src/config.rs#L397

I believe we want to be able to resume clients with the same custom datadir ?

**Comment by paulhauner** [comment]
The `testnet` command is for creating a _new_ datadir, not for resuming.

Once you've created a datadir using `lighthouse bn testnet ...`, you can just resume using `lighthouse bn`. The help menu is specific that it's for creating a _new_ datadir:

https://github.com/sigp/lighthouse/blob/55680ab1d34ea7001df32573dd96277486331b21/beacon_node/src/cli.rs#L214

Feel free to add some extra help text if you want.

**Comment by AgeManning** [comment]
Fair enough.

**Comment by paulhauner** [comment]
FYI, the reasoning behind have `testnet` be create-only is that if you want it to also resume, then you probably want to check that the values supplied are the same as what it was created with (e.g., genesis time, validator count, etc). Otherwise you end up thinking you have `testnet quick 12 1234` but you're actually running `testnet recent 100` from a few days ago.

Checking that the parameters are the same involves loading the beacon state from disk and analyzing it before booting and this is not already in our flow. In other words, it requires non-trivial logic that only applies to testnets.
