### ISSUE TITLE
Potential memory exhaustion vector

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#800]
## Description

In `per_block_processing` we store a list of intermediate states when fast-fowarding a state through skip slots:

https://github.com/sigp/lighthouse/blob/03443c3e5714ae5478173de4a87f92a1c9577549/beacon_node/beacon_chain/src/beacon_chain.rs#L1364-L1378

Given that each state is on the order of MB (they're ~5mb when SSZ encoded, not sure what they consumer when in RAM) there's an attack here to force us to skip forward more blocks than we can keep in RAM.

## Suggestions

1. Enforce a max-skip slots value. This was found to be annoying in testnets, so perhaps we allow it to be disabled at run-time.
2. Store the blocks in the DB as we go, and unwind if we encounter an error.

I'd probably lean towards a combination of the both. (2) still has a DoS vector that we can fill up a filesystem, but we can fit _many_ more states in the DB than in RAM because there's more memory and there is compression\efficiency when storing in the DB that is not present in RAM.

**Comment by pscott** [comment]
Should we also maybe provide a way for the user to set this `max-skip slots value`?
Or should we just set this number to be very low? Thinking about the user who has a small droplet that has 1GB RAM and that might find it useful to provide a smaller `max-skip slots value`

**Comment by paulhauner** [comment]
> Enforce a max-skip slots value. This was found to be annoying in testnets, so perhaps we allow it to be disabled at run-time.

This has already been implemented.

**Comment by paulhauner** [comment]
A potential solution is to create another column in the database for "temporary states".

If we get a block with more than `STATE_SKIP_THRESHOLD`, instead of keeping the state in memory we write them into the temporary states column. After we've verified the block, we move the temporary states in to the real database.

The purpose of the temp states column is to avoid writing unverified states into the "real database".

Note: we would need to think about to make the moving from temp states to real states an atomic operation.

**Comment by michaelsproul** [comment]
That’s a good point... I wonder if we used a database with “real transactions” (like LMDB) whether this would even require any more work than just using a transaction... 🤔 As far as I understand LMDB uses memory-mapped pages which get auto flushed to disk when the OS sees fit. Whether or not it would flush them to disk before the transaction commits is something we’d have to check

**Comment by michaelsproul** [comment]
Ok, LMDB is not a silver bullet 😅 I ran a test writing 20GB in one transaction and it OOMed instantly, obliterating my whole session.

Manually implementing temp states, or having a flag on states like `confirmed: bool` seems like a workable solution. Even using LevelDB we would be able to atomically update a batch of states from `confirmed: false -> true`

**Comment by paulhauner** [comment]
> having a flag on states like confirmed: bool seems like a workable solution. 

This is elegant from an atomic perspective but it's a breaking schema change. We could probably write a migration script *fairly* easily.

**Comment by michaelsproul** [comment]
I think the temp state flag would need to be in a completely separate column from the states in order to allow atomic updates, and this would also simplify migration.

I thought about atomicity some more and realised that:

1. If the temp states are stored as whole states in their own column, then we have the same memory-exhaustion problem as now when it comes to atomically moving them, i.e. you'd have to load all the temp states into memory, create a WriteBatch, and commit that.
2. Using an object like `{state: BeaconState, confirmed: bool}` is no better, because LevelDB only allows writes and not mutations, so we'd have to load the whole object just to change `confirmed: false -> true`.

The separate column design meanwhile would look something like:

* During intermediate state storage, atomically write:
    1. The state into the regular states column (if it doesn't already exist*)
    2. A marker value into a new "temp states" column. This value doesn't need any content, and is stored under the state root as a key (i.e. mapping `state_root => ()`).
    3. When the block is processed, commit one of two transactions:
        1. Success: atomically delete all stored state roots from the temp states column
        2. Failure: atomically delete all (new) stored state roots from the temp states column, _and_ their corresponding states (on `drop`).
* During _all_ state loads:
    1. Check if the state root corresponds to a temp state: if it does, return `None`
    2. Load the state as normal from the regular states table

*There are some complications around what to do if a state already exists a) as a confirmed state or b) as an existing temp state. Need to think about it some more.

We may also need some sort of garbage-collection process to delete temp states (on startup?). Although that may not be necessary if the normal deletion process removes most of them.

**Comment by michaelsproul** [comment]
I'm coming round to the idea of the garbage collection of temp states as the _only_ way to delete states created as temporary. Otherwise two threads could race, and if one reverts, it might delete a state required by the other. A flow something like:

1. Thread 1 atomically stores state `s` and flag `s_temp`.
2. Thread 2 wants to store `s`, but seeing it there already just stages the deletion of `s_temp` later
3. Thread 1 errors, and commits the "on drop" revert transaction -- deleting `s` and `s_temp`
4. Thread 2 succeeds, re-deleting `s_temp`. However, the state that it wanted stored, `s`, is also gone :frowning: #rekt

With the garbage collection approach, we just leave the temp states there if the block import fails, and they either get cleaned up by future blocks which make them non-temporary, _or_ at startup by iterating through the temp states column and deleting all the entries and their corresponding states (_before_ allowing any block importer to start running in parallel).

All this concurrency has me like :exploding_head:
