### ISSUE TITLE
Many documentation links broken

### ISSUE THREAD

**Issue by thor314** [sigp/lighthouse#821]
## Description
All of the links in the documentation in all sections not named “Re-exports” are broken.
https://lighthouse-docs.sigmaprime.io/

## Present Behaviour
Click a link, any link, 404 not found, you will find.

## Expected Behaviour
Documentation links to content

## Steps to resolve
Probably find where the links were supposed to point, update the links.

**Comment by johnsBeharry** [comment]
Just checked out the docs and the links I clicked seem to be working.
Could you include which urls specifically are returning 404?

**Comment by johnsBeharry** [comment]
@thor314 the links actually work and do not 404, they are anchors to sections of the current page.

**Comment by michaelsproul** [comment]
I reproduced this by clicking the link to "builder" under the "Modules" heading, which leads to:

https://lighthouse-docs.sigmaprime.io/builder/index.html (404)

Rather than:

https://lighthouse-docs.sigmaprime.io/beacon_chain/builder/index.html

It's probably an HTTP configuration issue, we'll look into it.
