### ISSUE TITLE
BooleanBitfield test failing

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#86]
## Description

I have created a test for BooleanBitfield that I think should pass, but fails.

https://github.com/sigp/lighthouse/commit/bedc1abec00ef72f57b447c0136937cc39bf5232

## Present Behaviour

Test fails

## Expected Behaviour

I think this test should pass

## Steps to resolve

I haven't looked into how to resolve it.

**Comment by ralexstokes** [comment]
i'll take a look

**Comment by ralexstokes** [comment]
@paulhauner will push a fix shortly -- this led me on a journey to see what the canonical impl does after seeing that the parity impl does something different (serializes bytes w/ length, which imo is preferred)

the bug here comes down to not extending the bitfield long enough as it stops at the highest set bit. we need to set any `ssz-deserialized` bitfield to the maximum length of the bytes (in bits) to get the correct roundtrip behavior
