### ISSUE TITLE
Ensure Sync aligns on epoch boundaries

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#908]
## Description

Doing batched block downloads can be processed faster if the batch aligns to an epoch. From memory, this should naturally be the case for Finalized chain sync (provided the `BLOCKS_PER_BATCH` is a multiple of `slots_per_epoch`). 

This issue, is to ensure that when a finalized chain is created, the batches always align to an epoch. 
There is potentially an edge case when finalized chains switch (i.e more peers exist on a new finalized chain) and sync swaps to the new finalized chain. The new chain continues from where the old one left of, however it may be the case that this is no longer aligned to an epoch. 

We need to make sure that when resuming or starting a finalized chain, we always start from an epoch boundary. If the resumed chain has some portion of an epoch worth of blocks downloaded, we should download the rest of the epoch, then continue from the next epoch. 

Note: This logic is all contained within `Network::sync::range_sync`

Further info given upon request

**Comment by divagant-martian** [comment]
I'll take this one

**Comment by AgeManning** [comment]
All yours

**Comment by AgeManning** [comment]
@divagant-martian - Is there anything to report on this one?

**Comment by divagant-martian** [comment]
Hi!, here is my take on the matter:

First, I wasn't able to make it fail _properly_ (I'll explain). I asked @paulhauner for steps to reproduce a scenario where things could get misaligned, but he said this was more of a "I might be happening" thing, so I took his suggestion of playing with the sync sim.

What I did was run the sync sim several times (all strategies) and check that the boundaries of the epochs in which each slot (start and end) fall are consistent with these slots. So concretely, that: 
```rust
batch_start_slot.epoch(slots_per_epoch).start_slot() == batch_start_slot
``` 
and
```rust
batch_end_slot.epoch(slots_per_epoch).start_slot() == batch_end_slot
```
Last one is the start slot of the epoch since the `end_slot` is not inclusive.

With `BLOCKS_PER_BATCH = 64` as in v0.2.0, instead of 50 (current value in master, which needs to be changed) they are consistent _as long as this batch is not the last one_ (thus the _properly_ above)

In the case of last batches, (I think) it makes sense to have them misaligned but not sure if it makes sense to have a batch in the first place. Some examples of things I got: 

```bash
batch_start_slot = 384
batch_end_slot = 385
target_head_slot = 384
# we just want to request one block
-----
batch_start_slot = 360
batch_end_slot = 393
target_head_slot = 392
# I think this one is ok?
```
All failures are on final batches, so: 
- If these failures (batches in which the `target_head_slot` falls between the start of the batch and the would-be-end) are admisible, I think this is ok. `BLOCKS_PER_BATCH` still needs to be changed tho.
- If the batch should request blocks from slots beyond the `target_head_slot` then I think an improvement would be to change `BLOCKS_PER_BATCH` to `EPOCHS_PER_BATCH` and have each batch have a `start_epoch` and a number of `requested_epochs >= 1`. From what I understand, this is what is actually intended for most batches and this way if `slots_per_epoch` changes (no idea if this happens often) sync would still be consistent

What do you think?

**Comment by AgeManning** [comment]
Hey awesome. 
This sounds good to me. The case I was worried about off the top of my head, was when we switch to a higher priority (more peers) chain.
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/network/src/sync/range_sync/chain_collection.rs#L206
We stop and start chains in this case: 
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/network/src/sync/range_sync/chain_collection.rs#L257

The start function should update the chain to already downloaded blocks:
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/network/src/sync/range_sync/chain.rs#L528

However after just skimming this it looks like we don't update the chain with the `local_finalized_slot` and simply start the chain again from scratch (woops). Unless I'm mistaken we should have a line in there that changes the `self.start_slot` to `local_finalized_slot`. 
My concern was that `local_finalized_slot` might not lie on an epoch boundary. But it seems that it should right?

Could you confirm this is a bug and update it so the chain updates. I think we would also update the logs. It looks to me that `chain.start_slot` should be replaced with `local_slot` in these lines:
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/network/src/sync/range_sync/chain_collection.rs#L244
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/network/src/sync/range_sync/chain_collection.rs#L248
