### ISSUE TITLE
Limit Block size by block producer

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#978]
## Description

The network is only allowed to transmit blocks that have a maximum SSZ size of 1MB. 

Rather than having our block producer produce arbitrarily sized blocks then have our network stack reject them, we should add logic to the producer to make smaller blocks such that they will always fit within this limit.

**Comment by AgeManning** [comment]
@michaelsproul @paulhauner - Thoughts on this bad boy

**Comment by paulhauner** [comment]
Since all of the fields on the block are either fixed-length or variable length with a maximum capacity I would hope that it's impossible to construct a `SignedBeaconBlock` larger than the maximum network message size.

We could do the math and determine this ourselves, but perhaps someone like @djrtwo has already done it? If it's possible to produce oversize blocks I'd be thinking that's a spec issue.

**Comment by pawanjay176** [comment]
I was using [this](https://github.com/sigp/lighthouse/blob/67a935a9cdf623c1b3461cef689f58ca494db7bf/eth2/types/src/beacon_block.rs#L52) to get a max sized beacon block for some network testing. From the function, the ssz encoded length of a full block (max capacity) is 124384 bytes.

**Comment by paulhauner** [comment]
Nice @pawanjay176! Given those figures I think we can close this issue?

**Comment by AgeManning** [comment]
I guess this may become more relevant in later phases. Happy to close for now if we are happy we can't hit the limit

**Comment by paulhauner** [comment]
Closing since everyone seems happy to close
